import {test} from 'node:test';
import assert from 'node:assert/strict';
import {freshProject,area,validateProject,migrateProject,pushHistory,undo,redo,distance,angle} from '../src/core.mjs';
import {createGeometry,resizeRectangle,resizeEdge,vertices,edges,moveObjects,duplicateObjects,deleteObjects,toggleLock,changedEdges} from '../src/geometry.mjs';
const creation={type:'plot',name:'Участок',thickness:.2};
function rectangle(w=20,h=30,type='plot'){return createGeometry(freshProject(),{...creation,type},[{x:0,y:0},{x:w,y:0},{x:w,y:h},{x:0,y:h}],'rectangle').project;}
test('Участок 20×30: 600 м²; постройка 8×10 → 8×12: 80 → 96 м²',()=>{const plot=rectangle();assert.equal(area(vertices(plot,plot.objects[0])),600);const building=rectangle(10,8,'building'),id=building.objects[0].id;assert.equal(area(vertices(building,building.objects[0])),80);const resized=resizeRectangle(building,id,12,8,0,'start');validateProject(resized);assert.equal(area(vertices(resized,resized.objects[0])),96);assert.deepEqual(vertices(resized,resized.objects[0])[0],vertices(building,building.objects[0])[0]);});
test('Поворот и размер прямоугольника сохраняют выбранный центр',()=>{const p=rectangle(8,10),id=p.objects[0].id,next=resizeRectangle(p,id,12,8,37,'center');validateProject(next);const vs=vertices(next,next.objects[0]);assert.ok(Math.abs(vs.reduce((s,n)=>s+n.x,0)/4-4)<1e-8);assert.ok(Math.abs(vs.reduce((s,n)=>s+n.y,0)/4-5)<1e-8);assert.ok(Math.abs(area(vs)-96)<1e-8);});
test('Стена 4,2 → 5 м сохраняет направление и начальный узел, обновляет соседнюю стену',()=>{const p=createGeometry(freshProject(),{...creation,type:'wall'},[{x:0,y:0},{x:4.2,y:0},{x:4.2,y:3}],'wall').project;const [wall,nextWall]=p.objects;assert.equal(wall.vertexIds[1],nextWall.vertexIds[0]);const next=resizeEdge(p,wall.id,0,5,'start');validateProject(next);assert.deepEqual(next.nodes[wall.vertexIds[0]],p.nodes[wall.vertexIds[0]]);assert.equal(angle(...vertices(next,wall)),0);assert.equal(distance(...vertices(next,wall)),5);assert.equal(vertices(next,nextWall)[0].x,5);assert.equal(changedEdges(p,next).length,2);});
test('Неподвижный конец и центр стены действительно сохраняются',()=>{const p=createGeometry(freshProject(),{...creation,type:'wall'},[{x:1,y:2},{x:5,y:5}],'wall').project,o=p.objects[0];const end=resizeEdge(p,o.id,0,7,'end');assert.deepEqual(vertices(end,o)[1],vertices(p,o)[1]);const centered=resizeEdge(p,o.id,0,8,'center');const vs=vertices(centered,o);assert.ok(Math.abs((vs[0].x+vs[1].x)/2-3)<1e-8);assert.ok(Math.abs((vs[0].y+vs[1].y)/2-3.5)<1e-8);});
test('Заблокированная соседняя сторона отклоняет конфликт, исходник и история целы',()=>{const p0=createGeometry(freshProject(),creation,[{x:0,y:0},{x:4,y:0},{x:5,y:3},{x:0,y:3}],'polygon').project;const p=toggleLock(p0,p0.objects[0].id,1,'length');const saved=JSON.stringify(p),candidate=resizeEdge(p,p.objects[0].id,0,7,'start');assert.throws(()=>validateProject(candidate),/Конфликт/);assert.equal(JSON.stringify(p),saved);const h=pushHistory({past:[],present:p,future:[]},toggleLock(p,p.objects[0].id,1,'length'));assert.deepEqual(undo(h).present,p);});
test('Самопересечение и совпадающие стены отклоняются',()=>{assert.throws(()=>createGeometry(freshProject(),creation,[{x:0,y:0},{x:4,y:4},{x:0,y:4},{x:4,y:0}],'polygon'),/самопересечение/);const p=createGeometry(freshProject(),{...creation,type:'wall'},[{x:0,y:0},{x:4,y:0}],'wall').project;assert.throws(()=>createGeometry(p,{...creation,type:'wall'},[{x:1,y:0},{x:5,y:0}],'wall'),/накладываются/);});
test('Перенос и копирование цепочки сохраняют общие узлы; undo восстанавливает удаление',()=>{const p=createGeometry(freshProject(),{...creation,type:'wall'},[{x:0,y:0},{x:4,y:0},{x:4,y:3}],'wall').project,ids=p.objects.map(o=>o.id);const moved=moveObjects(p,ids,2,3);assert.equal(moved.nodes[p.objects[0].vertexIds[1]].x,6);const {project:copy,ids:newIds}=duplicateObjects(p,ids);validateProject(copy);const clones=copy.objects.filter(o=>newIds.includes(o.id));assert.equal(clones[0].vertexIds[1],clones[1].vertexIds[0]);assert.notEqual(clones[0].vertexIds[1],p.objects[0].vertexIds[1]);const deleted=deleteObjects(copy,newIds);validateProject(deleted);assert.equal(Object.keys(deleted.nodes).length,3);const h=pushHistory({past:[],present:copy,future:[]},deleted);assert.deepEqual(undo(h).present,copy);assert.deepEqual(redo(undo(h)).present,deleted);});
test('Старый проект первого этапа переносится без потери размеров и ревизии',()=>{const old={...freshProject(),schemaVersion:1,revision:4,objects:[{id:'legacy',type:'outline',name:'Старый план',vertices:[{x:0,y:0},{x:20,y:0},{x:20,y:30},{x:0,y:30}]}]};delete old.nodes;const migrated=validateProject(migrateProject(old));assert.equal(migrated.schemaVersion,2);assert.equal(migrated.revision,4);assert.equal(area(vertices(migrated,migrated.objects[0])),600);});
test('Несуществующие узлы, неверные координаты и дубли ID отклоняются',()=>{const p=rectangle();const id=p.objects[0].vertexIds[0];assert.throws(()=>validateProject({...p,nodes:{...p.nodes,[id]:{...p.nodes[id],x:Infinity}}}));assert.throws(()=>validateProject({...p,objects:[...p.objects,p.objects[0]]}));const nodes={...p.nodes};delete nodes[id];assert.throws(()=>validateProject({...p,nodes}));});

test('Замкнутая цепочка стен использует общий первый/последний узел',()=>{const p=createGeometry(freshProject(),{...creation,type:'wall'},[{x:0,y:0},{x:5,y:0},{x:5,y:4},{x:0,y:4},{x:0,y:0}],'wall').project;validateProject(p);assert.equal(p.objects.length,4);assert.equal(Object.keys(p.nodes).length,4);assert.equal(p.objects[0].vertexIds[0],p.objects[3].vertexIds[1]);});
test('Внешняя стена постройки не может стать независимым источником контура',()=>{const p=rectangle(8,10,'building'),building=p.objects[0];const wall=createGeometry(p,{...creation,type:'wall',wallKind:'external'},[{x:0,y:0},{x:8,y:0}],'wall',building.vertexIds.slice(0,2)).project;wall.objects.at(-1).buildingId=building.id;validateProject(wall);const altered=resizeEdge(wall,wall.objects.at(-1).id,0,9);assert.throws(()=>validateProject(altered),/прямоугольность/);});

test('Т-образное примыкание создаёт общий узел и делит исходную стену',()=>{const p=createGeometry(freshProject(),{...creation,type:'wall'},[{x:0,y:0},{x:6,y:0}],'wall').project;const next=createGeometry(p,{...creation,type:'wall'},[{x:3,y:0},{x:3,y:4}],'wall').project;validateProject(next);assert.equal(next.objects.length,3);const center=Object.values(next.nodes).find(n=>n.x===3&&n.y===0);assert.equal(next.objects.filter(o=>o.vertexIds.includes(center.id)).length,3);const moved={...next,nodes:{...next.nodes,[center.id]:{...center,x:4}}};validateProject(moved);assert.equal(edges(moved,moved.objects[0])[0].length,4);});
test('Создание Т-узла не разрушает заблокированную длину стены',()=>{const p0=createGeometry(freshProject(),{...creation,type:'wall'},[{x:0,y:0},{x:6,y:0}],'wall').project;const p=toggleLock(p0,p0.objects[0].id,0,'length');assert.throws(()=>createGeometry(p,{...creation,type:'wall'},[{x:3,y:0},{x:3,y:4}],'wall'),/Снимите ограничения/);assert.equal(p.objects.length,1);});
