import {test} from 'node:test';import assert from 'node:assert/strict';
import {freshProject,validateProject,pushHistory,undo,redo} from '../src/core.mjs';
import {createGeometry,duplicateObjects,deleteObjects,moveObjects} from '../src/geometry.mjs';
import {contourArea,contourPath} from '../src/contour-math.mjs';
import {contourEdgeToArc,addCurvedWall,splitCurvedWall,splitCircularWall,wallLength,wallCurve} from '../src/curved-walls.mjs';
import {joinCompatibleWalls,trimWallToPoint,wallIntersections,editJointAngle} from '../src/wall-editing.mjs';
const contour=()=>createGeometry(freshProject(),{type:'outline',name:'Покрытие'},[{x:0,y:0},{x:4,y:0},{x:4,y:4},{x:0,y:4}],'polygon').project;
test('Площадь кривого покрытия точна; копия, перенос, разбиение и удаление сохраняют ссылки',()=>{const base=contour(),o=base.objects[0],p=validateProject(contourEdgeToArc(base,o.id,0,90)),w=p.objects.find(o=>o.curve),expected=16+2*(Math.PI-2);assert.ok(Math.abs(contourArea(p,p.objects[0])-expected)<1e-9);assert.match(contourPath(p,p.objects[0]),/ A /);const moved=validateProject(moveObjects(p,[o.id],3,2));assert.ok(Math.abs(contourArea(moved,moved.objects[0])-expected)<1e-9);const copy=duplicateObjects(p,[o.id],10,0);validateProject(copy.project);const copied=copy.project.objects.find(n=>n.id===copy.ids[0]);assert.notEqual(copied.boundaryWallIds[0],w.id);const split=validateProject(splitCurvedWall(p,w.id,.5));assert.equal(split.objects.find(n=>n.id===o.id).vertexIds.length,5);assert.ok(Math.abs(contourArea(split,split.objects.find(n=>n.id===o.id))-expected)<1e-9);const deleted=validateProject(deleteObjects(p,[w.id]));assert.equal(contourArea(deleted,deleted.objects[0]),16);const h=pushHistory({past:[],present:base,future:[]},p);assert.deepEqual(undo(h).present,base);assert.deepEqual(redo(undo(h)).present,p)});
test('Окружность разделяется по метке на две дуги с сохранением окна',()=>{const added=addCurvedWall(freshProject(),{kind:'circle',center:{x:0,y:0},radius:2,startAngle:30,sweepAngle:360});const p={...added.project,openings:[{id:'window',name:'Окно',type:'window',kind:'curved',wallId:added.id,width:.4,offset:8,anchor:'start',height:1.4,hinge:'start',side:1}]};const split=validateProject(splitCircularWall(p,added.id,.5));assert.equal(split.objects.length,2);assert.equal(split.objects[0].curve.kind,'arc');assert.ok(Math.abs(split.objects.reduce((s,w)=>s+wallLength(split,w),0)-4*Math.PI)<1e-9);assert.notEqual(split.openings[0].wallId,added.id);assert.throws(()=>splitCircularWall({...p,openings:[{...p.openings[0],offset:12.4}]},added.id),/метку/)});
test('Соединение разделённой дуги восстанавливает параметры; продление выбирает пересечение окружности',()=>{const added=addCurvedWall(freshProject(),{kind:'arc',center:{x:0,y:0},radius:2,startAngle:0,sweepAngle:90});const split=splitCurvedWall(added.project,added.id,.4),joined=validateProject(joinCompatibleWalls(split,split.objects.map(o=>o.id)));assert.equal(joined.objects.length,1);assert.ok(Math.abs(joined.objects[0].curve.sweepAngle-90)<1e-8);const extended=validateProject(trimWallToPoint(joined,added.id,{x:-2,y:0}));assert.equal(extended.objects[0].curve.sweepAngle,180);assert.equal(joined.objects[0].curve.sweepAngle,90)});
test('Угловые ограничения копируются с новыми ID и удаляются вместе со стеной',()=>{const made=createGeometry(freshProject(),{type:'wall',name:'Стык',thickness:.2},[{x:0,y:0},{x:2,y:0},{x:2,y:2}],'wall');const p=validateProject(editJointAngle(made.project,made.ids,60,made.ids[1],1,true)),copy=duplicateObjects(p,made.ids,10,0);validateProject(copy.project);assert.equal(copy.project.jointConstraints.length,2);assert.notEqual(copy.project.jointConstraints[0].nodeId,copy.project.jointConstraints[1].nodeId);assert.equal(validateProject(deleteObjects(p,[made.ids[1]])).jointConstraints.length,0)});
test('Перекрывающиеся дуги и самопересечение кривого контура отклоняются',()=>{const a=addCurvedWall(freshProject(),{kind:'arc',center:{x:0,y:0},radius:2,startAngle:0,sweepAngle:90});assert.throws(()=>validateProject(addCurvedWall(a.project,{kind:'arc',center:{x:0,y:0},radius:2,startAngle:80,sweepAngle:90}).project),/Совпадающие/);const base=contour();assert.throws(()=>validateProject(contourEdgeToArc(base,base.objects[0].id,0,-270)),/пересекает/)});

test('Новый узел в середине дуги разделяет её и создаёт настоящий Т-стык',()=>{const a=addCurvedWall(freshProject(),{kind:'arc',center:{x:0,y:0},radius:2,startAngle:0,sweepAngle:90});const middle={x:Math.sqrt(2),y:Math.sqrt(2)};const made=createGeometry(a.project,{type:'wall',name:'Перегородка',thickness:.2},[middle,{x:3,y:3}],'wall');const p=validateProject(made.project),line=p.objects.find(o=>o.id===made.ids[0]);assert.equal(p.objects.filter(o=>o.curve).length,2);assert.equal(p.objects.filter(o=>o.vertexIds.includes(line.vertexIds[0])).length,3);assert.equal(a.project.objects.length,1)});
test('Две половины окружности соединяются обратно в замкнутую сущность',()=>{const a=addCurvedWall(freshProject(),{kind:'circle',center:{x:0,y:0},radius:2,startAngle:30,sweepAngle:360});const split=splitCircularWall(a.project,a.id);const joined=validateProject(joinCompatibleWalls(split,split.objects.map(o=>o.id)));assert.equal(joined.objects.length,1);assert.equal(joined.objects[0].curve.kind,'circle');assert.equal(joined.objects[0].vertexIds.length,1);assert.equal(joined.objects[0].id,a.id)});
