import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import {freshProject,validateProject,pushHistory,undo,redo,distance,area} from '../src/core.mjs';
import {createGeometry,resizeEdge,moveObjects,duplicateObjects,deleteObjects,splitWall,vertices,resizeRectangle} from '../src/geometry.mjs';
import {createOpening,openingGeometry,changeOpeningAnchor,moveOpening,wallSpans} from '../src/openings.mjs';
import {parallelWall,parallelWalls,alignObjects,distributeObjects,transformObjects,bounds} from '../src/commands.mjs';
import {snapPoint,defaultSnapSettings} from '../src/snapping.mjs';
import {storage} from '../server/storage.mjs';
import {exampleProject} from '../src/examples.mjs';
const creation={type:'wall',name:'Стена',thickness:.2,wallKind:'external'};
function wall(length=4.2){return createGeometry(freshProject(),creation,[{x:0,y:0},{x:length,y:0}],'wall').project;}
function door(p,offset=1.2,width=.9){return createOpening(p,p.objects[0].id,'door',offset,width).project;}
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} ≠ ${b}`);
test('Дом переносится и копируется со стенами, перегородкой и проёмами как единая группа',()=>{
 const p=exampleProject(),house=p.objects.find(o=>o.type==='building'),opening=p.openings[0];validateProject(p);
 const moved=moveObjects(p,[house.id,opening.id],20,30);validateProject(moved);
 for(const o of p.openings){const before=openingGeometry(p,o),after=openingGeometry(moved,o);near(after.a.x,before.a.x+20);near(after.a.y,before.a.y+30);near(after.start,before.start);}
 const copy=duplicateObjects(p,[house.id],40,0).project;validateProject(copy);
 const clonedHouse=copy.objects.find(o=>o.type==='building'&&o.id!==house.id);
 assert.equal(copy.objects.filter(o=>o.buildingId===clonedHouse.id).length,p.objects.filter(o=>o.buildingId===house.id).length);
 assert.equal(copy.openings.length,p.openings.length*2);
 const removed=deleteObjects(copy,[clonedHouse.id]);validateProject(removed);assert.equal(removed.openings.length,p.openings.length);assert.equal(removed.objects.length,p.objects.length);
});
test('Прямоугольник с дверью меняет габариты, сохраняя ширину и отступ проёма',()=>{
 let p=createGeometry(freshProject(),{type:'building',name:'Дом'},[{x:0,y:0},{x:8,y:0},{x:8,y:10},{x:0,y:10}],'rectangle').project;
 const b=p.objects[0],chain=createGeometry(p,creation,[p.nodes[b.vertexIds[0]],p.nodes[b.vertexIds[1]]],'wall',b.vertexIds.slice(0,2));p=chain.project;p.objects[1].buildingId=b.id;p=createOpening(p,p.objects[1].id,'door',1.2,.9).project;
 const resized=resizeRectangle(p,b.id,12,10,30);validateProject(resized);near(area(vertices(resized,resized.objects[0])),120);near(openingGeometry(resized,resized.openings[0]).start,1.2);near(resized.openings[0].width,.9);
});
test('Замкнутая параллельная цепочка сохраняет стыки и отвергает схлопывание',()=>{
 const p=createGeometry(freshProject(),creation,[{x:0,y:0},{x:5,y:0},{x:5,y:5},{x:0,y:5},{x:0,y:0}],'wall').project,ids=p.objects.map(o=>o.id);
 const next=parallelWalls(p,ids,1);validateProject(next);const added=next.objects.slice(4);
 for(let i=0;i<4;i++){assert.equal(added[i].vertexIds[1],added[(i+1)%4].vertexIds[0]);near(distance(next.nodes[added[i].vertexIds[0]],next.nodes[added[i].vertexIds[1]]),3);}
 assert.throws(()=>parallelWalls(p,ids,3),/схлопывает/);
});
test('Дверь 0,9 м / отступ 1,2 м следует за переносом, поворотом и изменением стены',()=>{const p=door(wall()),id=p.objects[0].id,o=p.openings[0];const longer=resizeEdge(p,id,0,5);validateProject(longer);near(openingGeometry(longer,o).a.x,1.2);const moved=moveObjects(longer,[id,o.id],3,4);validateProject(moved);near(openingGeometry(moved,o).a.x,4.2);near(openingGeometry(moved,o).a.y,4);const turned=transformObjects(moved,[id],90);validateProject(turned);const g=openingGeometry(turned,o);near(g.angle,90);near(distance(turned.nodes[turned.objects[0].vertexIds[0]],g.a),1.2);near(o.width,.9);});
test('Укорочение стены вызывает конфликт, не сужает дверь и не изменяет исходник',()=>{const p=door(wall()),source=JSON.stringify(p),short=resizeEdge(p,p.objects[0].id,0,2);assert.throws(()=>validateProject(short),/слишком короткая/);assert.equal(JSON.stringify(p),source);near(short.openings[0].width,.9);});
test('Отступ от конца сохраняется при росте стены; смена опоры не сдвигает проём',()=>{const p=door(wall(5)),id=p.openings[0].id,end=changeOpeningAnchor(p,id,'end');validateProject(end);near(openingGeometry(end,end.openings[0]).a.x,1.2);const lengthened=resizeEdge(end,p.objects[0].id,0,6);validateProject(lengthened);near(openingGeometry(lengthened,lengthened.openings[0]).a.x,2.2);near(lengthened.openings[0].offset,end.openings[0].offset);});
test('Стена физически разбивается на видимые интервалы вокруг проёма',()=>{const p=door(wall(5)),spans=wallSpans(p,p.objects[0]);assert.equal(spans.length,2);near(spans[0].b.x,1.2);near(spans[1].a.x,2.1);});
test('Проёмы за стеной и пересечения отвергаются до сохранения',()=>{const p=door(wall(5));assert.throws(()=>createOpening(p,p.objects[0].id,'window',1.5,1.2),/пересекаются/);assert.throws(()=>createOpening(p,p.objects[0].id,'window',4.5,1.2),/короткая/);const shifted=moveOpening(p,p.openings[0].id,-2,0);assert.throws(()=>validateProject(shifted));});
test('Копия стены получает новые связанные проёмы, удаление и undo/redo атомарны',()=>{const p=door(wall(5)),copy=duplicateObjects(p,[p.objects[0].id]).project;validateProject(copy);assert.equal(copy.openings.length,2);assert.notEqual(copy.openings[0].id,copy.openings[1].id);assert.equal(copy.openings[1].wallId,copy.objects[1].id);const deleted=deleteObjects(copy,[copy.objects[1].id]);assert.equal(deleted.openings.length,1);const history=pushHistory({past:[],present:copy,future:[]},deleted);assert.deepEqual(undo(history).present,copy);assert.deepEqual(redo(undo(history)).present,deleted);});
test('Разделение стены переносит проём на правильную половину; пересечение проёма не допускается',()=>{const p=door(wall(8),5,.9),split=splitWall(p,p.objects[0].id);validateProject(split);assert.equal(split.openings[0].wallId,split.objects[1].id);near(split.openings[0].offset,1);near(openingGeometry(split,split.openings[0]).a.x,5);const crossing=door(wall(8),3.7,.9);assert.throws(()=>splitWall(crossing,crossing.objects[0].id),/пересекает проём/);});
test('Параллельная стена различает оси и чистый просвет; копия независима',()=>{const p=door(wall(5)),axes=parallelWall(p,p.objects[0].id,1,1,'axes',.4,true),clear=parallelWall(p,p.objects[0].id,1,1,'clear',.4,false);validateProject(axes);validateProject(clear);near(axes.nodes[axes.objects[1].vertexIds[0]].y,1);near(clear.nodes[clear.objects[1].vertexIds[0]].y,1.3);assert.equal(axes.openings.length,2);assert.equal(clear.openings.length,1);assert.notEqual(axes.objects[1].vertexIds[0],p.objects[0].vertexIds[0]);});
test('Параллельная ломаная имеет общий стык и не повреждает исходную цепочку',()=>{const p=createGeometry(freshProject(),creation,[{x:0,y:0},{x:5,y:0},{x:5,y:5}],'wall').project,source=JSON.stringify(p),next=parallelWalls(p,p.objects.map(o=>o.id),1);validateProject(next);const [a,b]=next.objects.slice(2);assert.equal(a.vertexIds[1],b.vertexIds[0]);near(next.nodes[a.vertexIds[1]].x,4);near(next.nodes[a.vertexIds[1]].y,1);assert.equal(JSON.stringify(p),source);});
test('Привязка к концам и серединам имеет одинаковый допуск в px на разных масштабах; Alt отключает',()=>{const p=wall(10);for(const scale of [10,25,100]){let hit=snapPoint(p,{x:5,y:5/scale},scale,defaultSnapSettings);assert.equal(hit.label,'Середина');near(hit.point.x,5);near(hit.point.y,0);hit=snapPoint(p,{x:5,y:5/scale},scale,defaultSnapSettings,{disabled:true});near(hit.point.y,5/scale);}});
test('Пересечение, продолжение и перпендикулярность выбираются независимо',()=>{let p=wall(10);p=createGeometry(p,creation,[{x:5,y:-5},{x:5,y:5}],'wall').project;const off={...defaultSnapSettings,nodes:false,midpoints:false,walls:false,guides:false,centers:false,extensions:false,grid:false};assert.equal(snapPoint(p,{x:5.03,y:.04},25,off).label,'Пересечение');const ext={...off,intersections:false,extensions:true};assert.equal(snapPoint(p,{x:12,y:.1},25,ext).label,'Продолжение');const perp={...off,intersections:false,relation:'perpendicular'};const hit=snapPoint(p,{x:2.05,y:3},25,perp,{origin:{x:2,y:0},referenceId:p.objects[0].id});assert.equal(hit.label,'Перпендикулярно опоре');near(hit.point.x,2);});
test('Выравнивание и распределение сохраняют выбранную опору',()=>{let p=freshProject();for(const [x,y] of [[0,0],[4,3],[12,7]])p=createGeometry(p,{type:'building',name:'Дом',thickness:.2},[{x,y},{x:x+2,y},{x:x+2,y:y+2},{x,y:y+2}],'rectangle').project;const ids=p.objects.map(o=>o.id),aligned=alignObjects(p,ids,'top',ids[1]);validateProject(aligned);for(const id of ids)near(bounds(aligned,[id]).top,3);assert.deepEqual(vertices(aligned,aligned.objects[1]),vertices(p,p.objects[1]));const distributed=distributeObjects(p,ids,'x',ids[1]);near(bounds(distributed,[ids[1]]).cx,5);near(bounds(distributed,[ids[1]]).cx-bounds(distributed,[ids[0]]).cx,bounds(distributed,[ids[2]]).cx-bounds(distributed,[ids[1]]).cx);});
test('Отражение двери сохраняет физическую сторону открывания; габариты отражённого прямоугольника редактируются',()=>{const p=door(wall(5)),mirror=transformObjects(p,[p.objects[0].id],0,'mirrorX');validateProject(mirror);assert.equal(mirror.openings[0].side,-1);let rect=createGeometry(freshProject(),{type:'building',name:'Дом',thickness:.2},[{x:0,y:0},{x:8,y:0},{x:8,y:10},{x:0,y:10}],'rectangle').project;rect=transformObjects(rect,[rect.objects[0].id],0,'mirrorX');const before=vertices(rect,rect.objects[0])[0];const resized=resizeRectangle(rect,rect.objects[0].id,12,10,180);validateProject(resized);near(area(vertices(resized,resized.objects[0])),120);assert.deepEqual(vertices(resized,resized.objects[0])[0],before);});
test('Серверное сохранение восстанавливает связи двери и стены, старые проекты получают пустой список проёмов',async()=>{const root=await mkdtemp(path.join(os.tmpdir(),'home-planer-openings-'));try{const db=storage(root),p=door(wall(5)),saved=await db.save(p),loaded=await db.get(saved.id);assert.equal(loaded.openings[0].wallId,loaded.objects[0].id);near(openingGeometry(loaded,loaded.openings[0]).start,1.2);const old={...p};delete old.openings;assert.deepEqual(validateProject(old).openings,[]);}finally{await rm(root,{recursive:true,force:true})}});
