import {readFile,writeFile,rename,mkdir,copyFile,readdir} from 'node:fs/promises';
import path from 'node:path';
import {validateProject} from '../src/core.mjs';
export function storage(root){
 const safe=id=>{if(typeof id!=='string'||!/^[a-zA-Z0-9-]{1,80}$/.test(id))throw Error('Некорректный ID');return id};
 const file=id=>path.join(root,safe(id)+'.json'),folder=id=>path.join(root,'.versions',safe(id));
 const revision=n=>{if(!Number.isSafeInteger(n)||n<1)throw Error('Некорректная ревизия');return n};
 const archive=async(p,label=null)=>{if(p.revision<1)return;await mkdir(folder(p.id),{recursive:true});const target=path.join(folder(p.id),revision(p.revision)+'.json');try{await writeFile(target,JSON.stringify({revision:p.revision,label,createdAt:p.updatedAt,document:p},null,2),{encoding:'utf8',flag:'wx'})}catch(e){if(e.code!=='EEXIST')throw e}};
 const archivePrevious=async id=>{try{const previous=JSON.parse(await readFile(file(id)+'.bak','utf8'));if(previous.id!==id)throw Error('ID предыдущей версии не совпадает');await archive(previous)}catch(e){if(e.code!=='ENOENT')throw e}};
 const get=async id=>validateProject(JSON.parse(await readFile(file(id),'utf8')));
 return {async list(){await mkdir(root,{recursive:true});const files=await readdir(root);return Promise.all(files.filter(f=>/^[a-zA-Z0-9-]+\.json$/.test(f)).map(async f=>{const p=JSON.parse(await readFile(path.join(root,f),'utf8'));return {id:p.id,name:p.name,updatedAt:p.updatedAt,revision:p.revision}}));},get,
 async versions(id){const p=await get(id);await archivePrevious(id);await archive(p);await mkdir(folder(id),{recursive:true});const names=await readdir(folder(id));return (await Promise.all(names.filter(n=>/^[0-9]+\.json$/.test(n)).map(async n=>{const v=JSON.parse(await readFile(path.join(folder(id),n),'utf8'));return{revision:v.revision,label:v.label,createdAt:v.createdAt}}))).sort((a,b)=>b.revision-a.revision)},
 async version(id,n){const v=JSON.parse(await readFile(path.join(folder(id),revision(n)+'.json'),'utf8'));if(v.document.id!==id||v.document.revision!==n)throw Error('Повреждённая сохранённая версия');return validateProject(v.document)},
 async save(input,label=null){if(label!==null&&(typeof label!=='string'||!label.trim()||label.length>80))throw Error('Название контрольной точки: от 1 до 80 символов');const p=validateProject(input);if(p.variantSnapshot)throw Error('Внутренний снимок нельзя сохранять отдельным проектом');if(p.revision>=Number.MAX_SAFE_INTEGER)throw Error('Достигнут предел ревизий');if(Buffer.byteLength(JSON.stringify(p))>5*1024*1024)throw Error('Проект превышает 5 МБ; уменьшите число вариантов');await mkdir(root,{recursive:true});let old;try{old=JSON.parse(await readFile(file(p.id),'utf8'))}catch(e){if(e.code!=='ENOENT')throw e}if((old?.revision??0)!==p.revision){const e=Error('Проект изменён на другом устройстве');e.status=409;throw e}if(old?.schemaVersion>p.schemaVersion){const e=Error('Старый формат не может перезаписать расширенный проект');e.status=409;throw e}if(old){await archivePrevious(p.id);await archive(old)}const next=validateProject({...p,revision:p.revision+1,updatedAt:new Date().toISOString()});const temp=file(p.id)+'.tmp';await writeFile(temp,JSON.stringify(next,null,2),'utf8');if(old)await copyFile(file(p.id),file(p.id)+'.bak');await rename(temp,file(p.id));await archive(next,label?.trim()??null);return next;}};
}
