import {defaultLayerId} from './layers.mjs';
export const drawingLayers=()=>[{id:'annotations',name:'Разметка',visible:true,locked:false},{id:'guidelines',name:'Направляющие',visible:true,locked:false}];
export const stage2Project=p=>({...p,schemaVersion:Math.max(p.schemaVersion,4),layers:[...p.layers,...drawingLayers().filter(l=>!p.layers.some(n=>n.id===l.id))]});
export const palette=['#50545b','#000000','#ffffff','#c99108','#337e9b','#ba6545','#655d53','#79a66b'];
export function validateStyle(style){if(style===undefined)return;if(!style||typeof style!=='object'||Array.isArray(style))throw Error('Некорректное оформление');for(const [k,v] of Object.entries(style)){if(['stroke','fill'].includes(k)){if(typeof v!=='string'||!/^#[a-fA-F0-9]{6}$/.test(v)&&!(k==='fill'&&v==='none'))throw Error('Цвет должен быть HEX #RRGGBB')}else if(k==='opacity'){if(!Number.isFinite(v)||v<0||v>1)throw Error('Непрозрачность: 0–1')}else if(k==='screenWidth'){if(!Number.isFinite(v)||v<=0||v>30)throw Error('Экранная толщина: 0–30 px')}else if(k==='dash'){if(!['solid','dash','dot'].includes(v))throw Error('Некорректный тип линии')}else if(k==='hatch'){if(!['none','diagonal','cross'].includes(v))throw Error('Некорректная штриховка')}else throw Error('Неизвестное свойство оформления')}}
export function resolvedStyle(p,o){return{stroke:o.color??'#50545b',fill:['wall','guide'].includes(o.type)?'none':'#edf3e7',opacity:1,screenWidth:1.5,dash:'solid',hatch:'none',...p.layers.find(l=>l.id===(o.layerId??defaultLayerId(o)))?.style,...o.style}}
export function editStyle(p,ids,key,value){if(value!==undefined)validateStyle({[key]:value});const change=o=>{if(!ids.includes(o.id))return o;const style={...o.style};if(value===undefined)delete style[key];else style[key]=value;return{...o,style}};const next=stage2Project(p);return{...next,objects:p.objects.map(change),openings:p.openings.map(change),settings:{...p.settings,recentColors:typeof value==='string'&&value.startsWith('#')?[value,...(p.settings.recentColors??[]).filter(c=>c!==value)].slice(0,12):p.settings.recentColors??[]}}}
export const styleFamily=o=>['wall','door','window'].includes(o.type)?o.type:['pipe','wire','guide'].includes(o.type)?'line':o.type==='annotation'?(o.drawingKind==='text'||o.drawingKind==='leader'?'text':'drawing'):o.type==='fixture'?'fixture':'shape';
export function copyStyle(p,sourceId,targetIds){const all=[...p.objects,...p.openings],source=all.find(o=>o.id===sourceId);if(!source)throw Error('Выберите источник оформления');if(targetIds.some(id=>styleFamily(all.find(o=>o.id===id)??{})!==styleFamily(source)))throw Error('Оформление можно копировать только между совместимыми элементами');const next=stage2Project(p),change=o=>targetIds.includes(o.id)?{...o,style:{...resolvedStyle(p,source)},labelVisible:source.labelVisible}:o;return{...next,objects:p.objects.map(change),openings:p.openings.map(change)}}
export const dashArray=(style,scale)=>style.dash==='dash'?`${7/scale} ${4/scale}`:style.dash==='dot'?`${1/scale} ${3/scale}`:undefined;
export const labelsShown=(p,o)=>o.labelVisible!==false&&p.layers.find(l=>l.id==='labels')?.visible!==false;
export function monochromeProject(p){const gray=c=>{if(c==='none')return c;const rgb=[1,3,5].map(i=>parseInt(c.slice(i,i+2),16));const n=Math.round(rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722).toString(16).padStart(2,'0');return'#'+n.repeat(3)};const change=o=>{const s=resolvedStyle(p,o);return{...o,color:o.color?gray(o.color):undefined,style:{...s,stroke:gray(s.stroke),fill:gray(s.fill)}}};return{...p,layers:p.layers.map(l=>({...l,style:l.style?{...l.style,stroke:l.style.stroke?gray(l.style.stroke):undefined,fill:l.style.fill?gray(l.style.fill):undefined}:undefined})),objects:p.objects.map(change),openings:p.openings.map(change)}}

export function straightWallOutline(span,thickness){const {a,b}=span,l=Math.hypot(b.x-a.x,b.y-a.y),dx=-(b.y-a.y)/l*thickness/2,dy=(b.x-a.x)/l*thickness/2;return 'M '+[a.x+dx,a.y+dy].join(' ')+' L '+[b.x+dx,b.y+dy].join(' ')+' L '+[b.x-dx,b.y-dy].join(' ')+' L '+[a.x-dx,a.y-dy].join(' ')+' Z'}
