import {resolveEngineering} from './engineering-math.mjs';
import {angle,distance,validateProject} from './core.mjs';
import {vertices,edges,moveObjects,duplicateObjects,expandSelection} from './geometry.mjs';
import {openingGeometry} from './openings.mjs';
/** @param {import('./types').Project} p @param {string[]} ids */
export function bounds(p,ids){const points=p.objects.filter(o=>ids.includes(o.id)).flatMap(o=>vertices(p,o));for(const o of p.openings??[])if(ids.includes(o.id)){const g=openingGeometry(p,o);points.push(g.a,g.b)}if(!points.length)throw Error('Выберите объект');const left=Math.min(...points.map(n=>n.x)),right=Math.max(...points.map(n=>n.x)),top=Math.min(...points.map(n=>n.y)),bottom=Math.max(...points.map(n=>n.y));return{left,right,top,bottom,cx:(left+right)/2,cy:(top+bottom)/2};}
/** @param {import('./types').Project} p @param {string[]} ids @param {'left'|'right'|'top'|'bottom'|'cx'|'cy'} mode @param {string} referenceId @returns {import('./types').Project} */
export function alignObjects(p,ids,mode,referenceId){if(ids.length<2||!ids.includes(referenceId))throw Error('Выберите два объекта и опору');assertIndependent(p,ids);const reference=bounds(p,[referenceId]);let next=p;for(const id of ids.filter(id=>id!==referenceId)){const b=bounds(p,[id]),delta=reference[mode]-b[mode];next=moveObjects(next,[id],['left','right','cx'].includes(mode)?delta:0,['top','bottom','cy'].includes(mode)?delta:0);}return next;}
/** @param {import('./types').Project} p @param {string[]} ids */
function assertIndependent(p,ids){const seen=new Set();for(const o of p.objects.filter(o=>ids.includes(o.id))){for(const id of o.vertexIds){if(seen.has(id))throw Error('Выравнивание связанных объектов изменило бы общие узлы. Выберите независимые объекты');seen.add(id)}}if((p.openings??[]).some(o=>ids.includes(o.id)))throw Error('Проёмы перемещаются вдоль своих стен; выравнивайте стены или используйте отступ проёма');}
/** @param {import('./types').Project} p @param {string[]} ids @param {'x'|'y'} axis @param {string} referenceId @returns {import('./types').Project} */
export function distributeObjects(p,ids,axis,referenceId){if(ids.length<3)throw Error('Для распределения нужны минимум три объекта');assertIndependent(p,ids);const key=axis==='x'?'cx':'cy',ordered=ids.map(id=>({id,b:bounds(p,[id])})).sort((a,b)=>a.b[key]-b.b[key]),step=(ordered.at(-1).b[key]-ordered[0].b[key])/(ids.length-1),refIndex=ordered.findIndex(o=>o.id===referenceId);if(refIndex<0)throw Error('Опора не выбрана');const start=ordered[refIndex].b[key]-refIndex*step;let next=p;ordered.forEach((item,i)=>{if(item.id!==referenceId)next=moveObjects(next,[item.id],axis==='x'?start+i*step-item.b[key]:0,axis==='y'?start+i*step-item.b[key]:0)});return next;}
/** @param {import('./types').Project} p @param {string[]} ids @param {number} degrees @param {'rotate'|'mirrorX'|'mirrorY'} mode @returns {import('./types').Project} */
export function transformObjects(p,ids,degrees=90,mode='rotate'){if(!Number.isFinite(degrees))throw Error('Неверный угол');ids=expandSelection(p,ids);const b=bounds(p,ids),set=new Set(p.objects.filter(o=>ids.includes(o.id)).flatMap(o=>o.vertexIds));if(!set.size)throw Error('Выберите геометрию; проём поворачивается со стеной');const radians=degrees*Math.PI/180,nodes={...p.nodes};for(const id of set){const n=nodes[id],x=n.x-b.cx,y=n.y-b.cy;nodes[id]={...n,x:b.cx+(mode==='mirrorX'?-x:mode==='mirrorY'?x:x*Math.cos(radians)-y*Math.sin(radians)),y:b.cy+(mode==='mirrorY'?-y:mode==='mirrorX'?y:x*Math.sin(radians)+y*Math.cos(radians))};}const affected=new Set(p.objects.filter(o=>o.type==='wall'&&o.vertexIds.every(id=>set.has(id))).map(o=>o.id));const openings=p.openings.map(o=>affected.has(o.wallId)&&mode!=='rotate'?{...o,side:-o.side}:o);const objects=p.objects.map(o=>{if(o.type!=='fixture'||!ids.includes(o.id))return o;if(o.wallMount&&!ids.includes(o.wallMount.wallId))throw Error('Поверните стену с закреплённым прибором или включите свободное размещение');return{...o,rotation:mode==='rotate'?(o.rotation??0)+degrees:mode==='mirrorX'?180-(o.rotation??0):-(o.rotation??0),mirror:mode==='rotate'?o.mirror:!o.mirror}});return resolveEngineering({...p,nodes,openings,objects});}
/** @param {import('./types').Project} p @param {string} wallId @param {number} distanceValue @param {1|-1} side @param {'axes'|'clear'} mode @param {number} thickness @param {boolean} withOpenings @returns {import('./types').Project} */
export function parallelWall(p,wallId,distanceValue,side=1,mode='axes',thickness=.2,withOpenings=false){const wall=p.objects.find(o=>o.id===wallId&&o.type==='wall');if(!wall)throw Error('Выберите стену');if(!Number.isFinite(distanceValue)||distanceValue<0||!Number.isFinite(thickness)||thickness<=0)throw Error('Введите неотрицательный отступ и положительную толщину');const es=edges(p,wall)[0],separation=distanceValue+(mode==='clear'?((wall.thickness??.2)+thickness)/2:0);if(separation<=1e-6)throw Error('Расстояние между осями должно быть больше нуля');const dx=-(es.b.y-es.a.y)/es.length*separation*side,dy=(es.b.x-es.a.x)/es.length*separation*side;const copied=duplicateObjects(p,[wall.id],dx,dy),newWall=copied.project.objects.find(o=>copied.ids.includes(o.id));return {...copied.project,objects:copied.project.objects.map(o=>o.id===newWall.id?{...o,name:wall.name+' (параллельно)',thickness,buildingId:undefined}:o),openings:copied.project.openings.filter(o=>withOpenings||o.wallId!==newWall.id)};}
/** @param {import('./types').Project} p @param {string[]} ids @param {number} value @param {1|-1} side @param {'axes'|'clear'} mode @param {number} thickness @param {boolean} withOpenings @returns {import('./types').Project} */
export function parallelWalls(p,ids,value,side=1,mode='axes',thickness=.2,withOpenings=false){if(ids.length===1)return parallelWall(p,ids[0],value,side,mode,thickness,withOpenings);if(!Number.isFinite(value)||value<0||!Number.isFinite(thickness)||thickness<=0)throw Error('Неверное расстояние или толщина');const walls=p.objects.filter(w=>ids.includes(w.id));if(walls.length!==ids.length||walls.some(w=>w.type!=='wall'))throw Error('Для параллельной цепочки выберите только стены');const links=new Map();for(const w of walls)for(const id of w.vertexIds){const list=links.get(id)??[];list.push(w);links.set(id,list)}if([...links.values()].some(list=>list.length>2))throw Error('Параллельная цепочка не может содержать разветвления');const endpoint=[...links.keys()].find(id=>links.get(id).length===1),closed=!endpoint,first=endpoint??walls[0].vertexIds[0],ordered=[],used=new Set();let node=first;while(used.size<walls.length){const wall=links.get(node)?.find(w=>!used.has(w.id));if(!wall)throw Error('Выберите одну связную цепочку');const reversed=wall.vertexIds[0]!==node,next=wall.vertexIds[reversed?0:1];ordered.push({wall,reversed,a:p.nodes[node],b:p.nodes[next]});used.add(wall.id);node=next;}const lines=ordered.map(item=>{const len=distance(item.a,item.b),offset=value+(mode==='clear'?((item.wall.thickness??.2)+thickness)/2:0);if(offset<=1e-6)throw Error('Расстояние между осями должно быть больше нуля');const delta={x:-(item.b.y-item.a.y)/len*offset*side,y:(item.b.x-item.a.x)/len*offset*side};return{...item,offset,start:{x:item.a.x+delta.x,y:item.a.y+delta.y},end:{x:item.b.x+delta.x,y:item.b.y+delta.y}}});const joins=[];
 for(let i=0;i<(closed?lines.length:lines.length-1);i++){const a=lines[i],b=lines[(i+1)%lines.length],dx=a.end.x-a.start.x,dy=a.end.y-a.start.y,ex=b.end.x-b.start.x,ey=b.end.y-b.start.y,den=dx*ey-dy*ex;if(Math.abs(den)<1e-10){if(distance(a.end,b.start)>1e-6)joins.push({a:{...a.end},b:{...b.start}});continue}const t=((b.start.x-a.start.x)*ey-(b.start.y-a.start.y)*ex)/den,join={x:a.start.x+t*dx,y:a.start.y+t*dy};if(distance(join,a.end)>4*Math.max(a.offset,b.offset)||distance(join,b.start)>4*Math.max(a.offset,b.offset))joins.push({a:{...a.end},b:{...b.start}});else{a.end=join;b.start=join;}}
 const nodes={...p.nodes},newObjects=[],newOpenings=[];const nodeFor=point=>{const existing=Object.values(nodes).find(n=>newObjects.some(w=>w.vertexIds.includes(n.id))&&distance(n,point)<1e-8);if(existing)return existing.id;const id=crypto.randomUUID();nodes[id]={...point,id};return id;};
 for(const line of lines){const a=nodeFor(line.start),b=distance(line.start,line.end)<1e-7?null:nodeFor(line.end);if(!b||(line.end.x-line.start.x)*(line.b.x-line.a.x)+(line.end.y-line.start.y)*(line.b.y-line.a.y)<=1e-8)throw Error('Смещение схлопывает или переворачивает сегмент; уменьшите расстояние');const id=crypto.randomUUID();newObjects.push({...line.wall,id,name:line.wall.name+' (параллельно)',vertexIds:line.reversed?[b,a]:[a,b],buildingId:undefined,thickness,locks:[]});if(withOpenings)for(const o of p.openings.filter(o=>o.wallId===line.wall.id))newOpenings.push({...o,id:crypto.randomUUID(),wallId:id,name:o.name+' (копия)'});}
 for(const join of joins){if(distance(join.a,join.b)<1e-7)continue;const a=nodeFor(join.a),b=nodeFor(join.b);newObjects.push({id:crypto.randomUUID(),type:'wall',name:'Срез стыка',vertexIds:[a,b],thickness,height:2.8,wallKind:'external'});}
 const next={...p,nodes,objects:[...p.objects,...newObjects],openings:[...p.openings,...newOpenings]};
 // Detect loops/crossings in the offset chain rather than applying an ambiguous result.
 for(let i=0;i<newObjects.length;i++)for(let j=i+1;j<newObjects.length;j++){const a=newObjects[i],b=newObjects[j];if(a.vertexIds.some(id=>b.vertexIds.includes(id)))continue;const A=nodes[a.vertexIds[0]],B=nodes[a.vertexIds[1]],C=nodes[b.vertexIds[0]],D=nodes[b.vertexIds[1]],dx=B.x-A.x,dy=B.y-A.y,ex=D.x-C.x,ey=D.y-C.y,den=dx*ey-dy*ex;if(Math.abs(den)<1e-10)continue;const t=((C.x-A.x)*ey-(C.y-A.y)*ex)/den,u=((C.x-A.x)*dy-(C.y-A.y)*dx)/den;if(t>1e-7&&t<1-1e-7&&u>1e-7&&u<1-1e-7)throw Error('Смещённая цепочка пересекает себя. Уменьшите расстояние или выберите другую сторону');}return next;
}
