import {wallCurve} from './curved-walls.mjs';
import {curveAreaContribution,curveLength,curvePath,curveBounds,lineCurveIntersections,curveIntersections,curvePoint,coincidentCurveOverlap} from './curve-math.mjs';
const near=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y)<1e-6;
export function contourEdges(p,o){return o.vertexIds.map((id,i)=>{const next=o.vertexIds[(i+1)%o.vertexIds.length],a=p.nodes[id],b=p.nodes[next];const walls=p.objects.filter(w=>w.type==='wall'&&w.curve?.kind==='arc'&&(o.boundaryWallIds?.includes(w.id)||o.type==='building'&&w.buildingId===o.id&&w.wallKind==='external')&&((w.vertexIds[0]===id&&w.vertexIds[1]===next)||(w.vertexIds[1]===id&&w.vertexIds[0]===next)));if(walls.length>1)throw Error('Несколько дуг относятся к одной стороне контура');const wall=walls[0];let curve=wall?wallCurve(p,wall):null;if(curve&&wall.vertexIds[0]!==id)curve={...curve,startAngle:curve.startAngle+curve.sweepAngle,sweepAngle:-curve.sweepAngle};return{a,b,curve,index:i,wallId:wall?.id,length:curve?curveLength(curve):Math.hypot(b.x-a.x,b.y-a.y)}})}
export const contourArea=(p,o)=>Math.abs(contourEdges(p,o).reduce((s,e)=>s+(e.curve?curveAreaContribution(e.curve):(e.a.x*e.b.y-e.b.x*e.a.y)/2),0));
export const contourPath=(p,o)=>{const edges=contourEdges(p,o);return `M ${edges[0].a.x} ${edges[0].a.y} `+edges.map(e=>e.curve?curvePath(e.curve).replace(/^M [^ ]+ [^ ]+ /,''):`L ${e.b.x} ${e.b.y}`).join(' ')+' Z'};
export function contourBounds(p,o){const points=contourEdges(p,o).flatMap(e=>{if(!e.curve)return[e.a,e.b];const b=curveBounds(e.curve);return[{x:b.minX,y:b.minY},{x:b.maxX,y:b.maxY}]});return{minX:Math.min(...points.map(v=>v.x)),maxX:Math.max(...points.map(v=>v.x)),minY:Math.min(...points.map(v=>v.y)),maxY:Math.max(...points.map(v=>v.y))}}
export function validateContour(p,o){const edges=contourEdges(p,o);if(contourArea(p,o)<1e-8)throw Error('Контур имеет нулевую площадь или самопересечение');for(let i=0;i<edges.length;i++)for(let j=i+1;j<edges.length;j++){const a=edges[i],b=edges[j];let hits=[];if(a.curve&&b.curve){if(near(a.curve.center,b.curve.center)&&Math.abs(a.curve.radius-b.curve.radius)<1e-7){if(coincidentCurveOverlap(a.curve,b.curve))throw Error('Совпадающие дуги контура');continue}hits=curveIntersections(a.curve,b.curve)}else if(a.curve||b.curve){const c=a.curve?a:b,l=a.curve?b:a;hits=lineCurveIntersections(l.a,l.b,c.curve)}else{const dx=a.b.x-a.a.x,dy=a.b.y-a.a.y,ex=b.b.x-b.a.x,ey=b.b.y-b.a.y,d=dx*ey-dy*ex;if(Math.abs(d)<=1e-10&&Math.abs((b.a.x-a.a.x)*dy-(b.a.y-a.a.y)*dx)<1e-7){const axis=Math.abs(dx)>Math.abs(dy)?'x':'y';if(Math.min(Math.max(a.a[axis],a.b[axis]),Math.max(b.a[axis],b.b[axis]))-Math.max(Math.min(a.a[axis],a.b[axis]),Math.min(b.a[axis],b.b[axis]))>1e-7)throw Error('Контур имеет перекрывающиеся стороны')}if(Math.abs(d)>1e-10){const t=((b.a.x-a.a.x)*ey-(b.a.y-a.a.y)*ex)/d,u=((b.a.x-a.a.x)*dy-(b.a.y-a.a.y)*dx)/d;if(t>=0&&t<=1&&u>=0&&u<=1)hits=[{x:a.a.x+t*dx,y:a.a.y+t*dy}]}}
 for(const point of hits)if(!([a.a,a.b].some(v=>near(v,point))&&[b.a,b.b].some(v=>near(v,point))&&(j===i+1||i===0&&j===edges.length-1)))throw Error('Контур с дугами пересекает сам себя');}}
