import {defaultLayers,withLayers,validateLayers} from './layers.mjs';
import {inspectData} from './validation-data.mjs';
import {isRoute} from './engineering-catalog.mjs';
import {validateEngineering,resolveEngineering,pathOutline} from './engineering-math.mjs';
/** @returns {import('./types').Project} */
export const freshProject = () => ({id:crypto.randomUUID(),name:'Мой участок',schemaVersion:2,revision:0,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),settings:{unit:'m',grid:1,snap:0.1},layers:defaultLayers(),nodes:{},objects:[],openings:[]});
export const area = vs => Math.abs(vs.reduce((s,a,i)=>{const b=vs[(i+1)%vs.length];return s+a.x*b.y-b.x*a.y},0))/2;
export const worldToScreen = (p,c) => ({x:p.x*c.scale+c.x,y:p.y*c.scale+c.y});
export const screenToWorld = (p,c) => ({x:(p.x-c.x)/c.scale,y:(p.y-c.y)/c.scale});
export function zoomAt(c,p,f){const w=screenToWorld(p,c),scale=Math.max(3,Math.min(400,c.scale*f));return {scale,x:p.x-w.x*scale,y:p.y-w.y*scale};}
export function pushHistory(h,next){return {past:[...h.past.slice(-99),h.present],present:next,future:[]};}
export function undo(h){return h.past.length?{past:h.past.slice(0,-1),present:h.past.at(-1),future:[h.present,...h.future]}:h;}
export function redo(h){return h.future.length?{past:[...h.past,h.present],present:h.future[0],future:h.future.slice(1)}:h;}
/** Convert stage-one files without changing their geometry or revision. */
export function migrateProject(p){if(p?.schemaVersion!==1)return p?.schemaVersion===2?{...p,openings:p.openings??[]}:p;if(!Array.isArray(p.objects))throw Error('Некорректный проект');const nodes={};const objects=p.objects.map(o=>{if(o.type!=='outline'||!Array.isArray(o.vertices))throw Error('Некорректная геометрия старого проекта');const vertexIds=o.vertices.map(v=>{const id=crypto.randomUUID();nodes[id]={...v,id};return id});const {vertices,...rest}=o;return{...rest,vertexIds,shape:'polygon'}});return{...p,schemaVersion:2,nodes,objects,openings:[]};}
export function validateProject(input){
 inspectData(input);
 let p=migrateProject(input);
 if(!p || p.schemaVersion!==2 || typeof p.id!=='string' || !/^[a-zA-Z0-9-]{1,80}$/.test(p.id) || typeof p.name!=='string' || p.name.length>200 || !Number.isSafeInteger(p.revision) || p.revision<0 || !Array.isArray(p.objects) || p.objects.length>10000)throw Error('Некорректный проект');
 if(!p.settings||!['m','cm','mm'].includes(p.settings.unit)||!Number.isFinite(p.settings.grid)||p.settings.grid<=0||p.settings.grid>1e6||!Number.isFinite(p.settings.snap)||p.settings.snap<=0||p.settings.snap>1e6)throw Error('Некорректные настройки');
 if(typeof p.createdAt!=='string'||!Number.isFinite(Date.parse(p.createdAt))||typeof p.updatedAt!=='string'||!Number.isFinite(Date.parse(p.updatedAt)))throw Error('Некорректные даты проекта');
 if(!p.nodes||typeof p.nodes!=='object'||Array.isArray(p.nodes)||Object.keys(p.nodes).length>50000)throw Error('Некорректные узлы');
 for(const [id,n] of Object.entries(p.nodes)){if(!/^[a-zA-Z0-9-]{1,80}$/.test(id)||!n||n.id!==id||!Number.isFinite(n.x)||!Number.isFinite(n.y)||Math.abs(n.x)>1e6||Math.abs(n.y)>1e6)throw Error('Некорректные координаты узла');}
 p=withLayers(p);validateLayers(p);
 const ids=new Set(Object.keys(p.nodes)),attachmentIds=new Map();
 for(const o of p.objects){if(!o||typeof o.id!=='string'||!/^[a-zA-Z0-9-]{1,80}$/.test(o.id)||ids.has(o.id)||!['outline','plot','building','wall','fixture','pipe','wire','path'].includes(o.type)||typeof o.name!=='string'||o.name.length>200||!Array.isArray(o.vertexIds)||o.vertexIds.length>(o.type==='wall'?2:o.type==='fixture'?1:1000)||o.vertexIds.length<(o.type==='fixture'?1:o.type==='wall'||isRoute(o)?2:3)||new Set(o.vertexIds).size!==o.vertexIds.length||o.vertexIds.some(id=>!Object.hasOwn(p.nodes,id)))throw Error('Некорректная геометрия');ids.add(o.id);if(o.thickness!==undefined&&(!Number.isFinite(o.thickness)||o.thickness<=0||o.thickness>5))throw Error('Толщина должна быть от 0 до 5 м');if(o.height!==undefined&&(!Number.isFinite(o.height)||o.height<=0||o.height>1000))throw Error('Некорректная высота');if(o.type==='wall'&&distance(p.nodes[o.vertexIds[0]],p.nodes[o.vertexIds[1]])<1e-6)throw Error('Стена не может иметь нулевую длину');if(!['wall','fixture'].includes(o.type)&&!isRoute(o)&&(area(o.vertexIds.map(id=>p.nodes[id]))<1e-8||selfIntersects(o.vertexIds.map(id=>p.nodes[id]))))throw Error('Контур имеет нулевую площадь или самопересечение');
 if(['fixture','pipe','wire','path'].includes(o.type))validateEngineering(p,o,attachmentIds);
 if(o.shape==='rectangle'){const vs=o.vertexIds.map(id=>p.nodes[id]);if(vs.length!==4)throw Error('Прямоугольник должен иметь четыре вершины');for(let i=0;i<4;i++){const a=vs[i],b=vs[(i+1)%4],c=vs[(i+2)%4];if(Math.abs((b.x-a.x)*(c.x-b.x)+(b.y-a.y)*(c.y-b.y))>1e-6)throw Error('Нарушена прямоугольность');}}
 if(o.locks!==undefined){if(!Array.isArray(o.locks)||o.locks.length>1000)throw Error('Некорректные ограничения');for(const l of o.locks){const i=o.vertexIds.indexOf(l.startId);if(i<0||o.vertexIds[(i+1)%o.vertexIds.length]!==l.endId||l.length!==undefined&&(!Number.isFinite(l.length)||l.length<=0)||l.angle!==undefined&&!Number.isFinite(l.angle))throw Error('Некорректная опора ограничения');if(l.length!==undefined&&Math.abs(distance(p.nodes[l.startId],p.nodes[l.endId])-l.length)>1e-5)throw Error('Конфликт заблокированной длины');if(l.angle!==undefined&&Math.abs(angleDelta(angle(p.nodes[l.startId],p.nodes[l.endId]),l.angle))>1e-5)throw Error('Конфликт заблокированного направления');}}
 }
 for(const o of p.objects)if(o.buildingId){const b=p.objects.find(b=>b.id===o.buildingId&&b.type==='building');if(!b)throw Error('Не найдена постройка стены');if(o.wallKind==='external'&&!b.vertexIds.some((id,i)=>id===o.vertexIds[0]&&b.vertexIds[(i+1)%b.vertexIds.length]===o.vertexIds[1]||id===o.vertexIds[1]&&b.vertexIds[(i+1)%b.vertexIds.length]===o.vertexIds[0]))throw Error('Внешняя стена постройки должна использовать узлы её контура');}
 if(!Array.isArray(p.openings)||p.openings.length>10000)throw Error('Некорректные проёмы');
 for(const o of p.openings){if(!o||typeof o.id!=='string'||!/^[a-zA-Z0-9-]{1,80}$/.test(o.id)||ids.has(o.id)||!['door','window'].includes(o.type)||typeof o.name!=='string'||o.name.length>200||!['start','end'].includes(o.anchor)||!['start','end'].includes(o.hinge)||![1,-1].includes(o.side)||!['single','double','sliding','standard','panoramic'].includes(o.kind)||!Number.isFinite(o.width)||o.width<=1e-6||!Number.isFinite(o.offset)||o.offset<0||!Number.isFinite(o.height)||o.height<=0||o.sill!==undefined&&(!Number.isFinite(o.sill)||o.sill<0))throw Error('Некорректный проём');ids.add(o.id);const wall=p.objects.find(w=>w.id===o.wallId&&w.type==='wall');if(!wall)throw Error('Не найдена стена проёма');const length=distance(p.nodes[wall.vertexIds[0]],p.nodes[wall.vertexIds[1]]);if(o.offset+o.width>length+1e-7)throw Error(`Стена «${wall.name}» слишком короткая для «${o.name}»: нужны ${(o.offset+o.width).toFixed(3)} м. Увеличьте стену, измените отступ или перенесите проём`);}
 for(let i=0;i<p.openings.length;i++)for(let j=i+1;j<p.openings.length;j++){const a=p.openings[i],b=p.openings[j];if(a.wallId!==b.wallId)continue;const wall=p.objects.find(w=>w.id===a.wallId),len=distance(p.nodes[wall.vertexIds[0]],p.nodes[wall.vertexIds[1]]),start=o=>o.anchor==='end'?len-o.offset-o.width:o.offset;if(Math.min(start(a)+a.width,start(b)+b.width)-Math.max(start(a),start(b))>1e-7)throw Error('Проёмы одной стены пересекаются: измените ширину или отступ');}
 const walls=p.objects.filter(o=>o.type==='wall');for(let i=0;i<walls.length;i++)for(let j=i+1;j<walls.length;j++)if(overlapping(p.nodes[walls[i].vertexIds[0]],p.nodes[walls[i].vertexIds[1]],p.nodes[walls[j].vertexIds[0]],p.nodes[walls[j].vertexIds[1]]))throw Error('Стены накладываются друг на друга');
 for(const o of p.objects.filter(o=>['pipe','wire'].includes(o.type)))for(const id of o.vertexIds){if(p.objects.some(n=>n.id!==o.id&&n.vertexIds.includes(id)&&(!['pipe','wire'].includes(n.type)||n.type!==o.type||n.kind!==o.kind)))throw Error('Узел трассы должен соединять линии одного типа и назначения')}
 p=resolveEngineering(p);
 for(const n of Object.values(p.nodes))if(!Number.isFinite(n.x)||!Number.isFinite(n.y)||Math.abs(n.x)>1e6||Math.abs(n.y)>1e6)throw Error('Подключение задаёт некорректные координаты');
 for(const o of p.objects)for(const l of o.locks??[]){if(l.length!==undefined&&Math.abs(distance(p.nodes[l.startId],p.nodes[l.endId])-l.length)>1e-5)throw Error('Подключение нарушает заблокированную длину трассы');if(l.angle!==undefined&&Math.abs(angleDelta(angle(p.nodes[l.startId],p.nodes[l.endId]),l.angle))>1e-5)throw Error('Подключение нарушает заблокированное направление трассы')}
 for(const o of p.objects){if(isRoute(o))validateEngineering(p,o,new Map());if(o.type==='path'){const outline=pathOutline(p,o);if(area(outline)<1e-8||selfIntersects(outline))throw Error('Границы дорожки пересекаются или схлопываются: уменьшите ширину либо измените узлы')}}
 return p;
}
export const distance=(a,b)=>Math.hypot(b.x-a.x,b.y-a.y);
export const angle=(a,b)=>Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI;
export const angleDelta=(a,b)=>((a-b+540)%360+360)%360-180;
const cross=(a,b,c)=>(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);
const onSegment=(a,b,p)=>Math.abs(cross(a,b,p))<1e-8&&p.x>=Math.min(a.x,b.x)-1e-8&&p.x<=Math.max(a.x,b.x)+1e-8&&p.y>=Math.min(a.y,b.y)-1e-8&&p.y<=Math.max(a.y,b.y)+1e-8;
export function selfIntersects(vs){for(let i=0;i<vs.length;i++){const a=vs[i],b=vs[(i+1)%vs.length],previous=vs[(i+vs.length-1)%vs.length];if(distance(a,b)<1e-6||Math.abs(cross(previous,a,b))<1e-8&&(a.x-previous.x)*(b.x-a.x)+(a.y-previous.y)*(b.y-a.y)<-1e-8)return true;for(let j=i+1;j<vs.length;j++){if(j===i+1||i===0&&j===vs.length-1)continue;const c=vs[j],d=vs[(j+1)%vs.length];if(cross(a,b,c)*cross(a,b,d)<0&&cross(c,d,a)*cross(c,d,b)<0||onSegment(a,b,c)||onSegment(a,b,d)||onSegment(c,d,a)||onSegment(c,d,b))return true;}}return false;}
export function overlapping(a,b,c,d){if(Math.abs(cross(a,b,c))>1e-8||Math.abs(cross(a,b,d))>1e-8)return false;const len=distance(a,b),project=p=>((p.x-a.x)*(b.x-a.x)+(p.y-a.y)*(b.y-a.y))/len;return Math.min(len,Math.max(project(c),project(d)))-Math.max(0,Math.min(project(c),project(d)))>1e-6;}
