import {validateOutputSettings} from './print-layout.mjs';
import {validateFloors,synchronizeFloors} from './floors.mjs';
import {validateWorkspace,synchronizeWorkspace} from './workspace.mjs';
import {validateSite} from './site.mjs';
import {validateFurniture} from './furniture-data.mjs';
import {validateRooms,reconcileRooms} from './rooms.mjs';
import {validateUnderlays} from './underlays.mjs';
import {validateDrawing,resolveDrawings} from './drawings.mjs';
import {validateStyle} from './appearance.mjs';
import {coincidentCurveOverlap} from './curve-math.mjs';
import {wallCurve} from './curved-walls.mjs';
import {validateContour} from './contour-math.mjs';
import {jointAngle} from './wall-editing.mjs';
import {validateCurvedWall,wallLength,curveOpeningIntervals} from './curved-walls.mjs';
import {defaultLayers,withLayers,validateLayers} from './layers.mjs';
import {inspectData} from './validation-data.mjs';
import {isRoute} from './engineering-catalog.mjs';
import {validateEngineering,resolveEngineering,pathOutline} from './engineering-math.mjs';
import {migrateProject} from './project-migrations.mjs';
export {migrateProject} from './project-migrations.mjs';
/** @returns {import('./types').Project} */
export const freshProject = () => ({id:crypto.randomUUID(),name:'Мой участок',schemaVersion:2,revision:0,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),settings:{unit:'m',grid:1,snap:0.1},layers:defaultLayers(),nodes:{},objects:[],openings:[]});
export const area = vs => Math.abs(vs.reduce((s,a,i)=>{const b=vs[(i+1)%vs.length];return s+a.x*b.y-b.x*a.y},0))/2;
export const worldToScreen = (p,c) => {const a=(c.rotation??0)*Math.PI/180;return{x:(p.x*Math.cos(a)-p.y*Math.sin(a))*c.scale+c.x,y:(p.x*Math.sin(a)+p.y*Math.cos(a))*c.scale+c.y}};
export const screenToWorld = (p,c) => {const a=-(c.rotation??0)*Math.PI/180,x=(p.x-c.x)/c.scale,y=(p.y-c.y)/c.scale;return{x:x*Math.cos(a)-y*Math.sin(a),y:x*Math.sin(a)+y*Math.cos(a)}};
export function zoomAt(c,p,f){const w=screenToWorld(p,c),scale=Math.max(3,Math.min(400,c.scale*f));const projected=worldToScreen(w,{...c,x:0,y:0,scale});return {...c,scale,x:p.x-projected.x,y:p.y-projected.y};}
export function pushHistory(h,next){return {past:[...h.past.slice(-99),h.present],present:next,future:[]};}
export function undo(h){return h.past.length?{past:h.past.slice(0,-1),present:h.past.at(-1),future:[h.present,...h.future]}:h;}
export function redo(h){return h.future.length?{past:[...h.past,h.present],present:h.future[0],future:h.future.slice(1)}:h;}
/** Convert stage-one files without changing their geometry or revision. */
export function validateProject(input){
 inspectData(input);
 let p=migrateProject(input);
 if(!p || ![2,3,4,5,6,7,8,9,10].includes(p.schemaVersion) || typeof p.id!=='string' || !/^[a-zA-Z0-9-]{1,80}$/.test(p.id) || typeof p.name!=='string' || p.name.length>200 || !Number.isSafeInteger(p.revision) || p.revision<0 || !Array.isArray(p.objects) || p.objects.length>10000)throw Error('Некорректный проект');
 if(!p.settings||!['m','cm','mm'].includes(p.settings.unit)||!Number.isFinite(p.settings.grid)||p.settings.grid<=0||p.settings.grid>1e6||!Number.isFinite(p.settings.snap)||p.settings.snap<=0||p.settings.snap>1e6)throw Error('Некорректные настройки');
 validateOutputSettings(p.settings);
 if(p.settings.recentColors!==undefined&&(!Array.isArray(p.settings.recentColors)||p.settings.recentColors.length>12||p.settings.recentColors.some(c=>typeof c!=='string'||!/^#[a-fA-F0-9]{6}$/.test(c))))throw Error('Некорректная палитра');
 if(p.settings.savedViews!==undefined){if(p.schemaVersion<3||!Array.isArray(p.settings.savedViews)||p.settings.savedViews.length>100)throw Error('Некорректные сохранённые виды');const seen=new Set();for(const v of p.settings.savedViews){if(!v||typeof v.id!=='string'||seen.has(v.id)||typeof v.name!=='string'||v.name.length>80||!v.camera||![v.camera.x,v.camera.y,v.camera.scale,v.camera.rotation??0].every(Number.isFinite)||v.camera.scale<3||v.camera.scale>400)throw Error('Некорректный сохранённый вид');seen.add(v.id)}}
 if(typeof p.createdAt!=='string'||!Number.isFinite(Date.parse(p.createdAt))||typeof p.updatedAt!=='string'||!Number.isFinite(Date.parse(p.updatedAt)))throw Error('Некорректные даты проекта');
 if(!p.nodes||typeof p.nodes!=='object'||Array.isArray(p.nodes)||Object.keys(p.nodes).length>50000)throw Error('Некорректные узлы');
 for(const [id,n] of Object.entries(p.nodes)){if(!/^[a-zA-Z0-9-]{1,80}$/.test(id)||!n||n.id!==id||!Number.isFinite(n.x)||!Number.isFinite(n.y)||Math.abs(n.x)>1e6||Math.abs(n.y)>1e6)throw Error('Некорректные координаты узла');if(n.name!==undefined&&(typeof n.name!=='string'||n.name.length>200))throw Error('Некорректное имя узла');}
 p=withLayers(p);validateLayers(p);validateUnderlays(p);const curved=p.objects.filter(o=>o.curve&&o.type==='wall');for(let i=0;i<curved.length;i++)for(let j=i+1;j<curved.length;j++)if(coincidentCurveOverlap(wallCurve(p,curved[i]),wallCurve(p,curved[j])))throw Error('Совпадающие кривые стены');
 const ids=new Set(Object.keys(p.nodes)),attachmentIds=new Map();
 for(const o of p.objects){if(!o||typeof o.id!=='string'||!/^[a-zA-Z0-9-]{1,80}$/.test(o.id)||ids.has(o.id)||!['annotation','guide','outline','plot','building','wall','fixture','pipe','wire','path'].includes(o.type)||typeof o.name!=='string'||o.name.length>200||!Array.isArray(o.vertexIds)||o.vertexIds.length>(o.type==='wall'?(o.curve?.kind==='circle'?1:o.curve?3:2):o.type==='fixture'?1:1000)||o.vertexIds.length<(o.type==='fixture'||o.drawingKind==='text'||o.curve?.kind==='circle'?1:o.type==='wall'||o.type==='annotation'||o.type==='guide'||isRoute(o)?2:3)||new Set(o.vertexIds).size!==o.vertexIds.length||o.vertexIds.some(id=>!Object.hasOwn(p.nodes,id)))throw Error('Некорректная геометрия');ids.add(o.id);validateStyle(o.style);if(o.labelVisible!==undefined&&typeof o.labelVisible!=='boolean')throw Error('Некорректная видимость подписи');if(['annotation','guide'].includes(o.type))validateDrawing(p,o);if(o.thickness!==undefined&&(!Number.isFinite(o.thickness)||o.thickness<=0||o.thickness>5))throw Error('Толщина должна быть от 0 до 5 м');if(o.height!==undefined&&(!Number.isFinite(o.height)||o.height<=0||o.height>1000))throw Error('Некорректная высота');validateCurvedWall(p,o);if(o.type==='wall'&&!o.curve&&distance(p.nodes[o.vertexIds[0]],p.nodes[o.vertexIds[1]])<1e-6)throw Error('Стена не может иметь нулевую длину');if(!['wall','fixture','annotation','guide'].includes(o.type)&&!isRoute(o)){if(!o.boundaryWallIds?.length&&!p.objects.some(w=>w.curve&&w.buildingId===o.id)&&selfIntersects(o.vertexIds.map(id=>p.nodes[id])))throw Error('Контур имеет самопересечение');validateContour(p,o);}if(o.boundaryWallIds!==undefined){if(p.schemaVersion<3||!['outline','plot','building'].includes(o.type)||!Array.isArray(o.boundaryWallIds)||o.boundaryWallIds.length>1000||new Set(o.boundaryWallIds).size!==o.boundaryWallIds.length)throw Error('Некорректные дуги контура');for(const id of o.boundaryWallIds){const w=p.objects.find(w=>w.id===id&&w.type==='wall');if(!w||w.curve?.kind!=='arc'||!o.vertexIds.some((a,i)=>{const b=o.vertexIds[(i+1)%o.vertexIds.length];return a===w.vertexIds[0]&&b===w.vertexIds[1]||a===w.vertexIds[1]&&b===w.vertexIds[0]}))throw Error('Дуга не связана с соседними узлами контура')}}
 if(['fixture','pipe','wire','path'].includes(o.type))validateEngineering(p,o,attachmentIds);
 if(o.shape==='rectangle'){const vs=o.vertexIds.map(id=>p.nodes[id]);if(vs.length!==4)throw Error('Прямоугольник должен иметь четыре вершины');for(let i=0;i<4;i++){const a=vs[i],b=vs[(i+1)%4],c=vs[(i+2)%4];if(Math.abs((b.x-a.x)*(c.x-b.x)+(b.y-a.y)*(c.y-b.y))>1e-6)throw Error('Нарушена прямоугольность');}}
 if(o.locks!==undefined){if(!Array.isArray(o.locks)||o.locks.length>1000)throw Error('Некорректные ограничения');for(const l of o.locks){const i=o.vertexIds.indexOf(l.startId);if(i<0||o.vertexIds[(i+1)%o.vertexIds.length]!==l.endId||l.length!==undefined&&(!Number.isFinite(l.length)||l.length<=0)||l.angle!==undefined&&!Number.isFinite(l.angle))throw Error('Некорректная опора ограничения');if(l.length!==undefined&&Math.abs(distance(p.nodes[l.startId],p.nodes[l.endId])-l.length)>1e-5)throw Error('Конфликт заблокированной длины');if(l.angle!==undefined&&Math.abs(angleDelta(angle(p.nodes[l.startId],p.nodes[l.endId]),l.angle))>1e-5)throw Error('Конфликт заблокированного направления');}}
 }
 for(const o of p.objects)if(o.wallMount&&p.objects.find(w=>w.id===o.wallMount.wallId)?.curve)throw Error('Закрепление прибора на кривой стене пока не поддерживается');
 for(const o of p.objects)if(o.buildingId){const b=p.objects.find(b=>b.id===o.buildingId&&b.type==='building');if(!b)throw Error('Не найдена постройка стены');if(o.wallKind==='external'&&!b.vertexIds.some((id,i)=>id===o.vertexIds[0]&&b.vertexIds[(i+1)%b.vertexIds.length]===o.vertexIds[1]||id===o.vertexIds[1]&&b.vertexIds[(i+1)%b.vertexIds.length]===o.vertexIds[0]))throw Error('Внешняя стена постройки должна использовать узлы её контура');}
 if(!Array.isArray(p.openings)||p.openings.length>10000)throw Error('Некорректные проёмы');
 for(const o of p.openings){if(!o||typeof o.id!=='string'||!/^[a-zA-Z0-9-]{1,80}$/.test(o.id)||ids.has(o.id)||!['door','window'].includes(o.type)||typeof o.name!=='string'||o.name.length>200||!['start','end'].includes(o.anchor)||!['start','end'].includes(o.hinge)||![1,-1].includes(o.side)||!['single','double','sliding','standard','panoramic','curved'].includes(o.kind)||!Number.isFinite(o.width)||o.width<=1e-6||!Number.isFinite(o.offset)||o.offset<0||!Number.isFinite(o.height)||o.height<=0||o.sill!==undefined&&(!Number.isFinite(o.sill)||o.sill<0))throw Error('Некорректный проём');validateStyle(o.style);if(o.labelVisible!==undefined&&typeof o.labelVisible!=='boolean')throw Error('Некорректная подпись');ids.add(o.id);const wall=p.objects.find(w=>w.id===o.wallId&&w.type==='wall');if(!wall)throw Error('Не найдена стена проёма');const length=wallLength(p,wall);if(wall.curve&&(o.type!=='window'||o.kind!=='curved'))throw Error('На кривой стене поддерживается только изогнутое окно; плоская дверь требует прямого участка');if(!wall.curve&&o.kind==='curved')throw Error('Изогнутое окно требует кривую стену');if(wall.curve?.kind==='circle'?(o.offset>=length||o.width>=length):o.offset+o.width>length+1e-7)throw Error(`Стена «${wall.name}» слишком короткая для «${o.name}»: нужны ${(o.offset+o.width).toFixed(3)} м. Увеличьте стену, измените отступ или перенесите проём`);}
 for(let i=0;i<p.openings.length;i++)for(let j=i+1;j<p.openings.length;j++){const a=p.openings[i],b=p.openings[j];if(a.wallId!==b.wallId)continue;const wall=p.objects.find(w=>w.id===a.wallId),len=wallLength(p,wall),start=o=>o.anchor==='end'?len-o.offset-o.width:o.offset;if(Math.min(start(a)+a.width,start(b)+b.width)-Math.max(start(a),start(b))>1e-7)throw Error('Проёмы одной стены пересекаются: измените ширину или отступ');}
 for(const wall of p.objects.filter(o=>o.curve)){const cuts=curveOpeningIntervals(p,wall);for(let i=1;i<cuts.length;i++)if(cuts[i][0]<cuts[i-1][1]-1e-7)throw Error('Проёмы пересекаются через начальную метку окружности')}
 const walls=p.objects.filter(o=>o.type==='wall'&&!o.curve);for(let i=0;i<walls.length;i++)for(let j=i+1;j<walls.length;j++)if(overlapping(p.nodes[walls[i].vertexIds[0]],p.nodes[walls[i].vertexIds[1]],p.nodes[walls[j].vertexIds[0]],p.nodes[walls[j].vertexIds[1]]))throw Error('Стены накладываются друг на друга');
 for(const o of p.objects.filter(o=>['pipe','wire'].includes(o.type)))for(const id of o.vertexIds){if(p.objects.some(n=>n.id!==o.id&&n.vertexIds.includes(id)&&(!['pipe','wire'].includes(n.type)||n.type!==o.type||n.kind!==o.kind)))throw Error('Узел трассы должен соединять линии одного типа и назначения')}
 if(p.jointConstraints!==undefined){if(p.schemaVersion<3||!Array.isArray(p.jointConstraints)||p.jointConstraints.length>1000)throw Error('Некорректные ограничения стыков');for(const constraint of p.jointConstraints){if(!constraint||typeof constraint.id!=='string'||ids.has(constraint.id)||!Array.isArray(constraint.wallIds)||constraint.wallIds.length!==2||!constraint.wallIds.includes(constraint.changedWallId)||!Number.isFinite(constraint.angle)||constraint.angle<=0||constraint.angle>=180)throw Error('Некорректное ограничение угла стыка');ids.add(constraint.id);const joint=jointAngle(p,constraint.wallIds);if(joint.nodeId!==constraint.nodeId||Math.abs(joint.angle-constraint.angle)>1e-5)throw Error('Конфликт зафиксированного угла стыка')}}
 p=resolveDrawings(resolveEngineering(p));
 for(const n of Object.values(p.nodes))if(!Number.isFinite(n.x)||!Number.isFinite(n.y)||Math.abs(n.x)>1e6||Math.abs(n.y)>1e6)throw Error('Подключение задаёт некорректные координаты');
 for(const o of p.objects)for(const l of o.locks??[]){if(l.length!==undefined&&Math.abs(distance(p.nodes[l.startId],p.nodes[l.endId])-l.length)>1e-5)throw Error('Подключение нарушает заблокированную длину трассы');if(l.angle!==undefined&&Math.abs(angleDelta(angle(p.nodes[l.startId],p.nodes[l.endId]),l.angle))>1e-5)throw Error('Подключение нарушает заблокированное направление трассы')}
 for(const o of p.objects){if(isRoute(o))validateEngineering(p,o,new Map());if(o.type==='path'){const outline=pathOutline(p,o);if(area(outline)<1e-8||selfIntersects(outline))throw Error('Границы дорожки пересекаются или схлопываются: уменьшите ширину либо измените узлы')}}
 if(p.jointConstraints)for(const c of p.jointConstraints)if(Math.abs(jointAngle(p,c.wallIds).angle-c.angle)>1e-5)throw Error('Подключение нарушает угол стыка');
 validateFurniture(p);validateSite(p);
 if(p.schemaVersion>=7)for(const t of p.library)if(t.type==='set')validateProject(t.document);
 validateRooms(p);
 p=reconcileRooms(p);p=synchronizeFloors(p);validateFloors(p);p=validateWorkspace(p)??p;return synchronizeWorkspace(p);
}
export const distance=(a,b)=>Math.hypot(b.x-a.x,b.y-a.y);
export const angle=(a,b)=>Math.atan2(b.y-a.y,b.x-a.x)*180/Math.PI;
export const angleDelta=(a,b)=>((a-b+540)%360+360)%360-180;
const cross=(a,b,c)=>(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);
const onSegment=(a,b,p)=>Math.abs(cross(a,b,p))<1e-8&&p.x>=Math.min(a.x,b.x)-1e-8&&p.x<=Math.max(a.x,b.x)+1e-8&&p.y>=Math.min(a.y,b.y)-1e-8&&p.y<=Math.max(a.y,b.y)+1e-8;
export function selfIntersects(vs){for(let i=0;i<vs.length;i++){const a=vs[i],b=vs[(i+1)%vs.length],previous=vs[(i+vs.length-1)%vs.length];if(distance(a,b)<1e-6||Math.abs(cross(previous,a,b))<1e-8&&(a.x-previous.x)*(b.x-a.x)+(a.y-previous.y)*(b.y-a.y)<-1e-8)return true;for(let j=i+1;j<vs.length;j++){if(j===i+1||i===0&&j===vs.length-1)continue;const c=vs[j],d=vs[(j+1)%vs.length];if(cross(a,b,c)*cross(a,b,d)<0&&cross(c,d,a)*cross(c,d,b)<0||onSegment(a,b,c)||onSegment(a,b,d)||onSegment(c,d,a)||onSegment(c,d,b))return true;}}return false;}
export function overlapping(a,b,c,d){if(Math.abs(cross(a,b,c))>1e-8||Math.abs(cross(a,b,d))>1e-8)return false;const len=distance(a,b),project=p=>((p.x-a.x)*(b.x-a.x)+(p.y-a.y)*(b.y-a.y))/len;return Math.min(len,Math.max(project(c),project(d)))-Math.max(0,Math.min(project(c),project(d)))>1e-6;}
