import {checkCurve,curvePoint,curveLength,curveChord,curveFromChord,curveFromThreePoints,curveFromRadius,splitCurve,filletGeometry,chamferGeometry,curvePath} from './curve-math.mjs';
export const wallCurve=(p,w)=>w.curve?{...w.curve,center:p.nodes[w.curve.centerId]}:null;
export const wallLength=(p,w)=>w.curve?curveLength(wallCurve(p,w)):Math.hypot(p.nodes[w.vertexIds[1]].x-p.nodes[w.vertexIds[0]].x,p.nodes[w.vertexIds[1]].y-p.nodes[w.vertexIds[0]].y);
export function validateCurvedWall(p,w){
 if(!w.curve)return;
 if(p.schemaVersion<3||!['wall','annotation'].includes(w.type)||!p.nodes[w.curve.centerId]||w.curve.center!==undefined)throw Error('Кривая требует схему v3 и общий узел центра');
 const c=checkCurve(wallCurve(p,w),w.type==='annotation'?0:w.thickness??.2),count=c.kind==='circle'?1:3;
 if(w.vertexIds.length!==count||w.vertexIds.at(-1)!==c.centerId)throw Error('Некорректные узлы кривой стены');
 if(w.locks?.length)throw Error('Линейные ограничения несовместимы с кривой стеной');
 if(c.kind==='arc')for(let i=0;i<2;i++){const actual=p.nodes[w.vertexIds[i]],expected=curvePoint(c,i);if(Math.hypot(actual.x-expected.x,actual.y-expected.y)>1e-6)throw Error('Концы дуги не согласованы с радиусом и углами')}

}
export function setWallCurve(p,id,curve){
 const w=p.objects.find(w=>w.id===id&&['wall','annotation'].includes(w.type));if(!w)throw Error('Стена не найдена');
 if(w.locks?.length)throw Error('Снимите ограничения перед изменением типа стены');
 if(p.openings.some(o=>o.wallId===id&&o.kind!=='curved'))throw Error('Обычные окна и двери не изгибаются: сначала перенесите проёмы');
 if(p.objects.some(o=>o.wallMount?.wallId===id))throw Error('Сначала отсоедините закреплённые приборы от стены');
 checkCurve(curve,w.type==='annotation'?0:w.thickness??.2);
 const centerId=w.curve?.centerId??crypto.randomUUID(),nodes={...p.nodes,[centerId]:{id:centerId,x:curve.center.x,y:curve.center.y}};
 const vertexIds=curve.kind==='circle'?[centerId]:[w.curve?.kind==='circle'?crypto.randomUUID():w.vertexIds[0],w.curve?.kind==='circle'?crypto.randomUUID():w.vertexIds[1],centerId];
 if(curve.kind==='arc')vertexIds.slice(0,2).forEach((nodeId,i)=>nodes[nodeId]={id:nodeId,...curvePoint(curve,i)});
 const {center,...parameters}=curve;
 return {...p,schemaVersion:Math.max(p.schemaVersion,3),nodes,objects:p.objects.map(o=>o.id===id?{...o,vertexIds,curve:{...parameters,centerId}}:o.id===w.buildingId&&w.wallKind==='external'?{...o,shape:'polygon'}:o)};
}
export function addCurvedWall(p,curve,thickness=.2,name='Дуговая стена'){
 const id=crypto.randomUUID(),a=crypto.randomUUID(),b=crypto.randomUUID();
 const base={...p,nodes:{...p.nodes,[a]:{id:a,x:0,y:0},[b]:{id:b,x:1,y:0}},objects:[...p.objects,{id,type:'wall',name,wallKind:'internal',thickness,height:2.8,vertexIds:[a,b]}]};
 return{project:setWallCurve(base,id,curve),id};
}
export function convertWallToArc(p,id,sweep=90){const w=p.objects.find(w=>w.id===id);if(!w||w.curve)throw Error('Выберите прямую стену');return setWallCurve(p,id,curveFromChord(p.nodes[w.vertexIds[0]],p.nodes[w.vertexIds[1]],sweep))}
export function convertWallToLine(p,id){const w=p.objects.find(w=>w.id===id);if(!w?.curve||w.curve.kind==='circle')throw Error('Окружность нельзя превратить в нулевой отрезок');if(p.openings.some(o=>o.wallId===id))throw Error('Сначала перенесите изогнутые окна');const {curve,...rest}=w;return {...p,objects:p.objects.map(o=>o.id===id?{...rest,vertexIds:w.vertexIds.slice(0,2)}:o)}}
export function editWallCurve(p,id,patch,fixedEnds=false,side=1,major=false){const w=p.objects.find(w=>w.id===id),c=wallCurve(p,w);if(!c)throw Error('Выберите кривую стену');let curve={...c,...patch};if(fixedEnds){if(patch.center!==undefined||patch.startAngle!==undefined)throw Error('При фиксированных концах меняйте радиус или охват; для переноса снимите фиксацию');if(c.kind==='circle')throw Error('У окружности нет фиксированных концов');const a=p.nodes[w.vertexIds[0]],b=p.nodes[w.vertexIds[1]];curve=patch.radius!==undefined?curveFromRadius(a,b,patch.radius,side,major):curveFromChord(a,b,patch.sweepAngle??c.sweepAngle)}return setWallCurve(p,id,curve)}
export function splitCurvedWall(p,id,t=.5,existingNodeId){const w=p.objects.find(w=>w.id===id),c=wallCurve(p,w),parts=splitCurve(c,t),cut=wallLength(p,w)*t,newId=crypto.randomUUID(),middleId=existingNodeId??crypto.randomUUID(),nodes={...p.nodes,[middleId]:{id:middleId,...curvePoint(c,t)}};const objects=p.objects.map(o=>o.id===id?{...w,vertexIds:[w.vertexIds[0],middleId,w.curve.centerId],curve:{...w.curve,sweepAngle:parts[0].sweepAngle}}:o);objects.push({...w,id:newId,name:w.name+' (часть 2)',vertexIds:[middleId,w.vertexIds[1],w.curve.centerId],curve:{...w.curve,startAngle:parts[1].startAngle,sweepAngle:parts[1].sweepAngle}});for(let i=0;i<objects.length;i++){const o=objects[i];if(!['outline','plot','building'].includes(o.type))continue;if(o.boundaryWallIds?.includes(id)||o.id===w.buildingId&&w.wallKind==='external'){const index=o.vertexIds.findIndex((n,i)=>{const b=o.vertexIds[(i+1)%o.vertexIds.length];return n===w.vertexIds[0]&&b===w.vertexIds[1]||n===w.vertexIds[1]&&b===w.vertexIds[0]});if(index<0)throw Error('Дуга потеряла связь с контуром');objects[i]={...o,shape:'polygon',vertexIds:[...o.vertexIds.slice(0,index+1),middleId,...o.vertexIds.slice(index+1)],boundaryWallIds:o.boundaryWallIds?[...o.boundaryWallIds,newId]:undefined}}}const openings=p.openings.map(o=>{if(o.wallId!==id)return o;const start=o.anchor==='end'?wallLength(p,w)-o.offset-o.width:o.offset;if(start<cut-1e-7&&start+o.width>cut+1e-7)throw Error('Разделение пересекает проём');return{...o,wallId:start>=cut?newId:id,anchor:'start',offset:start>=cut?start-cut:start}});return{...p,nodes,objects,openings}}
export function joinCorner(p,ids,radius,bevelB){
 const walls=ids.map(id=>p.objects.find(o=>o.id===id));if(walls.length!==2||walls.some(w=>!w||w.type!=='wall'||w.curve||w.buildingId||w.locks?.length))throw Error('Выберите две свободные прямые стены без ограничений');
 const common=walls[0].vertexIds.filter(id=>walls[1].vertexIds.includes(id));if(common.length!==1)throw Error('Выберите общий стык двух стен');const joint=common[0];
 if(p.objects.some(o=>!ids.includes(o.id)&&o.vertexIds.includes(joint))||p.openings.some(o=>ids.includes(o.wallId))||p.objects.some(o=>ids.includes(o.wallMount?.wallId)))throw Error('Стык имеет дополнительные связи или проёмы: операция не применена');
 const corner=p.nodes[joint],a=p.nodes[walls[0].vertexIds.find(id=>id!==joint)],b=p.nodes[walls[1].vertexIds.find(id=>id!==joint)],geometry=bevelB===undefined?filletGeometry(corner,a,b,radius):chamferGeometry(corner,a,b,radius,bevelB),n1=crypto.randomUUID(),n2=crypto.randomUUID(),nodes={...p.nodes,[n1]:{id:n1,...geometry.start},[n2]:{id:n2,...geometry.end}};
 const objects=p.objects.map(o=>o.id===ids[0]?{...o,vertexIds:o.vertexIds.map(id=>id===joint?n1:id)}:o.id===ids[1]?{...o,vertexIds:o.vertexIds.map(id=>id===joint?n2:id)}:o);
 const id=crypto.randomUUID();objects.push({...walls[0],id,name:bevelB===undefined?'Скругление':'Фаска',vertexIds:[n1,n2]});
 let next={...p,nodes,objects};if(geometry.curve)next=setWallCurve(next,id,geometry.curve);return next;
}
export function curveOpeningIntervals(p,w){const length=wallLength(p,w),intervals=[];for(const o of p.openings.filter(o=>o.wallId===w.id)){const start=o.anchor==='end'?length-o.offset-o.width:o.offset,end=start+o.width;if(w.curve?.kind==='circle'&&end>length){intervals.push([start,length],[0,end-length])}else intervals.push([start,end])}return intervals.sort((a,b)=>a[0]-b[0])}
export function curveWallPaths(p,w){const c=wallCurve(p,w),length=curveLength(c),cuts=curveOpeningIntervals(p,w),spans=[];let start=0;for(const [a,b]of cuts){if(a>start)spans.push(curvePath(c,start/length,a/length));start=Math.max(start,b)}if(start<length)spans.push(curvePath(c,start/length,1));return spans}
export {curveFromThreePoints,curveLength,curveChord,curvePoint,curvePath};
export function contourEdgeToArc(p,contourId,index,sweep=90){const o=p.objects.find(o=>o.id===contourId&&['outline','plot','building'].includes(o.type));if(!o||!Number.isInteger(index)||index<0||index>=o.vertexIds.length)throw Error('Сторона контура не найдена');const a=o.vertexIds[index],b=o.vertexIds[(index+1)%o.vertexIds.length],existing=p.objects.find(w=>w.type==='wall'&&((w.vertexIds[0]===a&&w.vertexIds[1]===b)||(w.vertexIds[0]===b&&w.vertexIds[1]===a)));const id=existing?.id??crypto.randomUUID();let next={...p,objects:existing?p.objects:[...p.objects,{id,type:'wall',name:o.name+' — дуга '+(index+1),vertexIds:[a,b],thickness:.2,height:2.8,wallKind:o.type==='building'?'external':'internal',buildingId:o.type==='building'?o.id:undefined}]};if(existing?.curve)throw Error('Эта сторона уже имеет дугу');const w=next.objects.find(w=>w.id===id);next=setWallCurve(next,id,curveFromChord(p.nodes[w.vertexIds[0]],p.nodes[w.vertexIds[1]],sweep));return{...next,objects:next.objects.map(n=>n.id===o.id?{...n,shape:'polygon',boundaryWallIds:[...(n.boundaryWallIds??[]).filter(w=>w!==id),id]}:n)}}
export function splitCircularWall(p,id,t=.5){const w=p.objects.find(w=>w.id===id),c=wallCurve(p,w);if(c?.kind!=='circle')throw Error('Выберите окружность');const len=wallLength(p,w);if(p.openings.some(o=>o.wallId===id&&(o.anchor==='end'?len-o.offset-o.width:o.offset)+o.width>len+1e-7))throw Error('Проём пересекает начальную метку: сначала перенесите метку или проём');const startId=crypto.randomUUID();const next={...p,nodes:{...p.nodes,[startId]:{id:startId,...curvePoint(c,0)}},objects:p.objects.map(o=>o.id===id?{...o,curve:{...o.curve,kind:'arc'},vertexIds:[startId,startId,o.curve.centerId]}:o)};return splitCurvedWall(next,id,t)}

export function curveWallOutlines(p,w){const c=wallCurve(p,w),length=curveLength(c),cuts=curveOpeningIntervals(p,w),spans=[];let start=0;for(const [a,b]of cuts){if(a>start)spans.push([start/length,a/length]);start=Math.max(start,b)}if(start<length)spans.push([start/length,1]);const t=(w.thickness??.2)/2;return spans.flatMap(([a,b])=>[-t,t].map(offset=>curvePath(c,a,b,c.radius+offset)))}
