import {isVisible,isLocked,layerVisible} from './layers.mjs';
import type {Project,PlanObject} from './types';
import {FixtureSymbol} from './FixtureSymbol';
import {fixturePorts,pathOutline,resolveEngineering} from './engineering-math.mjs';
import {routeKinds,isRoute} from './engineering-catalog.mjs';
import {routeLength,pathArea} from './engineering.mjs';
import {edges} from './geometry.mjs';
export function EngineeringScene({project,selected,scale,onDimension,ghost=false,routeMode=false,exportMode=false}:{project:Project;selected:string[];scale:number;onDimension?:(id:string,index:number)=>void;ghost?:boolean;exportMode?:boolean;routeMode?:boolean}){project=resolveEngineering(project);return <g>{project.objects.filter(o=>isVisible(project,o)).filter(o=>['fixture','pipe','wire','path'].includes(o.type)).sort((a,b)=>(a.type==='fixture'?1:a.type==='path'?-1:0)-(b.type==='fixture'?1:b.type==='path'?-1:0)).map(o=>{const active=selected.includes(o.id),vs=o.vertexIds.map(id=>project.nodes[id]),def=routeKinds.find(k=>k.kind===o.kind&&k.type===o.type),stroke=active||ghost?'#c99108':o.color??def?.color??'#7f8270',unit=project.settings.unit,factor=unit==='mm'?1000:unit==='cm'?100:1,label=unit==='mm'?'мм':unit==='cm'?'см':'м';let outline:any[]=[];if(o.type==='path')try{outline=pathOutline(project,o)}catch{}return <g key={o.id} data-object={ghost?undefined:o.id}>
 {o.type==='fixture'?<FixtureSymbol project={project} object={o} scale={scale} selected={active}/>:o.type==='path'?<polygon points={outline.map(v=>`${v.x},${v.y}`).join(' ')} fill={active?'#fff6cb':'#dedfd4'} fillOpacity={.7} stroke={stroke} strokeWidth={1.5/scale}/>:<><polyline points={vs.map(v=>`${v.x},${v.y}`).join(' ')} fill="none" stroke={stroke} strokeWidth={(o.type==='wire'&&o.kind==='main'?3:2)/scale} strokeDasharray={def?.dash.split(' ').filter(Boolean).map(n=>+n/scale).join(' ')} strokeLinejoin="round"/><polyline points={vs.map(v=>`${v.x},${v.y}`).join(' ')} fill="none" stroke="transparent" strokeWidth={14/scale}/></>}
 {layerVisible(project,'labels')&&(exportMode||active||o.type==='path')&&<text x={vs[0].x+10/scale} y={vs[0].y-15/scale} fontSize={12/scale} pointerEvents="none" fill="#20232b" stroke="#f7f9fb" strokeWidth={4/scale} paintOrder="stroke">{o.name}{o.type==='path'&&outline.length?' · '+pathArea(project,o).toFixed(2)+' м²':''}</text>}
 {layerVisible(project,'dimensions')&&(exportMode||active)&&edges(project,o).filter(e=>o.type!=='fixture'||exportMode&&e.index<2).map(e=><g key={e.index} className="dimension" data-dimension={o.id} data-edge={e.index} onPointerDown={event=>{if(event.pointerType!=='touch')event.stopPropagation()}} onClick={event=>{event.stopPropagation();o.type!=='fixture'&&!isLocked(project,o)&&!project.layers.find(l=>l.id==='dimensions')?.locked&&onDimension?.(o.id,e.index)}}><text x={(e.a.x+e.b.x)/2} y={(e.a.y+e.b.y)/2-8/scale} fontSize={12/scale} textAnchor="middle" fill="#4e5662" stroke="#f7f9fb" strokeWidth={4/scale} paintOrder="stroke">{(e.length*factor).toLocaleString('ru',{maximumFractionDigits:2})} {label}</text></g>)}
 {active&&!exportMode&&!isLocked(project,o)&&vs.map((v,i)=><rect key={v.id} data-node={v.id} x={v.x-5/scale} y={v.y-5/scale} width={10/scale} height={10/scale} fill="white" stroke="#c99108" strokeWidth={1.5/scale}><title>{'Узел '+(i+1)+(o.connections?.some(c=>c.nodeId===v.id)?' · подключён':'')}</title></rect>)}
 {!exportMode&&o.type==='fixture'&&(active||routeMode)&&fixturePorts(project,o).map(port=><g key={port.id} data-port={port.id} data-fixture={o.id}><circle cx={port.x} cy={port.y} r={5/scale} fill={port.system==='hot'?'#ba6545':port.system==='cold'?'#337e9b':port.system==='electric'?'#986b16':'#655d53'} stroke="white" strokeWidth={1/scale}/><title>{o.name+' · '+port.name}</title></g>)}
 {o.type!=='fixture'&&vs.filter(v=>o.connections?.some(c=>c.nodeId===v.id)||project.objects.filter(n=>['pipe','wire'].includes(n.type)&&n.vertexIds.includes(v.id)).length>1).map(v=><circle key={v.id} cx={v.x} cy={v.y} r={3/scale} fill={stroke} stroke="white" strokeWidth={1/scale} pointerEvents="none"/>)}
 </g>})}</g>}
