import {fixtureDefinition,isRoute} from './engineering-catalog.mjs';
export function fixturePoint(p,o,x,y){const a=p.nodes[o.vertexIds[0]],r=(o.rotation??0)*Math.PI/180,dx=x*o.width*(o.mirror?-1:1),dy=y*o.depth;return{x:a.x+dx*Math.cos(r)-dy*Math.sin(r),y:a.y+dx*Math.sin(r)+dy*Math.cos(r)}}
export const fixtureCorners=(p,o)=>[[-.5,-.5],[.5,-.5],[.5,.5],[-.5,.5]].map(([x,y],i)=>({...fixturePoint(p,o,x,y),id:o.id+'-corner-'+i}));
export const fixturePorts=(p,o)=>(fixtureDefinition(o.kind)?.ports??[]).map(port=>({...port,...fixturePoint(p,o,port.x,port.y)}));
export function portCompatible(route,port){return route.type==='wire'?port.system==='electric':route.type==='pipe'&&port.system!=='electric'&&(port.system==='any'||route.kind==='other'||route.kind==='heating'||route.kind===port.system)}
export function resolveEngineering(p){const nodes={...p.nodes},objects=p.objects.map(o=>o.wallMount?{...o}:o);for(const o of objects.filter(o=>o.type==='fixture'&&o.wallMount)){const w=objects.find(w=>w.id===o.wallMount.wallId&&w.type==='wall');if(!w)continue;const a=nodes[w.vertexIds[0]],b=nodes[w.vertexIds[1]],len=Math.hypot(b.x-a.x,b.y-a.y),u={x:(b.x-a.x)/len,y:(b.y-a.y)/len};nodes[o.vertexIds[0]]={...nodes[o.vertexIds[0]],x:a.x+u.x*o.wallMount.offset,y:a.y+u.y*o.wallMount.offset};o.rotation=Math.atan2(u.y,u.x)*180/Math.PI+(o.wallMount.side===-1?180:0)}const working={...p,nodes,objects};for(const route of objects.filter(isRoute))for(const c of route.connections??[]){const f=objects.find(f=>f.id===c.fixtureId&&f.type==='fixture'),port=f&&fixturePorts(working,f).find(port=>port.id===c.portId);if(port&&nodes[c.nodeId])nodes[c.nodeId]={...nodes[c.nodeId],x:port.x,y:port.y}}return working;}
const len=(a,b)=>Math.hypot(b.x-a.x,b.y-a.y);
// Miter up to four half-widths; longer convex corners are bevelled. Butt caps.
export function offsetLine(points,offset){const lines=points.slice(0,-1).map((a,i)=>{const b=points[i+1],l=len(a,b);if(l<1e-6)throw Error('Нулевой сегмент');const delta={x:-(b.y-a.y)/l*offset,y:(b.x-a.x)/l*offset};return{a:{x:a.x+delta.x,y:a.y+delta.y},b:{x:b.x+delta.x,y:b.y+delta.y}}});if(!lines.length)throw Error('Нужны две точки');const result=[lines[0].a];for(let i=0;i<lines.length-1;i++){const a=lines[i],b=lines[i+1],dx=a.b.x-a.a.x,dy=a.b.y-a.a.y,ex=b.b.x-b.a.x,ey=b.b.y-b.a.y,den=dx*ey-dy*ex;if(Math.abs(den)<1e-10){if(dx*ex+dy*ey<=0)throw Error('Разворот дорожки на 180° недопустим');result.push(a.b);continue}const t=((b.a.x-a.a.x)*ey-(b.a.y-a.a.y)*ex)/den,q={x:a.a.x+t*dx,y:a.a.y+t*dy};if(len(q,points[i+1])<=Math.abs(offset)*4+1e-7)result.push(q);else result.push(a.b,b.a)}result.push(lines.at(-1).b);return result;}
export const pathOutline=(p,o)=>o.shape==='polygon'?o.vertexIds.map(id=>p.nodes[id]):[...offsetLine(o.vertexIds.map(id=>p.nodes[id]),o.width/2),...offsetLine(o.vertexIds.map(id=>p.nodes[id]),-o.width/2).reverse()];
export function validateEngineering(p,o,ids){
 if(o.symbolSize!==undefined&&(!Number.isFinite(o.symbolSize)||o.symbolSize<8||o.symbolSize>80))throw Error('Размер символа должен быть от 8 до 80 px');
 if(o.type==='fixture'){const d=fixtureDefinition(o.kind);if(!d||![o.width,o.depth].every(n=>Number.isFinite(n)&&n>1e-5&&n<1000)||!Number.isFinite(o.rotation)||o.mirror!==undefined&&typeof o.mirror!=='boolean')throw Error('Некорректные габариты или тип предмета');if(o.wallMount){const w=p.objects.find(w=>w.id===o.wallMount.wallId&&w.type==='wall');if(!w||!Number.isFinite(o.wallMount.offset)||o.wallMount.offset<0||o.wallMount.offset>len(p.nodes[w.vertexIds[0]],p.nodes[w.vertexIds[1]])||![1,-1].includes(o.wallMount.side))throw Error('Некорректное крепление к стене')}return;}
 if(o.type==='pipe'&&(!['cold','hot','drain','heating','other'].includes(o.kind)||!Number.isFinite(o.diameter)||o.diameter<=0||o.diameter>5)||o.type==='wire'&&!['main','secondary'].includes(o.kind))throw Error('Некорректный тип трассы или диаметр');
 if(o.color!==undefined&&!/^#[0-9a-f]{6}$/i.test(o.color)||o.group!==undefined&&(typeof o.group!=='string'||o.group.length>200)||o.material!==undefined&&(typeof o.material!=='string'||o.material.length>200))throw Error('Некорректное обозначение');
 if(o.type==='path'&&o.shape!=='polygon'&&(!Number.isFinite(o.width)||o.width<=1e-5||o.width>1000))throw Error('Ширина дорожки должна быть больше нуля');
 if(o.connections!==undefined){if(!Array.isArray(o.connections)||o.connections.length>2||!['pipe','wire'].includes(o.type))throw Error('Некорректные связи трассы');const ends=[o.vertexIds[0],o.vertexIds.at(-1)],seen=new Set();for(const c of o.connections){const f=p.objects.find(f=>f.id===c.fixtureId&&f.type==='fixture'),port=f&&fixturePorts(p,f).find(port=>port.id===c.portId);if(!ends.includes(c.nodeId)||seen.has(c.nodeId)||!port||!portCompatible(o,port))throw Error('Несовместимая или отсутствующая точка подключения');seen.add(c.nodeId);const prior=ids.get(c.nodeId),key=c.fixtureId+':'+c.portId;if(prior&&prior!==key)throw Error('Общий узел нельзя подключить к двум разным предметам');ids.set(c.nodeId,key);}}
 if(isRoute(o))for(let i=0;i<o.vertexIds.length-1;i++)if(len(p.nodes[o.vertexIds[i]],p.nodes[o.vertexIds[i+1]])<1e-6)throw Error('Трасса содержит нулевой сегмент');
}
