import {withFurniture} from './furniture-data.mjs';
import {validateProject,distance,area,selfIntersects} from './core.mjs';
import {fixtureDefinition,isRoute} from './engineering-catalog.mjs';
import {fixturePorts,portCompatible,resolveEngineering,offsetLine,pathOutline} from './engineering-math.mjs';
export {fixtureCorners,fixturePorts,pathOutline,resolveEngineering} from './engineering-math.mjs';
export function createFixture(p,kind,point){const def=fixtureDefinition(kind);if(!def)throw Error('Неизвестный предмет');if(def.category==='furniture')p=withFurniture(p);const id=crypto.randomUUID(),nodeId=crypto.randomUUID();return{project:validateProject({...p,nodes:{...p.nodes,[nodeId]:{...point,id:nodeId}},objects:[...p.objects,{id,type:'fixture',kind,name:def.name,vertexIds:[nodeId],width:def.width,depth:def.depth,rotation:0,height:def.category==='electrical'?.3:def.category==='furniture'?(def.height??.8):1}]}),ids:[id]};}
export function createRoute(p,creation,points,connections=[]){const id=crypto.randomUUID(),nodes={...p.nodes},vertexIds=points.map(q=>{const nodeId=q.junctionId??crypto.randomUUID();if(!nodes[nodeId])nodes[nodeId]={id:nodeId,x:q.x,y:q.y};return nodeId});const o={id,type:creation.type,kind:creation.kind,name:creation.name,vertexIds,width:creation.type==='path'?1:undefined,diameter:creation.type==='pipe'?.025:undefined,material:creation.type==='path'?'Плитка':undefined,connections:connections.map(c=>({...c,nodeId:vertexIds[c.index]})).map(({index,...c})=>c)};if(creation.type==='path')delete o.connections;return{project:validateProject(resolveEngineering({...p,nodes,objects:[...p.objects,o]})),ids:[id]};}
export function updateFixture(p,id,changes){return resolveEngineering({...p,objects:p.objects.map(o=>o.id===id?{...o,...changes}:o)});}
export function connectPort(p,id,end,fixtureId,portId){const route=p.objects.find(o=>o.id===id),f=p.objects.find(o=>o.id===fixtureId&&o.type==='fixture'),port=f&&fixturePorts(p,f).find(port=>port.id===portId);if(!route||!['pipe','wire'].includes(route.type)||!port||!portCompatible(route,port))throw Error('Тип трассы не подходит к точке подключения');const nodeId=end==='start'?route.vertexIds[0]:route.vertexIds.at(-1);return validateProject(resolveEngineering({...p,objects:p.objects.map(o=>o.id===id?{...o,connections:[...(o.connections??[]).filter(c=>c.nodeId!==nodeId),{nodeId,fixtureId,portId}]}:o)}));}
export function disconnectEnd(p,id,end){const route=p.objects.find(o=>o.id===id),nodeId=end==='start'?route.vertexIds[0]:route.vertexIds.at(-1),newId=crypto.randomUUID(),otherRefs=p.objects.some(o=>o.id!==id&&o.vertexIds.includes(nodeId));return{...p,nodes:otherRefs?{...p.nodes,[newId]:{...p.nodes[nodeId],id:newId}}:p.nodes,objects:p.objects.map(o=>o.id===id?{...o,vertexIds:o.vertexIds.map(v=>v===nodeId&&otherRefs?newId:v),connections:(o.connections??[]).filter(c=>c.nodeId!==nodeId)}:o)};}
export function joinRouteNode(p,id,end,targetId,nodeIndex){let next=disconnectEnd(p,id,end);const route=next.objects.find(o=>o.id===id),target=next.objects.find(o=>o.id===targetId);if(!target||!['pipe','wire'].includes(route.type)||target.type!==route.type||target.kind!==route.kind||id===targetId)throw Error('Соединяются узлы трасс одного типа и назначения');const index=end==='start'?0:route.vertexIds.length-1,nodeId=target.vertexIds[nodeIndex],oldId=route.vertexIds[index];if(!nodeId)throw Error('Узел не найден');const c=target.connections?.find(c=>c.nodeId===nodeId);next={...next,objects:next.objects.map(o=>o.id===id?{...o,vertexIds:o.vertexIds.map((v,i)=>i===index?nodeId:v),connections:c?[...(o.connections??[]),{...c}]:o.connections}:o)};if(!next.objects.some(o=>o.vertexIds.includes(oldId))){next.nodes={...next.nodes};delete next.nodes[oldId]}return validateProject(next);}
export const routeLength=(p,o)=>o.vertexIds.slice(0,-1).reduce((sum,id,i)=>sum+distance(p.nodes[id],p.nodes[o.vertexIds[i+1]]),0);
export const pathArea=(p,o)=>area(pathOutline(p,o));
export function parallelPath(p,id,offset){const o=p.objects.find(o=>o.id===id&&o.type==='path'&&o.shape!=='polygon');if(!o||!Number.isFinite(offset)||Math.abs(offset)<1e-6)throw Error('Выберите дорожку по оси и ненулевой отступ между осями');const points=offsetLine(o.vertexIds.map(id=>p.nodes[id]),offset),nodes={...p.nodes},vertexIds=points.map(v=>{const id=crypto.randomUUID();nodes[id]={...v,id};return id});return validateProject({...p,nodes,objects:[...p.objects,{...o,id:crypto.randomUUID(),name:o.name+' (параллельно)',vertexIds,locks:[]}]});}
export function insertRouteNode(p,id,index){const o=p.objects.find(o=>o.id===id),a=p.nodes[o.vertexIds[index]],b=p.nodes[o.vertexIds[index+1]],nodeId=crypto.randomUUID();if(!b)throw Error('Сегмент не найден');return{...p,nodes:{...p.nodes,[nodeId]:{id:nodeId,x:(a.x+b.x)/2,y:(a.y+b.y)/2}},objects:p.objects.map(o=>o.id===id?{...o,vertexIds:[...o.vertexIds.slice(0,index+1),nodeId,...o.vertexIds.slice(index+1)],locks:(o.locks??[]).filter(l=>l.startId!==a.id||l.endId!==b.id)}:o)};}
export function removeRouteNode(p,id,index){const o=p.objects.find(o=>o.id===id),nodeId=o.vertexIds[index];if(o.vertexIds.length<=2)throw Error('В трассе должны остаться две точки');if((o.connections??[]).some(c=>c.nodeId===nodeId)||p.objects.some(n=>n.id!==id&&n.vertexIds.includes(nodeId)))throw Error('Сначала отсоедините связанный узел');const nodes={...p.nodes};delete nodes[nodeId];return{...p,nodes,objects:p.objects.map(o=>o.id===id?{...o,vertexIds:o.vertexIds.filter((_,i)=>i!==index),locks:(o.locks??[]).filter(l=>l.startId!==nodeId&&l.endId!==nodeId)}:o)};}
