import {freshProject} from './core.mjs';
import {createGeometry} from './geometry.mjs';
import {createOpening} from './openings.mjs';
import {createFixture,createRoute,connectPort,fixturePorts,updateFixture} from './engineering.mjs';
import {validateProject} from './core.mjs';
/** @returns {import('./types').Project} */
export function exampleProject(){let p=freshProject();p.name='Учебный пример';p=createGeometry(p,{type:'plot',name:'Участок',thickness:.2},[{x:0,y:0},{x:30,y:0},{x:30,y:20},{x:0,y:20}],'rectangle').project;const home=createGeometry(p,{type:'building',name:'Дом',buildingKind:'house',thickness:.2},[{x:4,y:4},{x:14,y:4},{x:14,y:12},{x:4,y:12}],'rectangle');p=home.project;const b=p.objects.find(o=>o.id===home.ids[0]),points=b.vertexIds.map(id=>p.nodes[id]);const walls=createGeometry(p,{type:'wall',name:'Стена дома',wallKind:'external',thickness:.25},[...points,points[0]],'wall',[...b.vertexIds,b.vertexIds[0]]);p={...walls.project,objects:walls.project.objects.map(o=>walls.ids.includes(o.id)?{...o,buildingId:b.id}:o)};p=createOpening(p,walls.ids[0],'window',2,1.5,'double').project;p=createOpening(p,walls.ids[0],'window',6,1.5,'double').project;p=createOpening(p,walls.ids[2],'door',4,.9,'single').project;p=createOpening(p,walls.ids[1],'window',3,2.4,'panoramic').project;const partition=createGeometry(p,{type:'wall',name:'Перегородка',wallKind:'internal',thickness:.12},[{x:8,y:4},{x:8,y:12}],'wall');p={...partition.project,objects:partition.project.objects.map(o=>partition.ids.includes(o.id)?{...o,buildingId:b.id}:o)};p=createOpening(p,partition.ids[0],'door',4,.9,'single').project;p={...p,openings:p.openings.map((o,i)=>({...o,name:['Окно 1','Окно 2','Входная дверь','Панорамное окно','Межкомнатная дверь'][i]??o.name}))};return p;}

/** Explicitly opened only; never saved until the user edits. */
export function engineeringExample(){let p=exampleProject();p.name='Пример: инженерные системы';const house=p.objects.find(o=>o.type==='building'),created=[];
 for(const [kind,x,y] of [['bath-straight',5.4,5.2],['bath-corner',6.8,7.1],['bath-round',5.3,9.4],['sink',6.9,10.6],['toilet-floor',7,5.2],['light-ceiling',10.5,6.8],['socket-double',14,10],['switch-single',12.5,11.7]]){const result=createFixture(p,kind,{x,y});p=updateFixture(result.project,result.ids[0],{buildingId:house.id});created.push(result.ids[0]);}
 const east=p.objects.find(o=>o.type==='wall'&&p.nodes[o.vertexIds[0]].x===14&&p.nodes[o.vertexIds[1]].x===14);p=validateProject(updateFixture(p,created[6],{wallMount:{wallId:east.id,offset:6,side:-1}}));
 for(const [kind,portId,start] of [['cold','cold',{x:3,y:3}],['hot','hot',{x:3.5,y:3}],['drain','drain',{x:3,y:13}]]){const f=p.objects.find(o=>o.id===created[0]),port=fixturePorts(p,f).find(port=>port.id===portId),result=createRoute(p,{type:'pipe',kind,name:kind==='cold'?'Подача холодной воды':kind==='hot'?'Подача горячей воды':'Слив ванны'},[start,{x:start.x,y:port.y},port]);p=connectPort(result.project,result.ids[0],'end',f.id,portId);}
 const power=createRoute(p,{type:'wire',kind:'main',name:'Основной провод'},[{x:14,y:10},{x:12,y:10},{x:12,y:6.8},{x:10.5,y:6.8}]);p=connectPort(power.project,power.ids[0],'start',created[6],'power');p=connectPort(p,power.ids[0],'end',created[5],'power');
 const secondary=createRoute(p,{type:'wire',kind:'secondary',name:'Провод выключателя'},[{x:12.5,y:11.7},{x:10.5,y:11.7},{x:10.5,y:6.8}]);p=connectPort(secondary.project,secondary.ids[0],'start',created[7],'power');p=connectPort(p,secondary.ids[0],'end',created[5],'power');
 p=createRoute(p,{type:'path',name:'Дорожка к дому'},[{x:9.55,y:12},{x:9.55,y:16},{x:25,y:16}]).project;return validateProject(p);
}
