import {useState} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {Scene} from './Scene';
import {exportBounds,exportSize} from './export-plan.mjs';
import type {Project} from './types';
export function downloadBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name.replace(/[<>:"/\\|?*]/g,'_');a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function ExportDialog({project,onClose}:{project:Project;onClose:()=>void}){
 const [layers,setLayers]=useState(project.layers.map(l=>({...l}))),[scale,setScale]=useState('40'),[margin,setMargin]=useState('24'),[manual,setManual]=useState(false),[bounds,setBounds]=useState({x:'0',y:'0',width:'30',height:'20'}),[transparent,setTransparent]=useState(false),[format,setFormat]=useState('svg'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const p={...project,layers},n=(s:string)=>Number(s.replace(',','.'));
 let b:any,size:any;try{if(n(margin)<0||n(margin)>500||!Number.isFinite(n(margin)))throw Error('Поля: 0–500 px');b=manual?Object.fromEntries(Object.entries(bounds).map(([k,v])=>[k,n(v)])):exportBounds(p,n(scale),n(margin));size=exportSize(b,n(scale))}catch(e){size=null}
 const run=async()=>{setError('');setBusy(true);try{
  const s=n(scale);if(!Number.isFinite(n(margin))||n(margin)<0||n(margin)>500)throw Error('Поля: 0–500 px');const box=manual?Object.fromEntries(Object.entries(bounds).map(([k,v])=>[k,n(v)])):exportBounds(p,s,n(margin)),pixels=exportSize(box,s);
  const markup=renderToStaticMarkup(<svg xmlns="http://www.w3.org/2000/svg" width={pixels.width} height={pixels.height} viewBox={`${box.x} ${box.y} ${box.width} ${box.height}`}><title>{project.name}</title><style>{'text{font-family:Arial,sans-serif}.fixture-glyph *{vector-effect:non-scaling-stroke}'}</style>{!transparent&&<rect x={box.x} y={box.y} width={box.width} height={box.height} fill="white"/>}<Scene project={p} selected={[]} scale={s} exportMode/></svg>);
  const svg=new Blob([markup],{type:'image/svg+xml;charset=utf-8'});
  if(format==='svg')downloadBlob(svg,project.name+'.svg');else{
   const url=URL.createObjectURL(svg);try{const img=new Image();img.src=url;await img.decode();const canvas=document.createElement('canvas');canvas.width=pixels.width;canvas.height=pixels.height;const context=canvas.getContext('2d');if(!context)throw Error('PNG недоступен в этом браузере');context.drawImage(img,0,0);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(v=>v?resolve(v):reject(Error('Не удалось создать PNG')),'image/png'));downloadBlob(blob,project.name+'.png')}finally{URL.revokeObjectURL(url)}
  }
 }catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <div className="overlay"><div className="dialog export-dialog"><h2>Экспорт изображения плана</h2><p className="hint">Только план, без панелей. Размеры всех видимых объектов включаются слоем «Размеры».</p><div className="export-layers">{layers.map(l=><label key={l.id} className="check"><input type="checkbox" checked={l.visible} onChange={e=>setLayers(layers.map(n=>n.id===l.id?{...n,visible:e.target.checked}:n))}/>{l.name}</label>)}</div><div className="fields"><label>Формат<select value={format} onChange={e=>setFormat(e.target.value)}><option value="svg">SVG</option><option value="png">PNG</option></select></label><label>Масштаб, px/м<input value={scale} onChange={e=>setScale(e.target.value)}/></label><label>Поля, px<input value={margin} disabled={manual} onChange={e=>setMargin(e.target.value)}/></label></div><label className="check"><input type="checkbox" checked={transparent} onChange={e=>setTransparent(e.target.checked)}/>Прозрачный фон</label><label className="check"><input type="checkbox" checked={manual} onChange={e=>setManual(e.target.checked)}/>Задать границы вручную (метры)</label>{manual&&<div className="fields">{Object.entries(bounds).map(([k,v])=><label key={k}>{({x:'X',y:'Y',width:'Ширина',height:'Высота'} as any)[k]}<input value={v} onChange={e=>setBounds({...bounds,[k]:e.target.value})}/></label>)}</div>}<p>{size?`${size.width} × ${size.height} px`:'Проверьте масштаб, границы и выбранные слои'}</p>{manual&&<p className="hint">За пределами заданной области план будет обрезан.</p>}{error&&<p role="alert" className="error">{error}</p>}<button className="primary" disabled={busy||!size} onClick={()=>void run()}>{busy?'Подготовка…':'Скачать '+format.toUpperCase()}</button><button onClick={onClose} disabled={busy}>Закрыть</button></div></div>
}
