import {fixtureCorners,resolveEngineering} from './engineering-math.mjs';
import {isRoute} from './engineering-catalog.mjs';
import {moveOpening,openingGeometry} from './openings.mjs';
import {angle,distance,validateProject,angleDelta} from './core.mjs';
/** @param {import('./types').Project} p @param {import('./types').PlanObject} o */
export const vertices=(p,o)=>o.type==='fixture'?fixtureCorners(p,o):o.vertexIds.map(id=>p.nodes[id]);
/** @param {import('./types').Project} p @param {import('./types').PlanObject} o */
export function edges(p,o){const vs=vertices(p,o);return vs.slice(0,o.type==='wall'?1:isRoute(o)?vs.length-1:vs.length).map((a,i)=>{const b=vs[(i+1)%vs.length];return {a,b,index:i,length:distance(a,b),angle:angle(a,b)}});}
/** @param {import('./types').Project} p @param {string[]} ids @param {number} dx @param {number} dy */
export function moveObjects(p,ids,dx,dy){ids=expandSelection(p,ids);const nodeIds=new Set(p.objects.filter(o=>ids.includes(o.id)).flatMap(o=>o.vertexIds));for(const o of p.objects.filter(o=>ids.includes(o.id)&&o.wallMount)){const w=p.objects.find(w=>w.id===o.wallMount.wallId);if(!w.vertexIds.every(id=>nodeIds.has(id)))throw Error('Прибор закреплён: измените отступ или включите свободное размещение')}const nodes={...p.nodes};for(const id of nodeIds)nodes[id]={...nodes[id],x:nodes[id].x+dx,y:nodes[id].y+dy};let next={...p,nodes};for(const opening of p.openings??[])if(ids.includes(opening.id)){const wall=p.objects.find(o=>o.id===opening.wallId);if(wall.vertexIds.every(id=>nodeIds.has(id)))continue;const old=openingGeometry(p,opening),g=openingGeometry(next,opening),a=next.nodes[wall.vertexIds[0]],target={x:old.center.x+dx,y:old.center.y+dy},start=(target.x-a.x)*g.u.x+(target.y-a.y)*g.u.y-opening.width/2;next={...next,openings:next.openings.map(o=>o.id===opening.id?{...o,offset:o.anchor==='end'?g.length-start-o.width:start}:o)}}return resolveEngineering(next);}
/** @param {import('./types').Project} p @param {string[]} ids */
export function duplicateObjects(p,ids,dx=1,dy=1){ids=expandSelection(p,ids);const mapping=new Map(),objectMapping=new Map();for(const o of p.objects.filter(o=>ids.includes(o.id)))objectMapping.set(o.id,crypto.randomUUID());const nodes={...p.nodes};const clones=p.objects.filter(o=>ids.includes(o.id)).map(o=>{const vertexIds=o.vertexIds.map(id=>{if(!mapping.has(id)){const n=crypto.randomUUID();mapping.set(id,n);nodes[n]={...p.nodes[id],id:n,x:p.nodes[id].x+dx,y:p.nodes[id].y+dy};}return mapping.get(id)});return {...o,id:objectMapping.get(o.id),name:o.name+' (копия)',vertexIds,connections:o.connections?.filter(c=>objectMapping.has(c.fixtureId)).map(c=>({...c,nodeId:mapping.get(c.nodeId),fixtureId:objectMapping.get(c.fixtureId)})),wallMount:o.wallMount&&objectMapping.has(o.wallMount.wallId)?{...o.wallMount,wallId:objectMapping.get(o.wallMount.wallId)}:undefined,buildingId:o.buildingId?objectMapping.get(o.buildingId)??(o.wallKind==='external'?undefined:o.buildingId):undefined,locks:o.locks?.map(l=>({...l,startId:mapping.get(l.startId),endId:mapping.get(l.endId)}))}});const openings=(p.openings??[]).filter(o=>ids.includes(o.id)||objectMapping.has(o.wallId)).map(o=>({...o,id:crypto.randomUUID(),name:o.name+' (копия)',wallId:objectMapping.get(o.wallId)??o.wallId,offset:objectMapping.has(o.wallId)?o.offset:o.offset+(o.anchor==='end'?-1:1)*(dx*openingGeometry(p,o).u.x+dy*openingGeometry(p,o).u.y)}));return {project:resolveEngineering({...p,nodes,objects:[...p.objects,...clones],openings:[...(p.openings??[]),...openings]}),ids:[...clones.map(o=>o.id),...openings.map(o=>o.id)]};}
/** @param {import('./types').Project} p @param {string[]} ids */
export function deleteObjects(p,ids){ids=expandSelection(p,ids);p=resolveEngineering(p);const objects=p.objects.filter(o=>!ids.includes(o.id)).map(o=>({...o,buildingId:ids.includes(o.buildingId??'')?undefined:o.buildingId,connections:o.connections?.filter(c=>!ids.includes(c.fixtureId)),wallMount:o.wallMount&&ids.includes(o.wallMount.wallId)?undefined:o.wallMount}));const used=new Set(objects.flatMap(o=>o.vertexIds));return {...p,objects,openings:(p.openings??[]).filter(o=>!ids.includes(o.id)&&!ids.includes(o.wallId)),nodes:Object.fromEntries(Object.entries(p.nodes).filter(([id])=>used.has(id)))};}
/** @param {import('./types').Project} p @param {import('./types').Creation} creation @param {import('./types').Point[]} points @param {'rectangle'|'polygon'|'wall'} shape @param {(string|undefined)[]} existingIds @returns {{project: import('./types').Project, ids:string[]}} */
export function createGeometry(p,creation,points,shape,existingIds=[]){const nodes={...p.nodes};const assigned=[];const vertexIds=points.map((point,i)=>{const prior=points.findIndex((q,j)=>j<i&&distance(q,point)<1e-8);const coincident=shape==='wall'?Object.values(nodes).find(n=>distance(n,point)<1e-8&&(assigned.includes(n.id)||p.objects.some(o=>['plot','building','wall','outline'].includes(o.type)&&o.vertexIds.includes(n.id))))?.id:undefined;const id=existingIds[i]??coincident??(prior>=0?assigned[prior]:crypto.randomUUID());assigned[i]=id;if(!nodes[id])nodes[id]={...point,id};return id});const added=shape==='wall'?vertexIds.slice(0,-1).map((id,i)=>({id:crypto.randomUUID(),type:'wall',name:creation.name+' '+(i+1),vertexIds:[id,vertexIds[i+1]],thickness:creation.thickness,height:2.8,wallKind:creation.wallKind??'external'})):[{id:crypto.randomUUID(),type:creation.type,name:creation.name,vertexIds,shape,buildingKind:creation.buildingKind}];let next={...p,nodes,objects:[...p.objects,...added]};if(shape==='wall')for(const nodeId of new Set(vertexIds)){const n=next.nodes[nodeId];for(const wall of [...next.objects].filter(o=>o.type==='wall'&&!o.vertexIds.includes(nodeId))){const a=next.nodes[wall.vertexIds[0]],b=next.nodes[wall.vertexIds[1]],hit=projectOnSegment(n,a,b);if(hit.t>1e-7&&hit.t<1-1e-7&&distance(hit.point,n)<1e-7)next=splitWall(next,wall.id,nodeId);}}validateProject(next);return {project:next,ids:added.map(o=>o.id)};}
/** @param {import('./types').Project} p @param {string} id @param {number} index @param {number} length @param {'start'|'end'|'center'} anchor @param {number|undefined} direction @returns {import('./types').Project} */
export function resizeEdge(p,id,index,length,anchor='start',direction=undefined){if(!Number.isFinite(length)||length<=1e-6)throw Error('Длина должна быть больше нуля');const o=p.objects.find(o=>o.id===id);if(!o)throw Error('Объект не найден');const {a,b,angle:oldAngle}=edges(p,o)[index];const deg=direction??oldAngle;if(!Number.isFinite(deg))throw Error('Неверный угол');const rad=deg*Math.PI/180,dx=Math.cos(rad)*length,dy=Math.sin(rad)*length;const nodes={...p.nodes};if(anchor==='end')nodes[a.id]={...a,x:b.x-dx,y:b.y-dy};else if(anchor==='center'){const x=(a.x+b.x)/2,y=(a.y+b.y)/2;nodes[a.id]={...a,x:x-dx/2,y:y-dy/2};nodes[b.id]={...b,x:x+dx/2,y:y+dy/2};}else nodes[b.id]={...b,x:a.x+dx,y:a.y+dy};const objects=p.objects.map(item=>item.id===id&&item.shape==='rectangle'?{...item,shape:'polygon'}:item);for(const route of p.objects)for(const c of route.connections??[])if(distance(p.nodes[c.nodeId],nodes[c.nodeId])>1e-7)throw Error('Конец трассы закреплён: выберите другую опору или отсоедините подключение');return resolveEngineering({...p,nodes,objects});}
/** @param {import('./types').Project} p @param {string} id @param {number} width @param {number} height @param {number} degrees @param {'start'|'center'} anchor */
export function resizeRectangle(p,id,width,height,degrees,anchor='start'){if(![width,height,degrees].every(Number.isFinite)||width<=1e-6||height<=1e-6)throw Error('Габариты должны быть больше нуля');const o=p.objects.find(o=>o.id===id);if(!o||o.shape!=='rectangle')throw Error('Выберите прямоугольник');const vs=vertices(p,o),r=degrees*Math.PI/180,u={x:Math.cos(r),y:Math.sin(r)},orientation=(vs[1].x-vs[0].x)*(vs[2].y-vs[1].y)-(vs[1].y-vs[0].y)*(vs[2].x-vs[1].x)>=0?1:-1,v={x:-Math.sin(r)*orientation,y:Math.cos(r)*orientation};const center={x:vs.reduce((s,n)=>s+n.x,0)/4,y:vs.reduce((s,n)=>s+n.y,0)/4};const origin=anchor==='center'?{x:center.x-u.x*width/2-v.x*height/2,y:center.y-u.y*width/2-v.y*height/2}:vs[0];const points=[origin,{x:origin.x+u.x*width,y:origin.y+u.y*width},{x:origin.x+u.x*width+v.x*height,y:origin.y+u.y*width+v.y*height},{x:origin.x+v.x*height,y:origin.y+v.y*height}];const nodes={...p.nodes};o.vertexIds.forEach((nodeId,i)=>nodes[nodeId]={...nodes[nodeId],...points[i]});return {...p,nodes};}
/** @param {import('./types').Project} before @param {import('./types').Project} after */
export function changedEdges(before,after){const result=[];for(const o of before.objects){const next=after.objects.find(n=>n.id===o.id);if(!next)continue;const old=edges(before,o),updated=edges(after,next);old.forEach((edge,i)=>{if(!updated[i])return;if(Math.abs(edge.length-updated[i].length)>1e-6||Math.abs(angleDelta(edge.angle,updated[i].angle))>1e-6)result.push({name:o.name,index:i,before:edge.length,after:updated[i].length,angle:updated[i].angle})})}return result;}
/** @param {import('./types').Project} p @param {string} id @param {number} index @param {'length'|'angle'} kind */
export function toggleLock(p,id,index,kind){return {...p,objects:p.objects.map(o=>{if(o.id!==id)return o;const e=edges(p,o)[index];const locks=[...(o.locks??[])];const pos=locks.findIndex(l=>l.startId===e.a.id&&l.endId===e.b.id);const lock=pos>=0?{...locks[pos]}:{startId:e.a.id,endId:e.b.id};if(lock[kind]!==undefined)delete lock[kind];else lock[kind]=kind==='length'?e.length:e.angle;if(pos>=0)locks.splice(pos,1);if(lock.length!==undefined||lock.angle!==undefined)locks.push(lock);return {...o,locks}})};}



/** @param {import('./types').Point} p @param {import('./types').Point} a @param {import('./types').Point} b */
export function projectOnSegment(p,a,b){const dx=b.x-a.x,dy=b.y-a.y,t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy)));return{t,point:{x:a.x+dx*t,y:a.y+dy*t}};}
/** @param {import('./types').Project} p @param {string} wallId @param {string|undefined} existingNodeId @returns {import('./types').Project} */
export function splitWall(p,wallId,existingNodeId=undefined){const wall=p.objects.find(o=>o.id===wallId);if(!wall||wall.type!=='wall')throw Error('Стена не найдена');if(wall.locks?.length)throw Error('Снимите ограничения стены перед созданием Т-узла или разделением');const a=p.nodes[wall.vertexIds[0]],b=p.nodes[wall.vertexIds[1]],id=existingNodeId??crypto.randomUUID(),node=p.nodes[id]??{id,x:(a.x+b.x)/2,y:(a.y+b.y)/2};if(distance(node,a)<1e-6||distance(node,b)<1e-6)throw Error('Точка разделения должна быть внутри стены');const newWallId=crypto.randomUUID(),splitDistance=distance(a,node);const openings=(p.openings??[]).map(o=>{if(o.wallId!==wallId)return o;const g=openingGeometry(p,o);if(g.start<splitDistance-1e-7&&g.start+o.width>splitDistance+1e-7)throw Error('Точка разделения пересекает проём. Выберите другой узел или перенесите проём');return {...o,wallId:g.start>=splitDistance-1e-7?newWallId:wallId,anchor:'start',offset:g.start>=splitDistance-1e-7?g.start-splitDistance:g.start}});const objects=p.objects.flatMap(o=>{if(o.wallMount?.wallId===wallId&&o.wallMount.offset>=splitDistance)return[{...o,wallMount:{...o.wallMount,wallId:newWallId,offset:o.wallMount.offset-splitDistance}}];if(o.id===wallId)return[{...o,vertexIds:[a.id,id]},{...o,id:newWallId,name:o.name+' (часть 2)',vertexIds:[id,b.id]}];if(o.id===wall.buildingId&&wall.wallKind==='external'){const index=o.vertexIds.findIndex((n,i)=>n===a.id&&o.vertexIds[(i+1)%o.vertexIds.length]===b.id||n===b.id&&o.vertexIds[(i+1)%o.vertexIds.length]===a.id);if(index<0)throw Error('Стена не связана с контуром');return[{...o,shape:'polygon',vertexIds:[...o.vertexIds.slice(0,index+1),id,...o.vertexIds.slice(index+1)]}];}return[o]});return{...p,nodes:{...p.nodes,[id]:node},objects,openings};}




/** @param {import('./types').Project} p @param {string[]} ids */
export function expandSelection(p,ids){return [...new Set([...ids,...p.objects.filter(o=>o.buildingId&&ids.includes(o.buildingId)).map(o=>o.id)])];}
