import {distance,angle,validateProject} from './core.mjs';
/** @param {import('./types').Project} p @param {import('./types').Opening} opening */
export function openingGeometry(p,opening){const wall=p.objects.find(o=>o.id===opening.wallId&&o.type==='wall');if(!wall)throw Error('Стена проёма не найдена');const a=p.nodes[wall.vertexIds[0]],b=p.nodes[wall.vertexIds[1]],length=distance(a,b),u={x:(b.x-a.x)/length,y:(b.y-a.y)/length},start=opening.anchor==='end'?length-opening.offset-opening.width:opening.offset;return {wall,length,u,start,a:{x:a.x+u.x*start,y:a.y+u.y*start},b:{x:a.x+u.x*(start+opening.width),y:a.y+u.y*(start+opening.width)},center:{x:a.x+u.x*(start+opening.width/2),y:a.y+u.y*(start+opening.width/2)},angle:angle(a,b)};}
/** @param {import('./types').Project} p @param {string} wallId @param {'door'|'window'} type @param {number} offset @param {number} width @param {import('./types').Opening['kind']} kind @returns {{project:import('./types').Project,id:string}} */
export function createOpening(p,wallId,type,offset,width=type==='door'?.9:1.2,kind=type==='door'?'single':'standard'){const o={id:crypto.randomUUID(),wallId,type,name:type==='door'?'Дверь':'Окно',offset,width,anchor:'start',height:type==='door'?2.1:1.4,sill:type==='window'?.9:undefined,hinge:'start',side:1,kind};const next={...p,openings:[...(p.openings??[]),o]};validateProject(next);return{project:next,id:o.id};}
/** @param {import('./types').Project} p @param {string} id @param {Partial<import('./types').Opening>} patch @returns {import('./types').Project} */
export function updateOpening(p,id,patch){return {...p,openings:p.openings.map(o=>o.id===id?{...o,...patch}:o)};}
/** @param {import('./types').Project} p @param {string} id @param {'start'|'end'} anchor @returns {import('./types').Project} */
export function changeOpeningAnchor(p,id,anchor){const o=p.openings.find(o=>o.id===id);if(!o)throw Error('Проём не найден');const g=openingGeometry(p,o);return updateOpening(p,id,{anchor,offset:anchor==='start'?g.start:g.length-g.start-o.width});}
/** @param {import('./types').Project} p @param {string} id @param {number} dx @param {number} dy @returns {import('./types').Project} */
export function moveOpening(p,id,dx,dy){const o=p.openings.find(o=>o.id===id);if(!o)return p;const g=openingGeometry(p,o),shift=dx*g.u.x+dy*g.u.y;return updateOpening(p,id,{offset:o.offset+(o.anchor==='end'?-shift:shift)});}
/** @param {import('./types').Project} p @param {string} id @param {string} wallId @returns {import('./types').Project} */
export function rehostOpening(p,id,wallId){return updateOpening(p,id,{wallId,offset:0,anchor:'start'});}
/** @param {import('./types').Project} p @param {import('./types').PlanObject} wall */
export function wallSpans(p,wall){const a=p.nodes[wall.vertexIds[0]],b=p.nodes[wall.vertexIds[1]],length=distance(a,b),u={x:(b.x-a.x)/length,y:(b.y-a.y)/length},cuts=p.openings.filter(o=>o.wallId===wall.id).map(o=>openingGeometry(p,o)).sort((a,b)=>a.start-b.start);const spans=[];let cursor=0;for(const cut of cuts){if(cut.start>cursor)spans.push([cursor,cut.start]);cursor=Math.max(cursor,cut.start+distance(cut.a,cut.b))}if(cursor<length)spans.push([cursor,length]);return spans.map(([s,e])=>({a:{x:a.x+s*u.x,y:a.y+s*u.y},b:{x:a.x+e*u.x,y:a.y+e*u.y}}));}
