import {useEffect,useState} from 'react';
import type {PlanObject,Project} from './types';
import {contourArea} from './contour-math.mjs';
import {contourEdgeToArc} from './curved-walls.mjs';
import {area,angle,distance} from './core.mjs';
import {vertices,edges,resizeEdge,resizeRectangle,toggleLock,moveObjects,splitWall} from './geometry.mjs';
const number=(s:string)=>Number(s.replace(',','.'));
export function Numeric({label,value,onApply,positive=false}:{label:string;value:number;onApply:(n:number)=>void;positive?:boolean}){const [text,setText]=useState(String(Number(value.toFixed(6)))),[error,setError]=useState('');useEffect(()=>{setText(String(Number(value.toFixed(6))));setError('')},[value]);return <form onSubmit={e=>{e.preventDefault();const n=number(text);if(!text.trim()||!Number.isFinite(n)||positive&&n<=0){setError('Введите '+(positive?'положительное ':'')+'число');return}setError('');onApply(n)}}><label>{label}<div className="numeric"><input aria-label={label} value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Escape'){setText(String(value));setError('')}}}/><button title="Подтвердить ввод" type="submit">↵</button></div></label>{error&&<small className="error">{error}</small>}</form>}
export function Properties({project,selected,onCommit,onPreview,onError,edgeRequest}:{project:Project;selected:string[];onCommit:(p:Project)=>void;onPreview:(p:Project)=>void;onError:(s:string)=>void;edgeRequest:{id:string;index:number;nonce:number}|null}){
 const o=project.objects.find(o=>o.id===selected[0]);const factor={m:1,cm:100,mm:1000}[project.settings.unit],unit={m:'м',cm:'см',mm:'мм'}[project.settings.unit];
 const [anchor,setAnchor]=useState<'start'|'end'|'center'>('start');
 const edit=(fn:()=>Project,preview=true)=>{try{const next=fn();if(preview)onPreview(next);else onCommit(next)}catch(e){onError((e as Error).message)}};
 const update=(patch:Partial<PlanObject>)=>onCommit({...project,objects:project.objects.map(n=>n.id===o?.id?{...n,...patch}:n)});
 useEffect(()=>{if(edgeRequest){const selectedObject=project.objects.find(n=>n.id===edgeRequest.id);if(selectedObject?.shape==='rectangle'){const input=document.querySelector<HTMLInputElement>('[aria-label="'+(edgeRequest.index%2===0?'Длина':'Ширина')+', '+unit+'"]');input?.scrollIntoView({block:'center'});input?.focus();input?.select()}else{document.getElementById('edge-'+edgeRequest.index)?.scrollIntoView({block:'nearest'});document.querySelector<HTMLInputElement>('#edge-'+edgeRequest.index+' input')?.focus()}}},[edgeRequest]);
 if(!o||selected.length!==1)return <><h2>{selected.length>1?`Выбрано: ${selected.length}`:'Настройки плана'}</h2><p className="hint">Выберите объект. Shift добавляет к группе. Изменения общих узлов обновляют все связанные стены.</p><Settings project={project} onCommit={onCommit}/></>;
 const vs=vertices(project,o),es=edges(project,o);const rectangle=o.shape==='rectangle';
 return <><h2>{o.type==='wall'?'Стена':o.type==='building'?'Постройка':o.type==='plot'?'Участок':'Контур'}</h2><label>Название<input key={o.id+o.name} defaultValue={o.name} maxLength={200} onBlur={e=>{if(e.target.value!==o.name)update({name:e.target.value})}} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur()}}/></label>{o.type!=='wall'&&<div className="area-card"><b>{contourArea(project,o).toLocaleString('ru',{maximumFractionDigits:3})} м²</b><small>Площадь по внешнему контуру</small></div>}
 {o.type==='path'&&<label>Материал<input defaultValue={o.material??'Плитка'} maxLength={200} onBlur={e=>update({material:e.target.value})}/></label>}{o.type==='building'&&<label>Тип постройки<select value={o.buildingKind??'other'} onChange={e=>update({buildingKind:e.target.value as PlanObject['buildingKind']})}><option value="house">Дом</option><option value="garage">Гараж</option><option value="shed">Сарай</option><option value="gazebo">Беседка</option><option value="other">Другое</option></select></label>}
 {['outline','plot','building'].includes(o.type)&&<details><summary>Кривые стороны контура</summary><p className="hint">Выберите сторону для дуги 90°. Радиус и охват затем редактируются в свойствах созданной стены. Площадь учитывает дугу по оси.</p>{o.vertexIds.map((id,i)=><button key={id} onClick={()=>edit(()=>contourEdgeToArc(project,o.id,i,90))}>Сторона {i+1} → дуга</button>)}</details>}<h3>Неподвижная опора</h3><select aria-label="Неподвижная опора" value={anchor} onChange={e=>setAnchor(e.target.value as typeof anchor)}><option value="start">Начало / первый угол</option>{!rectangle&&<option value="end">Конец стороны</option>}<option value="center">Центр</option></select>
 {rectangle&&<><h3>Габариты</h3><Numeric label={`Длина, ${unit}`} value={es[0].length*factor} positive onApply={n=>edit(()=>resizeRectangle(project,o.id,n/factor,es[1].length,es[0].angle,anchor==='center'?'center':'start'))}/><Numeric label={`Ширина, ${unit}`} value={es[1].length*factor} positive onApply={n=>edit(()=>resizeRectangle(project,o.id,es[0].length,n/factor,es[0].angle,anchor==='center'?'center':'start'))}/><Numeric label="Поворот, °" value={es[0].angle} onApply={n=>edit(()=>resizeRectangle(project,o.id,es[0].length,es[1].length,n,anchor==='center'?'center':'start'))}/><p className="hint">Для свободного изменения отдельных сторон преобразуйте прямоугольник в многоугольник.</p><button onClick={()=>update({shape:'polygon'})}>Преобразовать в многоугольник</button></>}
 {o.type==='wall'&&<><Numeric label={`Толщина, ${unit}`} value={(o.thickness??.2)*factor} positive onApply={n=>update({thickness:n/factor})}/><Numeric label={`Высота, ${unit}`} value={(o.height??2.8)*factor} positive onApply={n=>update({height:n/factor})}/><label>Назначение<select value={o.wallKind??'external'} onChange={e=>update({wallKind:e.target.value as any})}><option value="external">Внешняя стена</option><option value="internal">Перегородка</option></select></label><label>Постройка<select value={o.buildingId??''} onChange={e=>update({buildingId:e.target.value||undefined})}><option value="">Без привязки</option>{project.objects.filter(b=>b.type==='building').map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><p className="hint">Длина стены измеряется по оси. Внешняя стена связывается с постройкой только через соседние узлы её контура. Перегородки внутри хранятся отдельно.</p></>}
 <h3>{o.type==='wall'?'Длина и направление':'Стороны контура'}</h3>{es.map((e,i)=>{const lock=o.locks?.find(l=>l.startId===e.a.id&&l.endId===e.b.id);return <div className="edge-card" id={'edge-'+i} key={e.a.id+e.b.id}><b>{o.type==='wall'?'Ось стены':`Сторона ${i+1}`}</b>{e.curve?<p>Осевая дуга: {(e.length*factor).toLocaleString('ru')} {unit}. Радиус и охват — в свойствах связанной дуговой стены.</p>:rectangle?<p>{(e.length*factor).toLocaleString('ru')} {unit} · {e.angle.toFixed(1)}°</p>:<><Numeric label={`Длина стороны ${i+1}, ${unit}`} value={e.length*factor} positive onApply={n=>edit(()=>resizeEdge(project,o.id,i,n/factor,anchor))}/><Numeric label={`Угол стороны ${i+1}, °`} value={e.angle} onApply={n=>edit(()=>resizeEdge(project,o.id,i,e.length,anchor,n))}/></>}<div className="fields"><button disabled={!!e.curve} className={lock?.length!==undefined?'active':''} onClick={()=>edit(()=>toggleLock(project,o.id,i,'length'),false)}>{lock?.length!==undefined?'🔒':'○'} Длина</button><button disabled={!!e.curve} className={lock?.angle!==undefined?'active':''} onClick={()=>edit(()=>toggleLock(project,o.id,i,'angle'),false)}>{lock?.angle!==undefined?'🔒':'○'} Угол</button></div></div>})}
 <h3>Положение, {unit}</h3><Numeric label={`X опоры, ${unit}`} value={vs[0].x*factor} onApply={n=>edit(()=>moveObjects(project,[o.id],n/factor-vs[0].x,0))}/><Numeric label={`Y опоры, ${unit}`} value={vs[0].y*factor} onApply={n=>edit(()=>moveObjects(project,[o.id],0,n/factor-vs[0].y))}/>
 {!rectangle&&<><h3>Узлы</h3>{vs.map((v,i)=><details key={v.id}><summary>Вершина {i+1} · {project.objects.filter(n=>n.vertexIds.includes(v.id)).length>1?'общий узел':'отдельная'}</summary><label>Имя вершины<input defaultValue={(v as {name?:string}).name??''} maxLength={200} onBlur={e=>onCommit({...project,nodes:{...project.nodes,[v.id]:{...v,name:e.target.value}}})}/></label><Numeric label={`X вершины ${i+1}, ${unit}`} value={v.x*factor} onApply={n=>edit(()=>({...project,nodes:{...project.nodes,[v.id]:{...v,x:n/factor}}}))}/><Numeric label={`Y вершины ${i+1}, ${unit}`} value={v.y*factor} onApply={n=>edit(()=>({...project,nodes:{...project.nodes,[v.id]:{...v,y:n/factor}}}))}/>{o.type!=='wall'&&<div className="fields"><button onClick={()=>{const b=vs[(i+1)%vs.length],id=crypto.randomUUID();edit(()=>({...project,nodes:{...project.nodes,[id]:{id,x:(v.x+b.x)/2,y:(v.y+b.y)/2}},objects:project.objects.map(n=>n.id===o.id?{...n,vertexIds:[...n.vertexIds.slice(0,i+1),id,...n.vertexIds.slice(i+1)],locks:(n.locks??[]).filter(l=>l.startId!==v.id)}:n)}))}}>Вставить после</button><button disabled={vs.length<=3} onClick={()=>edit(()=>({...project,objects:project.objects.map(n=>n.id===o.id?{...n,vertexIds:n.vertexIds.filter(id=>id!==v.id),locks:(n.locks??[]).filter(l=>l.startId!==v.id&&l.endId!==v.id)}:n)}))}>Удалить узел</button></div>}</details>)}</>}
 {o.type==='wall'&&<button onClick={()=>{edit(()=>splitWall(project,o.id))}}>Разделить стену пополам</button>}
 <Settings project={project} onCommit={onCommit}/></>;
}
function Settings({project,onCommit}:{project:Project;onCommit:(p:Project)=>void}){return <><h3>Единицы и сетка</h3><label>Единицы<select value={project.settings.unit} onChange={e=>onCommit({...project,settings:{...project.settings,unit:e.target.value as any}})}><option value="m">Метры</option><option value="cm">Сантиметры</option><option value="mm">Миллиметры</option></select></label><Numeric label="Сетка, м" value={project.settings.grid} positive onApply={n=>onCommit({...project,settings:{...project.settings,grid:n}})}/><Numeric label="Шаг привязки, м" value={project.settings.snap} positive onApply={n=>onCommit({...project,settings:{...project.settings,snap:n}})}/><p className="hint">Enter / ↵ — числовой ввод.<br/>Колесо — масштаб. Space / H — рука.<br/>Alt — без привязки. Shift — ортогонально.<br/>Enter — завершить цепочку.<br/>Escape — отменить построение.<br/>Ctrl+S — сохранить.</p></>}
