import {inspectResource} from './resource-bytes.mjs';
import {cloudEnabled,supabase} from './cloud';
import {RESOURCE_LIMIT,PIXEL_LIMIT,RESOURCE_MIMES} from './underlays.mjs';
import type {Resource} from './types';
import {sha256} from './browser-crypto.mjs';
export async function hashBlob(blob:Blob){return sha256(await blob.arrayBuffer())}
export async function decodeImage(blob:Blob){const url=URL.createObjectURL(blob);try{const image=new Image();image.src=url;await image.decode();if(!image.naturalWidth||image.naturalWidth>8192||image.naturalHeight>8192||image.naturalWidth*image.naturalHeight>PIXEL_LIMIT)throw Error('Изображение: до 8192 px и 24 Мп');return {width:image.naturalWidth,height:image.naturalHeight}}catch(e){throw Error('Изображение повреждено или превышает 8192 px / 24 Мп')}finally{URL.revokeObjectURL(url)}}
export function checkFile(file:Blob){if(!RESOURCE_MIMES.includes(file.type))throw Error('Выберите JPG, PNG, WEBP или PDF');if(!file.size||file.size>RESOURCE_LIMIT)throw Error('Файл: до 20 МБ')}
export async function uploadResource(blob:Blob,name:string):Promise<Resource>{checkFile(blob);inspectResource(new Uint8Array(await blob.arrayBuffer()),blob.type);const dimensions=blob.type==='application/pdf'?{}:await decodeImage(blob),id=await hashBlob(blob),resource={id,sha256:id,mimeType:blob.type,byteLength:blob.size,name:name.slice(0,200),...dimensions};if(cloudEnabled){if(!supabase)throw Error('Облачное хранилище не настроено');const {data,error}=await supabase.auth.getUser();if(error||!data.user)throw Error('Для загрузки войдите в аккаунт');const result=await supabase.storage.from('home-planer-assets').upload(data.user.id+'/'+id,blob,{contentType:blob.type,upsert:false});if(result.error&&!['409','Duplicate'].includes(String((result.error as any).statusCode))&&!/already exists/i.test(result.error.message))throw Error(result.error.message);return resource}const response=await fetch('/api/resources?name='+encodeURIComponent(resource.name),{method:'POST',headers:{'Content-Type':blob.type},body:blob});const data=await response.json();if(!response.ok)throw Error(data.error);return data}
export async function downloadResource(resource:Resource){let blob:Blob;if(cloudEnabled){if(!supabase)throw Error('Облачное хранилище не настроено');const {data,error}=await supabase.auth.getUser();if(error||!data.user)throw Error('Войдите для загрузки подложки');const result=await supabase.storage.from('home-planer-assets').download(data.user.id+'/'+resource.id);if(result.error)throw Error(result.error.message);blob=result.data}else{const response=await fetch('/api/resources/'+resource.id);if(!response.ok)throw Error('Файл подложки недоступен');blob=await response.blob()}if(blob.size!==resource.byteLength||await hashBlob(blob)!==resource.sha256)throw Error('Контрольная сумма подложки не совпадает');return blob}
export const blobDataUrl=(blob:Blob)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=()=>reject(Error('Не удалось прочитать файл'));r.readAsDataURL(blob)});
