import {wallCurve} from './curved-walls.mjs';
import {curvePoint,curveTangent,curveParameter,curveLength,curveAreaContribution,curveIntersections,lineCurveIntersections,curvePath,curveBounds} from './curve-math.mjs';
const EPS=1e-7, dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),cross=(a,b)=>a.x*b.y-a.y*b.x;
const lerp=(a,b,t)=>({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t});
function lineHit(a,b,c,d,extend=false){const u={x:b.x-a.x,y:b.y-a.y},v={x:d.x-c.x,y:d.y-c.y},den=cross(u,v);if(Math.abs(den)<1e-12)return[];const w={x:c.x-a.x,y:c.y-a.y},t=cross(w,v)/den,s=cross(w,u)/den;return extend||t>=-EPS&&t<=1+EPS&&s>=-EPS&&s<=1+EPS?[lerp(a,b,t)]:[];}
export function roomEdge(p,ref){const w=p.objects.find(w=>w.id===ref.wallId&&w.type==='wall');if(!w)throw Error('Стена комнаты не найдена');const c=wallCurve(p,w);if(c){const curve={...c,kind:'arc',startAngle:c.startAngle+c.sweepAngle*ref.from,sweepAngle:c.sweepAngle*(ref.to-ref.from)};return{...ref,a:curvePoint(curve,0),b:curvePoint(curve,1),curve,thickness:w.thickness??.2}}return{...ref,a:lerp(p.nodes[w.vertexIds[0]],p.nodes[w.vertexIds[1]],ref.from),b:lerp(p.nodes[w.vertexIds[0]],p.nodes[w.vertexIds[1]],ref.to),curve:null,thickness:w.thickness??.2};}
const tangent=(e,start)=>e.curve?curveTangent(e.curve,start?0:1):{x:e.b.x-e.a.x,y:e.b.y-e.a.y};
const reverse=e=>({...e,from:e.to,to:e.from,a:e.b,b:e.a,curve:e.curve?{...e.curve,startAngle:e.curve.startAngle+e.curve.sweepAngle,sweepAngle:-e.curve.sweepAngle}:null});
export const signedEdgeArea=edges=>edges.reduce((sum,e)=>sum+(e.curve?curveAreaContribution(e.curve):cross(e.a,e.b)/2),0);
export const edgeLength=e=>e.curve?curveLength(e.curve):dist(e.a,e.b);
export const edgesPath=edges=>edges.length?'M '+edges[0].a.x+' '+edges[0].a.y+' '+edges.map(e=>e.curve?curvePath(e.curve).replace(/^M [^ ]+ [^ ]+ /,''):`L ${e.b.x} ${e.b.y}`).join(' ')+' Z':'';
export function sampleEdges(edges){return edges.flatMap(e=>{if(!e.curve)return[e.a];const count=Math.max(2,Math.ceil(Math.abs(e.curve.sweepAngle)/3));return Array.from({length:count},(_,i)=>curvePoint(e.curve,i/count));});}
export function pointInEdges(point,edges){const polygon=sampleEdges(edges);let inside=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const a=polygon[i],b=polygon[j];if((a.y>point.y)!==(b.y>point.y)&&point.x<(b.x-a.x)*(point.y-a.y)/(b.y-a.y)+a.x)inside=!inside;}return inside;}
export function edgesBounds(edges){const points=edges.flatMap(e=>{if(!e.curve)return[e.a,e.b];const b=curveBounds(e.curve);return[{x:b.minX,y:b.minY},{x:b.maxX,y:b.maxY}]});return{minX:Math.min(...points.map(p=>p.x)),minY:Math.min(...points.map(p=>p.y)),maxX:Math.max(...points.map(p=>p.x)),maxY:Math.max(...points.map(p=>p.y))};}
export function interiorAnchor(edges){const b=edgesBounds(edges),center={x:(b.minX+b.maxX)/2,y:(b.minY+b.maxY)/2};if(pointInEdges(center,edges))return center;for(const e of edges){const m=e.curve?curvePoint(e.curve,.5):lerp(e.a,e.b,.5),t=tangent(e,true),len=Math.hypot(t.x,t.y),step=Math.max(1e-5,Math.min(b.maxX-b.minX,b.maxY-b.minY)*.001),q={x:m.x-t.y/len*step,y:m.y+t.x/len*step};if(pointInEdges(q,edges))return q;}return center;}
const faceCache=new Map();
export function detectRoomFaces(p){
 const walls=p.objects.filter(w=>w.type==='wall'),key=JSON.stringify(walls.map(w=>[w.id,w.vertexIds.map(id=>p.nodes[id]),w.curve,w.thickness]));if(faceCache.has(key))return faceCache.get(key);
 if(walls.length>2000)throw Error('Распознавание комнат: до 2000 стен в текущем плане');
 const source=walls.map(w=>{const e=roomEdge(p,{wallId:w.id,from:0,to:1});return{...e,cuts:w.curve?.kind==='circle'?[0,.5,1]:[0,1],bounds:edgesBounds([e])}});
 for(let i=0;i<source.length;i++)for(let j=i+1;j<source.length;j++){const a=source[i],b=source[j],A=a.bounds,B=b.bounds;if(A.maxX<B.minX-EPS||B.maxX<A.minX-EPS||A.maxY<B.minY-EPS||B.maxY<A.minY-EPS)continue;let hits=[];try{hits=a.curve&&b.curve?curveIntersections(a.curve,b.curve):a.curve?lineCurveIntersections(b.a,b.b,a.curve):b.curve?lineCurveIntersections(a.a,a.b,b.curve):lineHit(a.a,a.b,b.a,b.b)}catch{continue}for(const hit of hits)for(const e of [a,b]){const t=e.curve?curveParameter(e.curve,hit):((hit.x-e.a.x)*(e.b.x-e.a.x)+(hit.y-e.a.y)*(e.b.y-e.a.y))/dist(e.a,e.b)**2;if(t>EPS&&t<1-EPS)e.cuts.push(t);}}
 const vertices=new Map(),segments=[],buckets=new Map();const vertex=q=>{const x=Math.floor(q.x/1e-6),y=Math.floor(q.y/1e-6);for(let i=x-1;i<=x+1;i++)for(let j=y-1;j<=y+1;j++){const existing=buckets.get(i+','+j)?.find(v=>dist(v.point,q)<1e-6);if(existing)return existing.key;}const cell=x+','+y,key='v'+vertices.size;vertices.set(key,[]);if(!buckets.has(cell))buckets.set(cell,[]);buckets.get(cell).push({key,point:q});return key;};
 for(const sourceEdge of source){const cuts=[...new Set(sourceEdge.cuts.map(t=>Number(t.toFixed(12))))].sort((a,b)=>a-b);for(let i=0;i<cuts.length-1;i++){const e=roomEdge(p,{wallId:sourceEdge.wallId,from:cuts[i],to:cuts[i+1]}),start=vertex(e.a),end=vertex(e.b);if(start===end)continue;const index=segments.length;segments.push({e,start,end,alive:true});vertices.get(start).push(index);vertices.get(end).push(index);}}
 // Open branches do not break an otherwise closed logical room.
 const queue=[...vertices].filter(([,links])=>links.length<2).map(([key])=>key);while(queue.length){const k=queue.pop();for(const index of vertices.get(k)){const s=segments[index];if(!s.alive)continue;s.alive=false;const other=s.start===k?s.end:s.start;if(vertices.get(other).filter(i=>segments[i].alive).length<2)queue.push(other);}}
 const halves=[],outgoing=new Map();for(const s of segments.filter(s=>s.alive)){for(const [e,start,end] of [[s.e,s.start,s.end],[reverse(s.e),s.end,s.start]]){const t=tangent(e,true),h={...e,start,end,index:halves.length,angle:Math.atan2(t.y,t.x)};halves.push(h);if(!outgoing.has(start))outgoing.set(start,[]);outgoing.get(start).push(h);}}
 for(const list of outgoing.values())list.sort((a,b)=>a.angle-b.angle||a.wallId.localeCompare(b.wallId));const visited=new Set(),faces=[];
 for(const initial of halves){if(visited.has(initial.index))continue;const edges=[];let h=initial;for(let guard=0;guard<=halves.length;guard++){if(visited.has(h.index))break;visited.add(h.index);edges.push(h);const list=outgoing.get(h.end),twin=halves[h.index^1],at=list.findIndex(e=>e.index===twin.index);h=list[(at+list.length-1)%list.length];if(h.index===initial.index)break;}if(h.index!==initial.index||edges.length<2||signedEdgeArea(edges)<EPS)continue;const refs=edges.map(({wallId,from,to})=>({wallId,from,to}));faces.push({boundary:refs,edges,axisArea:signedEdgeArea(edges),anchor:interiorAnchor(edges),key:refs.map(e=>e.wallId+':'+e.from+':'+e.to).sort().join('|')});}
 for(const face of faces){const contained=faces.filter(other=>other!==face&&other.axisArea<face.axisArea-EPS&&other.edges.every(e=>pointInEdges(e.a,face.edges))&&!other.boundary.some(e=>face.boundary.some(f=>f.wallId===e.wallId)));face.holes=contained.filter(other=>!contained.some(parent=>parent!==other&&parent.axisArea>other.axisArea&&pointInEdges(other.anchor,parent.edges))).map(child=>child.boundary.slice().reverse().map(e=>({wallId:e.wallId,from:e.to,to:e.from})));}
 const result=faces.sort((a,b)=>a.key.localeCompare(b.key));faceCache.set(key,result);if(faceCache.size>8)faceCache.delete(faceCache.keys().next().value);return result;
}
function fullCircle(c){return{...c,kind:'circle',startAngle:0,sweepAngle:360};}
function supportingIntersections(a,b){if(a.curve&&b.curve)return curveIntersections(fullCircle(a.curve),fullCircle(b.curve));if(a.curve)return lineCurveIntersections(b.a,b.b,fullCircle(a.curve),true);if(b.curve)return lineCurveIntersections(a.a,a.b,fullCircle(b.curve),true);return lineHit(a.a,a.b,b.a,b.b,true);}
export function offsetRoomEdges(edges,side=1){
 const shifted=edges.map(e=>{const amount=side*e.thickness/2;if(e.curve){const radius=e.curve.radius-Math.sign(e.curve.sweepAngle)*amount;if(radius<=EPS)throw Error('Внутренний радиус комнаты схлопнулся');const curve={...e.curve,radius};return{...e,curve,a:curvePoint(curve,0),b:curvePoint(curve,1)}}const l=dist(e.a,e.b),delta={x:-(e.b.y-e.a.y)/l*amount,y:(e.b.x-e.a.x)/l*amount};return{...e,a:{x:e.a.x+delta.x,y:e.a.y+delta.y},b:{x:e.b.x+delta.x,y:e.b.y+delta.y}}});
 for(let i=0;i<shifted.length;i++){const a=shifted[i],b=shifted[(i+1)%shifted.length],original=edges[i].b;if(dist(a.b,b.a)<EPS)continue;let hits=[];try{hits=supportingIntersections(a,b)}catch{}const point=hits.sort((x,y)=>dist(x,original)-dist(y,original))[0];if(point&&dist(point,original)<Math.max(a.thickness,b.thickness)*20){a.b=point;b.a=point;}}
 const result=[];for(let i=0;i<shifted.length;i++){const e=shifted[i];if(e.curve){const c=e.curve,oldStart=c.startAngle,start=Math.atan2(e.a.y-c.center.y,e.a.x-c.center.x)*180/Math.PI,end=Math.atan2(e.b.y-c.center.y,e.b.x-c.center.x)*180/Math.PI,normDelta=x=>((x+180)%360+360)%360-180,sweep=c.sweepAngle+normDelta(end-(oldStart+c.sweepAngle))-normDelta(start-oldStart);if(Math.sign(sweep)!==Math.sign(c.sweepAngle)||Math.abs(sweep)<EPS)throw Error('Внутренние грани комнаты пересекаются');e.curve={...c,startAngle:start,sweepAngle:sweep};}else if((e.b.x-e.a.x)*(edges[i].b.x-edges[i].a.x)+(e.b.y-e.a.y)*(edges[i].b.y-edges[i].a.y)<=EPS)throw Error('Внутренняя грань комнаты схлопнулась');result.push(e);const next=shifted[(i+1)%shifted.length];if(dist(e.b,next.a)>EPS)result.push({a:e.b,b:next.a,curve:null,connector:true,thickness:0});}
 return result;
}
export function roomMetrics(p,room){const axis=room.boundary.map(e=>roomEdge(p,e)),edges=offsetRoomEdges(axis),holes=(room.holes??[]).map(loop=>offsetRoomEdges(loop.map(e=>roomEdge(p,e)))),area=signedEdgeArea(edges)+holes.reduce((s,e)=>s+signedEdgeArea(e),0);if(area<=EPS)throw Error('Площадь пола схлопнулась');const boundaryIds=new Set([...room.boundary,...(room.holes??[]).flat()].map(e=>e.wallId));for(const wall of p.objects.filter(w=>w.type==='wall'&&!boundaryIds.has(w.id))){const e=roomEdge(p,{wallId:wall.id,from:0,to:1}),mid=e.curve?curvePoint(e.curve,.5):lerp(e.a,e.b,.5);if(pointInEdges(mid,edges)&&!holes.some(h=>pointInEdges(mid,h)))throw Error('Внутри комнаты есть незамкнутая стена; чистая площадь требует замкнутых внутренних граней');}const samples=sampleEdges(edges);for(let i=0;i<samples.length;i++)for(let j=i+2;j<samples.length;j++){if(i===0&&j===samples.length-1)continue;const hits=lineHit(samples[i],samples[(i+1)%samples.length],samples[j],samples[(j+1)%samples.length]);if(hits.some(q=>dist(q,samples[i])>EPS&&dist(q,samples[(i+1)%samples.length])>EPS))throw Error('Внутренние грани пересекаются: проверьте толщину стен');}return{area,perimeter:[edges,...holes].reduce((s,loop)=>s+loop.reduce((s,e)=>s+edgeLength(e),0),0),axisArea:signedEdgeArea(axis),edges,holes,bounds:edgesBounds(edges),path:edgesPath(edges)+holes.map(edgesPath).join(' '),anchor:(()=>{let anchor=interiorAnchor(edges);if(holes.some(h=>pointInEdges(anchor,h))){for(const e of edges){const t=tangent(e,true),l=Math.hypot(t.x,t.y),mid=e.curve?curvePoint(e.curve,.5):lerp(e.a,e.b,.5),q={x:mid.x-t.y/l*.001,y:mid.y+t.x/l*.001};if(pointInEdges(q,edges)&&!holes.some(h=>pointInEdges(q,h))){anchor=q;break;}}}return anchor})()};}
