import {isVisible} from './layers.mjs';
import type {Project,Point} from './types';
import {roomMetrics,edgeLength} from './room-math.mjs';
import {wallDimensionEdge,openingDimensionChain,fixtureClearances,layoutChainLabels,chainTotalOffset} from './room-commands.mjs';
import {curvePoint,curveTangent} from './curve-math.mjs';
import {wallCurve} from './curved-walls.mjs';
export function RoomScene({project:p,roomId,scale,onRoom,ghost=false,exportMode=false}:{project:Project;roomId?:string|null;scale:number;onRoom?:(id:string)=>void;ghost?:boolean;exportMode?:boolean}){if(p.layers.find(l=>l.id==='rooms')?.visible===false)return null;return <g>{(p.rooms??[]).filter(r=>r.active).map(r=>{try{const m=roomMetrics(p,r),selected=r.id===roomId;return <g key={r.id} data-room={r.id} onPointerDown={e=>{if(onRoom)e.stopPropagation()}} onClick={e=>{if(onRoom){e.stopPropagation();onRoom(r.id)}}} pointerEvents={ghost?'none':undefined}><path d={m.path} fill={ghost?'#ffd338':r.fill} fillOpacity={ghost?.22:.55} fillRule="evenodd" stroke={selected?'#c99108':'none'} strokeWidth={2/scale}/>{!ghost&&p.layers.find(l=>l.id==='labels')?.visible!==false&&<text x={r.anchor.x+r.labelOffset.x} y={r.anchor.y+r.labelOffset.y} textAnchor="middle" fontSize={12/scale} fill="#35433c"><tspan x={r.anchor.x+r.labelOffset.x}>{r.name}</tspan><tspan x={r.anchor.x+r.labelOffset.x} dy={15/scale}>{m.area.toFixed(2)} м² · P {m.perimeter.toFixed(2)} м</tspan></text>}</g>}catch{return <text key={r.id} x={r.anchor.x+r.labelOffset.x} y={r.anchor.y+r.labelOffset.y} textAnchor="middle" fontSize={12/scale} fill="#b45c32" onClick={()=>onRoom?.(r.id)}>{r.name}: площадь недоступна</text>}})}</g>;}
function Dimension({a,b,text,scale,offset=.25,color='#68717e',labelOffset={x:0,y:0},lane=0}:{a:Point;b:Point;text:string;scale:number;offset?:number;color?:string;labelOffset?:Point;lane?:number}){const len=Math.hypot(b.x-a.x,b.y-a.y);if(len<1e-8)return <text pointerEvents="none" x={a.x+labelOffset.x} y={a.y-12/scale+labelOffset.y} textAnchor="middle" fontSize={11/scale} fill={color}>{text}</text>;const nx=-(b.y-a.y)/len,ny=(b.x-a.x)/len,x1=a.x+nx*offset,y1=a.y+ny*offset,x2=b.x+nx*offset,y2=b.y+ny*offset;return <g pointerEvents="none"><path d={`M ${x1} ${y1} L ${x2} ${y2} M ${a.x} ${a.y} L ${x1+nx*4/scale} ${y1+ny*4/scale} M ${b.x} ${b.y} L ${x2+nx*4/scale} ${y2+ny*4/scale}`} fill="none" stroke={color} strokeWidth={1/scale}/>{(labelOffset.x||labelOffset.y)&&<path d={`M ${(x1+x2)/2} ${(y1+y2)/2} L ${(x1+x2)/2+labelOffset.x} ${(y1+y2)/2+labelOffset.y}`} stroke={color} strokeWidth={.7/scale} fill="none"/>}<text x={(x1+x2)/2+labelOffset.x+nx*lane*16/scale} y={(y1+y2)/2-4/scale+labelOffset.y+ny*lane*16/scale} textAnchor="middle" fontSize={11/scale} fill={color} stroke="#f7f9fb" strokeWidth={3/scale} paintOrder="stroke">{text}</text></g>;}
export function MeasurementScene({project:p,selected,roomId,scale,exportMode=false}:{project:Project;selected:string[];roomId?:string|null;scale:number;exportMode?:boolean}){const m=p.settings.measurements;if(!m||p.layers.find(l=>l.id==='dimensions')?.visible===false)return null;const modeText={axis:'Ось',inner:'Внутренняя грань',outer:'Внешняя грань'};return <g>
 {m.showRoomDimensions&&p.layers.find(l=>l.id==='rooms')?.visible!==false&&(p.rooms??[]).filter(r=>r.active&&(exportMode||r.id===roomId)).map(r=>{try{const metrics=roomMetrics(p,r);return <g key={r.id}>{metrics.edges.filter(e=>!e.connector).map((e,i)=><Dimension key={i} a={e.a} b={e.b} text={'Внутр. '+edgeLength(e).toFixed(3)+' м'+(e.curve?' по дуге':'')} scale={scale} offset={-(e.thickness??.2)-18/scale}/>)}</g>}catch{return null}})}
 {m.showWallDimensions&&p.objects.filter(w=>w.type==='wall'&&isVisible(p,w)&&!(exportMode&&m.showRoomDimensions&&p.layers.find(l=>l.id==='rooms')?.visible!==false&&p.rooms?.some(r=>r.active&&[...r.boundary,...r.holes.flat()].some(e=>e.wallId===w.id)))&&(exportMode||selected.includes(w.id))).map(w=>{try{const e=wallDimensionEdge(p,w,m.mode,roomId??undefined);return <Dimension key={w.id} a={e.a} b={e.b} text={modeText[m.mode]+': '+edgeLength(e).toFixed(3)+' м'+(e.curve?' по дуге':'')+(e.roomName?' · '+e.roomName:m.mode==='axis'?'':' · левая сторона оси')} scale={scale} offset={-22/scale}/>}catch{return null}})}
 {m.showChains&&(p.dimensionChains??[]).map(c=>{const wall=p.objects.find(w=>w.id===c.wallId);if(!wall||p.layers.find(l=>l.id===wall.layerId)?.visible===false)return null;const chain=openingDimensionChain(p,wall),curve=wallCurve(p,wall),labels=layoutChainLabels(chain,c,scale,!!curve);return <g key={wall.id}>{labels.map((label:{a:Point;b:Point;text:string;labelOffset:Point},i:number)=><Dimension key={i} a={label.a} b={label.b} text={label.text} scale={scale} offset={c.offset} labelOffset={label.labelOffset}/>)}<Dimension a={chain.point(0)} b={chain.point(chain.length)} text={'Общая ось: '+chain.length.toFixed(3)+' м'} scale={scale} offset={chainTotalOffset(chain,c,scale,labels)}/></g>})}
 {m.showClearances&&p.objects.filter(f=>f.type==='fixture'&&isVisible(p,f)&&selected.includes(f.id)).flatMap(f=>fixtureClearances(p,f).slice(0,4).map(hit=><Dimension key={f.id+hit.wallId} a={hit.foot} b={hit.fixturePoint} text={hit.wallName+': '+hit.distance.toFixed(3)+' м'} scale={scale} offset={0} color={hit.distance<0?'#c93434':'#337e9b'}/>))}
 </g>;}
