import {withUnderlays} from './underlays.mjs';
import {detectRoomFaces,roomEdge,roomMetrics,pointInEdges,interiorAnchor} from './room-math.mjs';
export const roomLayer=()=>({id:'rooms',name:'Комнаты',visible:true,locked:false});
export const defaultMeasurements=()=>({mode:'axis',showRoomDimensions:true,showWallDimensions:true,showClearances:true,showChains:true});
export function withRooms(p){const next=withUnderlays(p);return {...next,schemaVersion:Math.max(6,p.schemaVersion),layers:next.layers.some(l=>l.id==='rooms')?next.layers:[...next.layers,roomLayer()],rooms:p.rooms??[],dimensionChains:p.dimensionChains??[],settings:{...p.settings,measurements:p.settings.measurements??defaultMeasurements()}};}
const validId=id=>typeof id==='string'&&/^[a-zA-Z0-9-]{1,80}$/.test(id),validPoint=n=>n&&[n.x,n.y].every(Number.isFinite)&&Math.max(Math.abs(n.x),Math.abs(n.y))<=1e6;
const key=boundary=>boundary.map(e=>e.wallId+':'+e.from+':'+e.to).sort().join('|');
export function validateRooms(p){
 if(p.schemaVersion<6){if(p.rooms!==undefined||p.dimensionChains!==undefined||p.settings.measurements!==undefined)throw Error('Комнаты и измерения требуют формат v6');return}
 if(!Array.isArray(p.rooms)||p.rooms.length>1000||!Array.isArray(p.dimensionChains)||p.dimensionChains.length>1000)throw Error('Некорректные комнаты или размеры');
 const ids=new Set([...Object.keys(p.nodes),...p.objects.map(o=>o.id),...p.openings.map(o=>o.id),...(p.resources??[]).map(r=>r.id),...(p.underlays??[]).map(u=>u.id),...(p.jointConstraints??[]).map(c=>c.id)]);
 const validLoop=loop=>Array.isArray(loop)&&loop.length<=4000&&loop.every(e=>validId(e.wallId)&&[e.from,e.to].every(Number.isFinite)&&Math.min(e.from,e.to)>=0&&Math.max(e.from,e.to)<=1&&Math.abs(e.to-e.from)>1e-9);
 for(const r of p.rooms){if(!validId(r.id)||ids.has(r.id)||typeof r.name!=='string'||r.name.length>200||typeof r.purpose!=='string'||r.purpose.length>200||!/^#[a-f\d]{6}$/i.test(r.fill)||typeof r.active!=='boolean'||!validPoint(r.anchor)||!validPoint(r.labelOffset)||!validLoop(r.boundary)||!Array.isArray(r.holes)||r.holes.length>1000||!r.holes.every(validLoop)||r.lastArea!==undefined&&(!Number.isFinite(r.lastArea)||r.lastArea<0))throw Error('Некорректная комната');ids.add(r.id);}
 const m=p.settings.measurements;if(!m||!['axis','inner','outer'].includes(m.mode)||['showRoomDimensions','showWallDimensions','showClearances','showChains'].some(k=>typeof m[k]!=='boolean'))throw Error('Некорректные настройки измерений');
 const seen=new Set();for(const c of p.dimensionChains){if(!validId(c.wallId)||seen.has(c.wallId)||!Number.isFinite(c.offset)||Math.abs(c.offset)>100||!Array.isArray(c.labelOffsets)||c.labelOffsets.length>1000||c.labelOffsets.some(n=>!validPoint(n)))throw Error('Некорректная цепочка размеров');seen.add(c.wallId);}
}
export function reconcileRooms(p){
 if(p.schemaVersion<6)return p;const faces=detectRoomFaces(p),old=p.rooms??[],assigned=new Map(),used=new Set(),inFace=(room,face)=>pointInEdges(room.anchor,face.edges)&&!face.holes.some(loop=>pointInEdges(room.anchor,loop.map(e=>roomEdge(p,e))));
 const ordered=[...old].sort((a,b)=>Number(b.active)-Number(a.active)||(b.lastArea??0)-(a.lastArea??0)||a.id.localeCompare(b.id));
 // Exact boundary identity wins. On merge the largest active predecessor keeps its ID/name.
 for(const r of ordered){const i=faces.findIndex((f,i)=>!assigned.has(i)&&key(r.boundary)===f.key);if(i>=0){assigned.set(i,r);used.add(r.id);}}
 for(const r of ordered){if(used.has(r.id))continue;const scores=faces.map((f,i)=>({i,score:assigned.has(i)?-1:(inFace(r,f)?1000:0)+f.boundary.filter(e=>r.boundary.some(old=>old.wallId===e.wallId)).length})).sort((a,b)=>b.score-a.score||faces[b.i].axisArea-faces[a.i].axisArea);if(scores[0]?.score>0){assigned.set(scores[0].i,r);used.add(r.id);}}
 let part=1;const rooms=faces.map((f,i)=>{let r=assigned.get(i);if(!r){const parent=ordered.filter(r=>r.active).map(r=>({r,count:f.boundary.filter(e=>r.boundary.some(n=>n.wallId===e.wallId)).length})).sort((a,b)=>b.count-a.count)[0];r=parent?.count?{...parent.r,id:crypto.randomUUID(),name:parent.r.name+' — часть '+(++part),labelOffset:{x:0,y:0}}:{id:crypto.randomUUID(),name:'Комната '+(i+1),purpose:'Не задано',fill:'#edf3e7',labelOffset:{x:0,y:0}};}
 const next={...r,active:true,boundary:f.boundary,holes:f.holes,anchor:r.anchor&&inFace(r,f)?r.anchor:f.anchor};try{const metrics=roomMetrics(p,next);next.lastArea=metrics.area;if(!pointInEdges(next.anchor,metrics.edges)||metrics.holes.some(h=>pointInEdges(next.anchor,h)))next.anchor=metrics.anchor;}catch{next.lastArea=0;}return next;});
 const result={...p,rooms:[...rooms,...old.filter(r=>!rooms.some(n=>n.id===r.id)).map(r=>({...r,active:false}))],dimensionChains:p.dimensionChains.filter(c=>p.objects.some(w=>w.id===c.wallId&&w.type==='wall'))};validateRooms(result);return result;
}
export function roomChanges(before,after){const lines=[];for(const r of after.rooms??[]){const old=before.rooms?.find(n=>n.id===r.id);if(r.active&&(!old?.active||JSON.stringify(r.boundary)!==JSON.stringify(old.boundary)||Math.abs((r.lastArea??0)-(old.lastArea??0))>1e-7))lines.push(r.name+': '+(old?.active?(old.lastArea??0).toFixed(3)+' → ':'')+(r.lastArea? r.lastArea.toFixed(3)+' м²':'площадь недоступна'));if(!r.active&&old?.active)lines.push(old.name+': контур исчезнет; свойства сохранятся в недействующих комнатах');}return lines;}
export function assertRoomEdits(before,after){if(before.id!==after.id)return;if(before.layers.find(l=>l.id==='dimensions')?.locked&&JSON.stringify(before.dimensionChains??[])!==JSON.stringify(after.dimensionChains??[]))throw Error('Слой размеров заблокирован');if(!before.layers.find(l=>l.id==='rooms')?.locked)return;const metadata=r=>JSON.stringify([r.name,r.purpose,r.fill,r.labelOffset]);for(const r of before.rooms??[]){const next=after.rooms?.find(n=>n.id===r.id);if(next&&metadata(r)!==metadata(next))throw Error('Слой комнат заблокирован');}}
