import {isVisible,isLocked,layerVisible} from './layers.mjs';
import {EngineeringScene} from './EngineeringScene';
import {wallSpans} from './openings.mjs';
import {OpeningSymbol} from './OpeningSymbol';
import type {Project} from './types';
import {area} from './core.mjs';
import {vertices,edges} from './geometry.mjs';
export function Scene({project,selected,scale,onDimension,ghost=false,base,routeMode=false,exportMode=false}:{project:Project;selected:string[];scale:number;onDimension?:(id:string,index:number)=>void;ghost?:boolean;exportMode?:boolean;routeMode?:boolean;base?:Project}){const factor={m:1,cm:100,mm:1000}[project.settings.unit],unit={m:'м',cm:'см',mm:'мм'}[project.settings.unit];return <g opacity={ghost?.45:1} pointerEvents={ghost?'none':undefined}>{[...project.objects].filter(o=>isVisible(project,o)).filter(o=>!['fixture','pipe','wire','path'].includes(o.type)).filter(o=>!ghost||!base||JSON.stringify(base.objects.find(n=>n.id===o.id))!==JSON.stringify(o)||o.vertexIds.some(id=>JSON.stringify(base.nodes[id])!==JSON.stringify(project.nodes[id]))||JSON.stringify(base.openings.filter(n=>n.wallId===o.id))!==JSON.stringify(project.openings.filter(n=>n.wallId===o.id))).sort((a,b)=>(a.type==='wall'?1:0)-(b.type==='wall'?1:0)).map(o=>{const vs=vertices(project,o),isSelected=selected.includes(o.id),stroke=ghost||isSelected?'#c99108':'#50545b';return <g key={o.id} data-object={ghost?undefined:o.id}>{o.type==='wall'?<><>{wallSpans(project,o).map((span,i)=><line key={i} x1={span.a.x} y1={span.a.y} x2={span.b.x} y2={span.b.y} stroke={stroke} strokeWidth={o.thickness??.2} strokeLinecap="butt"/>)}</><line x1={vs[0].x} y1={vs[0].y} x2={vs[1].x} y2={vs[1].y} stroke="transparent" strokeWidth={Math.max(o.thickness??.2,14/scale)}/></>:<polygon points={vs.map(v=>`${v.x},${v.y}`).join(' ')} fill={isSelected?'#fff6cb':o.type==='building'?'#ffffff':'#edf3e7'} fillOpacity={o.type==='building'?.9:.55} stroke={stroke} strokeWidth={(isSelected?2:1.5)/scale}/>}
 {layerVisible(project,'labels')&&(exportMode||o.type!=='wall'||isSelected)&&<text className="plan-label" x={vs[0].x+8/scale} y={vs[0].y+(o.type==='wall'?-40:20)/scale} fontSize={12/scale} fill="#20232b" pointerEvents="none">{o.name}{o.type!=='wall'?' · '+area(vs).toLocaleString('ru',{maximumFractionDigits:2})+' м²':''}</text>}
 {layerVisible(project,'dimensions')&&(exportMode||isSelected||o.type==='plot')&&edges(project,o).map(e=>{const dx=e.b.x-e.a.x,dy=e.b.y-e.a.y,length=e.length,offset=18/scale,nx=dy/length*offset,ny=-dx/length*offset,tx=(e.a.x+e.b.x)/2+nx,ty=(e.a.y+e.b.y)/2+ny;return <g key={e.index} className="dimension" data-dimension={o.id} data-edge={e.index} onPointerDown={event=>{if(event.pointerType!=='touch')event.stopPropagation()}} onClick={event=>{event.stopPropagation();!isLocked(project,o)&&!project.layers.find(l=>l.id==='dimensions')?.locked&&onDimension?.(o.id,e.index)}}><path d={`M ${e.a.x+nx} ${e.a.y+ny} L ${e.b.x+nx} ${e.b.y+ny} M ${e.a.x+nx/2} ${e.a.y+ny/2} L ${e.a.x+nx*1.4} ${e.a.y+ny*1.4} M ${e.b.x+nx/2} ${e.b.y+ny/2} L ${e.b.x+nx*1.4} ${e.b.y+ny*1.4}`} fill="none" stroke="#68717e" strokeWidth={1/scale}/><text x={tx} y={ty-4/scale} textAnchor="middle" fontSize={12/scale} fill="#4e5662" stroke="#f7f9fb" strokeWidth={4/scale} paintOrder="stroke">{(length*factor).toLocaleString('ru',{maximumFractionDigits:2})} {unit}</text></g>})}
 {isSelected&&!exportMode&&!isLocked(project,o)&&vs.map((v,i)=><rect key={v.id} data-node={v.id} x={v.x-5/scale} y={v.y-5/scale} width={10/scale} height={10/scale} fill="white" stroke="#c99108" strokeWidth={1.5/scale}><title>{'Узел '+(i+1)+': перетащить'}</title></rect>)}
 </g>})}{project.openings.filter(o=>isVisible(project,o)).filter(o=>!ghost||!base||JSON.stringify(base.openings.find(n=>n.id===o.id))!==JSON.stringify(o)||project.objects.find(w=>w.id===o.wallId)?.vertexIds.some(id=>JSON.stringify(base.nodes[id])!==JSON.stringify(project.nodes[id]))).map(o=><g key={o.id} data-opening={ghost?undefined:o.id}><OpeningSymbol project={project} opening={o} scale={scale} selected={ghost||selected.includes(o.id)} exportMode={exportMode}/></g>)}<EngineeringScene project={project} selected={selected} scale={scale} onDimension={onDimension} ghost={ghost} routeMode={routeMode} exportMode={exportMode}/></g>}
