import {withFurniture} from './furniture-data.mjs';
export const siteLayers=()=>[{id:'fences',name:'Ограждения',visible:true,locked:false},{id:'clearances',name:'Отступы и проверки',visible:true,locked:false}];
export const siteDefaults=()=>({northAngle:0,northPosition:{x:-2,y:-2},boundaryOffset:0,minPassage:0,showZones:true,intentional:[]});
export function withSite(p){p=withFurniture(p);return {...p,schemaVersion:Math.max(8,p.schemaVersion),layers:[...p.layers,...siteLayers().filter(l=>!p.layers.some(n=>n.id===l.id))],fences:p.fences??[],clearanceRules:p.clearanceRules??[],settings:{...p.settings,site:p.settings.site??siteDefaults()}};}
const point=p=>p&&Number.isFinite(p.x)&&Number.isFinite(p.y)&&Math.abs(p.x)<=1e6&&Math.abs(p.y)<=1e6;
const positive=n=>Number.isFinite(n)&&n>1e-5&&n<=1000;
export function segmentFrame(f,id){const i=f.segmentIds.indexOf(id);if(i<0)throw Error('Сегмент ограждения не найден');const a=f.points[i],b=f.points[i+1],length=Math.hypot(b.x-a.x,b.y-a.y);return {a,b,length,u:{x:(b.x-a.x)/length,y:(b.y-a.y)/length}};}
export function fencePoint(f,id,offset){const g=segmentFrame(f,id);return{x:g.a.x+g.u.x*offset,y:g.a.y+g.u.y*offset};}
/** Generate an actual bill of elements. Corners share one post; openings cut every affected span. */
export function fenceLayout(f){if(!positive(f.interval)||!Array.isArray(f.points)||f.points.some(v=>!point(v)))throw Error('Некорректные координаты или шаг столбов');const posts=[],sections=[];let total=0;for(const segmentId of f.segmentIds){const g=segmentFrame(f,segmentId);total+=g.length;const openings=f.openings.filter(o=>o.segmentId===segmentId).sort((a,b)=>a.offset-b.offset);let end=0;for(const o of openings){if(!positive(o.width)||!Number.isFinite(o.offset)||o.offset<0||o.offset+o.width>g.length+1e-7||o.offset<end-1e-7)throw Error('Проём выходит из сегмента или пересекает другой проём');end=o.offset+o.width;}
 const count=Math.ceil(g.length/f.interval);if(count>5000)throw Error('Слишком много столбов: увеличьте интервал');const offsets=[0,g.length,...openings.flatMap(o=>[o.offset,o.offset+o.width])];for(let i=1;i<count;i++)offsets.push(f.lastSpan==='equal'?g.length*i/count:f.interval*i);
 const cuts=[...new Set(offsets.map(n=>Math.round(n*1e8)/1e8))].sort((a,b)=>a-b).filter(n=>!openings.some(o=>n>o.offset+1e-7&&n<o.offset+o.width-1e-7));
 for(const offset of cuts){const q=fencePoint(f,segmentId,offset);if(!posts.some(p=>Math.hypot(p.point.x-q.x,p.point.y-q.y)<1e-7))posts.push({segmentId,offset,point:q});}
 for(let i=1;i<cuts.length;i++){const start=cuts[i-1],end=cuts[i];if(end-start>1e-7&&!openings.some(o=>(start+end)/2>o.offset-1e-7&&(start+end)/2<o.offset+o.width+1e-7))sections.push({segmentId,start,end});}
 }if(posts.length+sections.length>10000)throw Error('Слишком много элементов ограждения');return{posts,sections,total};}
export function regenerateFence(f){const layout=fenceLayout(f),reuse=(items,item,keys)=>items?.find(old=>keys.every(k=>Math.abs((old[k]??0)-(item[k]??0))<1e-7)&&old.segmentId===item.segmentId)?.id??crypto.randomUUID();return {...f,posts:layout.posts.map(({point,...item})=>({...item,id:reuse(f.posts,item,['offset'])})),sections:layout.sections.map(item=>({...item,id:reuse(f.sections,item,['start','end'])}))};}
export function validateSite(p){if(p.schemaVersion<8){if(p.fences!==undefined||p.clearanceRules!==undefined||p.settings.site!==undefined)throw Error('Участок и ограждения требуют формат v8');return;}
 if(!Array.isArray(p.fences)||p.fences.length>100||!Array.isArray(p.clearanceRules)||p.clearanceRules.length>1000)throw Error('Некорректные ограждения или зоны');const s=p.settings.site;if(!s||!Number.isFinite(s.northAngle)||Math.abs(s.northAngle)>360||!point(s.northPosition)||![s.boundaryOffset,s.minPassage].every(n=>Number.isFinite(n)&&n>=0&&n<=100)||typeof s.showZones!=='boolean'||!Array.isArray(s.intentional)||s.intentional.length>10000||s.intentional.some(x=>typeof x!=='string'||x.length>300))throw Error('Некорректные ограничения участка');
 const ids=new Set([...Object.keys(p.nodes),...p.objects.map(o=>o.id),...p.openings.map(o=>o.id),...(p.groups??[]).map(o=>o.id),...(p.rooms??[]).map(o=>o.id),...(p.library??[]).map(o=>o.id),...(p.resources??[]).map(o=>o.id),...(p.underlays??[]).map(o=>o.id),...(p.jointConstraints??[]).map(o=>o.id)]);const add=id=>{if(typeof id!=='string'||!/^[a-zA-Z0-9-]{1,80}$/.test(id)||ids.has(id))throw Error('Повторный или неверный ID элемента участка');ids.add(id)};
 for(const f of p.fences){add(f.id);if(typeof f.name!=='string'||f.name.length>200||!['wood','metal','mesh','masonry'].includes(f.kind)||!positive(f.height)||!positive(f.screenWidth)||f.screenWidth>20||!positive(f.interval)||!['remainder','equal'].includes(f.lastSpan)||!Array.isArray(f.points)||f.points.length<2||f.points.length>101||f.points.some(v=>!point(v))||!Array.isArray(f.segmentIds)||f.segmentIds.length!==f.points.length-1||!Array.isArray(f.openings)||f.openings.length>1000||!Array.isArray(f.posts)||!Array.isArray(f.sections))throw Error('Некорректное ограждение');f.segmentIds.forEach(add);for(const id of f.segmentIds)if(segmentFrame(f,id).length<1e-5)throw Error('Нулевой сегмент ограждения');for(const o of f.openings){add(o.id);if(!['swing','sliding','wicket'].includes(o.kind)||![1,-1].includes(o.side)||!['start','end'].includes(o.hinge)||typeof o.name!=='string'||o.name.length>200||!f.segmentIds.includes(o.segmentId))throw Error('Некорректные ворота');}
 const layout=fenceLayout(f);for(const key of ['posts','sections']){if(f[key].length!==layout[key].length)throw Error('Ведомость ограждения не соответствует геометрии');for(let i=0;i<f[key].length;i++){const actual=f[key][i],expected=layout[key][i];add(actual.id);if(actual.segmentId!==expected.segmentId||(key==='posts'?['offset']:['start','end']).some(k=>!Number.isFinite(actual[k])||Math.abs(actual[k]-expected[k])>1e-7))throw Error('Некорректный элемент ограждения');}}
 }
 for(const r of p.clearanceRules){add(r.id);if(typeof r.objectId!=='string'||!['front','back','left','right'].includes(r.side)||!positive(r.depth))throw Error('Некорректная зона свободного пространства');/* Deleted targets remain visible in the panel until explicitly removed. */}
}
export function assertSiteEdits(before,after){if(before.id!==after.id)return;for(const [layer,fields]of [['fences',['fences']],['clearances',['clearanceRules']]])if(before.layers.find(l=>l.id===layer)?.locked){for(const key of fields)if(JSON.stringify(before[key])!==JSON.stringify(after[key]))throw Error('Слой участка заблокирован');if(layer==='clearances'&&JSON.stringify(before.settings.site)!==JSON.stringify(after.settings.site))throw Error('Слой проверок заблокирован');}}
export function createFence(p,points){p=withSite(p);const f=regenerateFence({id:crypto.randomUUID(),name:'Ограждение',points:structuredClone(points),segmentIds:points.slice(1).map(()=>crypto.randomUUID()),kind:'metal',height:1.8,screenWidth:3,interval:2.5,lastSpan:'remainder',openings:[],posts:[],sections:[]});return {...p,fences:[...p.fences,f]};}
export function updateFence(p,id,patch){return {...p,fences:p.fences.map(f=>f.id===id?regenerateFence({...f,...patch}):f)};}
export function addGate(p,fenceId,segmentId,kind,width,offset){const f=p.fences.find(f=>f.id===fenceId);return updateFence(p,fenceId,{openings:[...f.openings,{id:crypto.randomUUID(),name:kind==='wicket'?'Калитка':'Ворота',segmentId,kind,width,offset,side:1,hinge:'start'}]});}
