import {fixturePolygon,wallPolygons,polygonDistance,swingZones,gateFrame,strip,freeZone,pointDistance,boundaryPoints,contains,edgeDistance} from './site-analysis.mjs';
import {openingGeometry} from './openings.mjs';
import {fencePoint} from './site.mjs';
const bbox=v=>({minX:Math.min(...v.map(q=>q.x)),maxX:Math.max(...v.map(q=>q.x)),minY:Math.min(...v.map(q=>q.y)),maxY:Math.max(...v.map(q=>q.y))});
const bboxGap=(a,b)=>{const x=bbox(a),y=bbox(b);return Math.hypot(Math.max(0,x.minX-y.maxX,y.minX-x.maxX),Math.max(0,x.minY-y.maxY,y.minY-x.maxY))};
/** Explicit full analysis. Never called by Scene or pointer-move handlers. Curves sampled at <=3 degrees. */
export function analyzeSite(p){const s=p.settings.site??{boundaryOffset:0,minPassage:0,intentional:[]},issues=[],fixtures=p.objects.filter(o=>o.type==='fixture').map(o=>({o,polys:[fixturePolygon(p,o)]})),walls=p.objects.filter(o=>o.type==='wall').map(o=>({o,polys:wallPolygons(p,o)}));if(fixtures.length+walls.length+(p.fences??[]).reduce((n,f)=>n+f.openings.length+f.sections.length,0)>2000)throw Error('Полная проверка ограничена 2000 стенами и предметами');const add=(type,objects,description,points)=>{const key=type+':'+objects.map(o=>o.id).sort().join(':');if(!issues.some(i=>i.key===key))issues.push({key,type,objectIds:objects.map(o=>o.id),names:objects.map(o=>o.name).join(' / '),description,points,intentional:s.intentional.includes(key)});};const overlaps=(a,b)=>a.polys.some(x=>b.polys.some(y=>bboxGap(x,y)<1e-7&&polygonDistance(x,y)<1e-7));
 for(let i=0;i<fixtures.length;i++){const a=fixtures[i];for(const b of walls){if(overlaps(a,b))add('Стена', [a.o,b.o],'Предмет пересекает тело стены.',a.polys[0]);else if(s.minPassage>0&&a.o.wallMount?.wallId!==b.o.id){let gap=Infinity;for(const poly of b.polys)if(bboxGap(a.polys[0],poly)<s.minPassage)gap=Math.min(gap,polygonDistance(a.polys[0],poly));if(gap<s.minPassage-1e-7)add('Проход',[a.o,b.o],`Зазор до стены ${gap.toFixed(2)} м меньше заданного ${s.minPassage.toFixed(2)} м.`,a.polys[0]);}}for(const b of fixtures.slice(i+1)){if(bboxGap(a.polys[0],b.polys[0])>Math.max(s.minPassage,1e-7))continue;const distance=polygonDistance(a.polys[0],b.polys[0]);if(distance<1e-7)add('Наложение',[a.o,b.o],'Предметы соприкасаются или накладываются.',[...a.polys[0],...b.polys[0]]);else if(s.minPassage>0&&distance<s.minPassage-1e-7)add('Проход',[a.o,b.o],`Зазор ${distance.toFixed(2)} м меньше заданного ${s.minPassage.toFixed(2)} м. Это расстояние между предметами, не расчёт маршрута эвакуации.`,[...a.polys[0],...b.polys[0]]);}}
 const barriers=(p.fences??[]).map(f=>({o:f,polys:f.sections.map(sec=>[fencePoint(f,sec.segmentId,sec.start),fencePoint(f,sec.segmentId,sec.end)])}));for(const a of fixtures)for(const b of barriers)if(overlaps(a,b))add('Ограждение',[a.o,b.o],'Предмет пересекает линию секции ограждения.',a.polys[0]);
 const swings=[...p.openings.filter(o=>o.type==='door'&&!p.objects.find(w=>w.id===o.wallId)?.curve).map(o=>({o,polys:swingZones(openingGeometry(p,o),o),source:o.wallId})),...(p.fences??[]).flatMap(f=>f.openings.map(o=>({o,polys:swingZones(gateFrame(f,o),o,true),source:f.id,segmentId:o.segmentId})))];for(const a of swings){for(const b of [...fixtures,...walls])if(b.o.id!==a.source&&overlaps(a,b))add('Открывание',[a.o,b.o],'Предмет или стена попадает в зону открывания / сдвига створки.',a.polys.flat());for(const f of p.fences??[])for(const sec of f.sections){if(f.id===a.source&&sec.segmentId===a.segmentId)continue;const poly=[fencePoint(f,sec.segmentId,sec.start),fencePoint(f,sec.segmentId,sec.end)];if(a.polys.some(v=>polygonDistance(v,poly)<1e-7))add('Открывание',[a.o,f],'Створка пересекает секцию ограждения.',a.polys.flat());}}
 for(const r of p.clearanceRules??[]){const owner=p.objects.find(o=>o.id===r.objectId),poly=freeZone(p,r);if(!owner){add('Зона', [{id:r.id,name:'Удалённый предмет'}],'Удалите правило: его предмет отсутствует.',[]);continue;}for(const b of [...fixtures,...walls,...barriers])if(b.o.id!==r.objectId&&b.polys.some(v=>polygonDistance(poly,v)<1e-7))add('Свободное место',[{id:r.id,name:owner.name},b.o],`Заданный запас ${r.depth.toFixed(2)} м занят.`,poly);}
 if(s.boundaryOffset>0)for(const plot of p.objects.filter(o=>['plot','outline'].includes(o.type))){const boundary=boundaryPoints(p,plot);const targets=[...fixtures,...p.objects.filter(o=>o.type==='building').map(o=>({o,polys:[boundaryPoints(p,o)]})),...(p.fences??[]).map(f=>({o:f,polys:[f.points]}))];for(const a of targets){let minimum=Infinity,outside=false;for(const q of a.polys.flat()){outside ||= !contains(boundary,q);for(let i=0;i<boundary.length;i++)minimum=Math.min(minimum,pointDistance(q,boundary[i],boundary[(i+1)%boundary.length]));}for(const poly of a.polys){minimum=Math.min(minimum,edgeDistance(poly,boundary));if(minimum<1e-7)outside=true;}if(outside||minimum<s.boundaryOffset-1e-7)add('Отступ',[a.o,plot],outside?'Объект касается или выходит за границу участка.':`Отступ ${minimum.toFixed(2)} м меньше пользовательского ${s.boundaryOffset.toFixed(2)} м.`,a.polys.flat());}}
 const buildings=p.objects.filter(o=>o.type==='building').map(o=>({o,polys:[boundaryPoints(p,o)]}));if(s.minPassage>0)for(let i=0;i<buildings.length;i++)for(const b of buildings.slice(i+1)){const a=buildings[i];if(bboxGap(a.polys[0],b.polys[0])>=s.minPassage)continue;const distance=polygonDistance(a.polys[0],b.polys[0]);if(distance<s.minPassage-1e-7)add('Между постройками',[a.o,b.o],`Зазор ${distance.toFixed(2)} м меньше пользовательского ${s.minPassage.toFixed(2)} м.`,[...a.polys[0],...b.polys[0]]);}
 for(let i=0;i<swings.length;i++)for(const b of swings.slice(i+1))if(overlaps(swings[i],b))add('Открывание',[swings[i].o,b.o],'Зоны открывания двух проёмов пересекаются.',swings[i].polys.flat());
 return issues;
}
