import {wallCurve} from './curved-walls.mjs';
import {curvePoint,projectOnCurve,onCurve,tangentPoints,lineCurveIntersections,curveIntersections} from './curve-math.mjs';
import {distance} from './core.mjs';
import {edges,projectOnSegment,vertices} from './geometry.mjs';
/** @type {import('./types').SnapSettings} */
export const defaultSnapSettings={locked:true,grid:true,nodes:true,midpoints:true,intersections:true,walls:true,guides:true,extensions:true,centers:true,angleStep:0,relation:'none',tolerance:8};
/** @param {import('./types').Point} a @param {import('./types').Point} b @param {import('./types').Point} c @param {import('./types').Point} d */
export function intersection(a,b,c,d){const dx=b.x-a.x,dy=b.y-a.y,ex=d.x-c.x,ey=d.y-c.y,den=dx*ey-dy*ex;if(Math.abs(den)<1e-10)return null;const t=((c.x-a.x)*ey-(c.y-a.y)*ex)/den,u=((c.x-a.x)*dy-(c.y-a.y)*dx)/den;if(t<0||t>1||u<0||u>1)return null;return{x:a.x+t*dx,y:a.y+t*dy};}
/** @param {import('./types').Project} project @param {import('./types').Point} raw @param {number} scale @param {import('./types').SnapSettings} settings @param {{disabled?:boolean,exclude?:string[],origin?:import('./types').Point,referenceId?:string,previous?:any}} options */
export function snapPoint(project,raw,scale,settings=defaultSnapSettings,options={}){
 if(options.disabled)return{point:raw,label:'Без привязки',key:'none',guides:[]};
 const tolerance=settings.tolerance/scale,exclude=options.exclude??[],ignoredNodes=new Set(project.objects.filter(o=>exclude.includes(o.id)).flatMap(o=>o.vertexIds)),objects=project.objects.filter(o=>!exclude.includes(o.id)&&(o.type!=='guide'||settings.savedGuides!==false)),segments=objects.flatMap(o=>edges(project,o).map(e=>({...e,objectId:o.id,type:o.type})));const curves=objects.filter(o=>o.curve).map(o=>({object:o,curve:wallCurve(project,o)}));const linear=segments.filter(e=>!e.curve);segments.splice(0,segments.length,...linear);const candidates=[];
 const add=(point,label,priority,key,nodeId=undefined,guides=[])=>{const d=distance(point,raw);if(d<=tolerance)candidates.push({point,label,priority,key,nodeId,guides,d})};
 for(const o of objects.filter(o=>o.type==='guide')){const a=project.nodes[o.vertexIds[0]],b=project.nodes[o.vertexIds[1]],dx=b.x-a.x,dy=b.y-a.y,t=((raw.x-a.x)*dx+(raw.y-a.y)*dy)/(dx*dx+dy*dy);add({x:a.x+t*dx,y:a.y+t*dy},'Сохранённая ось · '+o.name,1,'saved-guide:'+o.id)}
 for(const {object,curve}of curves){if(settings.centers){add(curve.center,'Центр окружности',1,'curve-center:'+object.id,object.curve.centerId);for(const angle of [0,90,180,270]){const point=curvePoint({...curve,startAngle:angle},0);if(onCurve(curve,point))add(point,'Квадрант',1,'quadrant:'+object.id+':'+angle)}}if(settings.midpoints&&curve.kind==='arc')add(curvePoint(curve,.5),'Середина по длине дуги',1,'curve-mid:'+object.id);if(settings.walls)add(projectOnCurve(curve,raw).point,'На дуге',3,'curve:'+object.id);if(options.origin&&settings.extensions)for(const point of tangentPoints(curve,options.origin))add(point,'Касательная',1,'tangent:'+object.id+':'+point.x);if(settings.intersections){for(const e of linear)for(const point of lineCurveIntersections(e.a,e.b,curve))add(point,'Пересечение прямой и дуги',1,'line-curve:'+object.id+':'+e.objectId+':'+point.x);for(const other of curves.filter(c=>c.object.id>object.id)){try{for(const point of curveIntersections(curve,other.curve))add(point,'Пересечение дуг',1,'curve-curve:'+object.id+':'+other.object.id+':'+point.x)}catch{}}}}
 if(settings.nodes)for(const node of Object.values(project.nodes))if(!ignoredNodes.has(node.id)&&objects.some(o=>o.vertexIds.includes(node.id)))add(node,'Вершина / конец',0,'node:'+node.id,node.id);
 if(settings.midpoints)for(const e of segments)add({x:(e.a.x+e.b.x)/2,y:(e.a.y+e.b.y)/2},'Середина',1,'mid:'+e.objectId+':'+e.index);
 if(settings.intersections){const nearby=segments.filter(e=>raw.x>=Math.min(e.a.x,e.b.x)-tolerance&&raw.x<=Math.max(e.a.x,e.b.x)+tolerance&&raw.y>=Math.min(e.a.y,e.b.y)-tolerance&&raw.y<=Math.max(e.a.y,e.b.y)+tolerance);for(let i=0;i<nearby.length;i++)for(let j=i+1;j<nearby.length;j++){const a=nearby[i],b=nearby[j],hit=intersection(a.a,a.b,b.a,b.b);if(hit)add(hit,'Пересечение',1,'intersection:'+a.objectId+':'+a.index+':'+b.objectId+':'+b.index)}}
 if(settings.walls)for(const e of segments.filter(e=>e.type==='wall'))add(projectOnSegment(raw,e.a,e.b).point,'На стене',3,'wall:'+e.objectId,undefined,[e.a,e.b]);
 if(settings.centers)for(const o of objects.filter(o=>!o.curve)){const v=vertices(project,o),minX=Math.min(...v.map(n=>n.x)),maxX=Math.max(...v.map(n=>n.x)),minY=Math.min(...v.map(n=>n.y)),maxY=Math.max(...v.map(n=>n.y)),cx=(minX+maxX)/2,cy=(minY+maxY)/2;add({x:cx,y:cy},'Центр объекта',2,'center:'+o.id);for(const [i,p] of [{x:minX,y:cy},{x:maxX,y:cy},{x:cx,y:minY},{x:cx,y:maxY}].entries())add(p,'Край объекта',2,'edge:'+o.id+':'+i)}
 if(settings.extensions)for(const e of segments){const dx=e.b.x-e.a.x,dy=e.b.y-e.a.y,t=((raw.x-e.a.x)*dx+(raw.y-e.a.y)*dy)/(dx*dx+dy*dy);if(t<0||t>1)add({x:e.a.x+dx*t,y:e.a.y+dy*t},'Продолжение',5,'extension:'+e.objectId+':'+e.index,undefined,[e.a,e.b])}
 const guidePoints=[...objects.flatMap(o=>vertices(project,o)),...(options.origin?[options.origin]:[])];
 if(settings.centers)for(const o of objects){const v=vertices(project,o);guidePoints.push({x:(Math.min(...v.map(n=>n.x))+Math.max(...v.map(n=>n.x)))/2,y:(Math.min(...v.map(n=>n.y))+Math.max(...v.map(n=>n.y)))/2})}
 if(settings.guides&&guidePoints.length){const xs=guidePoints.map(p=>({p,d:Math.abs(p.x-raw.x)})).filter(p=>p.d<=tolerance).sort((a,b)=>a.d-b.d),ys=guidePoints.map(p=>({p,d:Math.abs(p.y-raw.y)})).filter(p=>p.d<=tolerance).sort((a,b)=>a.d-b.d);if(xs[0]&&ys[0])add({x:xs[0].p.x,y:ys[0].p.y},'Выравнивание X/Y',3,'guide:xy',undefined,[{x:xs[0].p.x,y:ys[0].p.y},raw]);if(xs[0])add({x:xs[0].p.x,y:raw.y},'Вертикальная направляющая',4,'guide:x:'+xs[0].p.x,undefined,[xs[0].p,{x:xs[0].p.x,y:raw.y}]);if(ys[0])add({x:raw.x,y:ys[0].p.y},'Горизонтальная направляющая',4,'guide:y:'+ys[0].p.y,undefined,[ys[0].p,{x:raw.x,y:ys[0].p.y}]);}
 if(options.origin){const origin=options.origin,reference=project.objects.find(o=>o.id===options.referenceId),e=reference?edges(project,reference)[0]:null;let theta=null,label='Шаг угла';if(settings.relation!=='none'&&e){theta=e.angle*Math.PI/180+(settings.relation==='perpendicular'?Math.PI/2:0);label=settings.relation==='parallel'?'Параллельно опоре':'Перпендикулярно опоре'}else if(settings.angleStep>0)theta=Math.round(Math.atan2(raw.y-origin.y,raw.x-origin.x)/(settings.angleStep*Math.PI/180))*settings.angleStep*Math.PI/180;if(theta!==null){const u={x:Math.cos(theta),y:Math.sin(theta)},t=(raw.x-origin.x)*u.x+(raw.y-origin.y)*u.y,point={x:origin.x+u.x*t,y:origin.y+u.y*t};add(point,label,2,'angle:'+theta,undefined,[origin,point]);}}
 candidates.sort((a,b)=>a.priority-b.priority||a.d-b.d||a.key.localeCompare(b.key));const retained=options.previous?candidates.find(c=>c.key===options.previous.key&&c.d<=tolerance&&c.priority<=(candidates[0]?.priority??100)):null;const target=retained??candidates[0];if(target)return target;
 if(settings.grid){const step=project.settings.snap;return{point:{x:Math.round(raw.x/step)*step,y:Math.round(raw.y/step)*step},label:'Сетка',key:'grid',guides:[]}}return{point:raw,label:'Свободно',key:'none',guides:[]};
}
