export const RESOURCE_LIMIT = 20 * 1024 * 1024;
export const PIXEL_LIMIT = 24_000_000;
export const RESOURCE_MIMES = ['image/png','image/jpeg','image/webp','application/pdf'];
export const underlayLayer = () => ({id:'underlays',name:'Подложки',visible:true,locked:false});
export function withUnderlays(p){return {...p,schemaVersion:Math.max(5,p.schemaVersion),layers:[...p.layers,...(p.layers.some(l=>l.id==='annotations')?[]:[{id:'annotations',name:'Разметка',visible:true,locked:false},{id:'guidelines',name:'Направляющие',visible:true,locked:false}]),...(p.layers.some(l=>l.id==='underlays')?[]:[underlayLayer()])],resources:p.resources??[],underlays:p.underlays??[]}}
const idOK=id=>typeof id==='string'&&/^[a-zA-Z0-9-]{1,80}$/.test(id);
export function validateUnderlays(p){
 if(p.schemaVersion<5){if(p.resources!==undefined||p.underlays!==undefined)throw Error('Файловые ресурсы требуют формат v5');return}
 if(!Array.isArray(p.resources)||p.resources.length>200||!Array.isArray(p.underlays)||p.underlays.length>100)throw Error('Некорректные файловые ресурсы');
 const used=new Set([...Object.keys(p.nodes),...p.objects.map(o=>o.id),...p.openings.map(o=>o.id)]);
 for(const r of p.resources){if(!idOK(r.id)||used.has(r.id)||typeof r.name!=='string'||r.name.length>200||!RESOURCE_MIMES.includes(r.mimeType)||!Number.isSafeInteger(r.byteLength)||r.byteLength<1||r.byteLength>RESOURCE_LIMIT||typeof r.sha256!=='string'||!/^[a-f0-9]{64}$/.test(r.sha256)||r.id!==r.sha256)throw Error('Некорректный файловый ресурс');used.add(r.id);if(r.mimeType!=='application/pdf'&&(!Number.isSafeInteger(r.width)||!Number.isSafeInteger(r.height)||r.width<1||r.height<1||r.width>8192||r.height>8192||r.width*r.height>PIXEL_LIMIT))throw Error('Изображение: до 8192 px и 24 Мп')}
 for(const u of p.underlays){const r=p.resources.find(r=>r.id===u.resourceId),source=p.resources.find(r=>r.id===u.sourceId);if(!idOK(u.id)||used.has(u.id)||typeof u.name!=='string'||u.name.length>200||!r||r.mimeType==='application/pdf'||!source||u.layerId!=='underlays'||![u.x,u.y,u.angle,u.opacity,u.metersPerPixel].every(Number.isFinite)||Math.abs(u.x)>1e6||Math.abs(u.y)>1e6||u.metersPerPixel<=1e-8||u.metersPerPixel>1e4||u.opacity<0||u.opacity>1||typeof u.visible!=='boolean'||typeof u.locked!=='boolean'||!['site','floor'].includes(u.scope)||u.scope==='floor'&&(typeof u.floorId!=='string'||!u.floorId.trim()||u.floorId.length>80))throw Error('Некорректная подложка');used.add(u.id);const c=u.crop;if(!c||![c.x,c.y,c.width,c.height].every(Number.isFinite)||c.x<0||c.y<0||c.width<=0||c.height<=0||c.x+c.width>r.width+1e-6||c.y+c.height>r.height+1e-6)throw Error('Обрезка выходит за изображение');if(source.mimeType==='application/pdf'&&(!Number.isInteger(u.page)||u.page<1||u.page>1000))throw Error('Некорректная страница PDF');if(u.calibration){const {a,b,length}=u.calibration;if(!a||!b||![a.x,a.y,b.x,b.y,length].every(Number.isFinite)||length<=0||Math.hypot(a.x-b.x,a.y-b.y)<1e-6||[a,b].some(n=>n.x<0||n.y<0||n.x>r.width||n.y>r.height)||Math.abs(u.metersPerPixel-length/Math.hypot(a.x-b.x,a.y-b.y))>1e-8)throw Error('Некорректная калибровка')}}
}
export function addUnderlay(p,resources,options={}){const next=withUnderlays(p),r=resources.at(-1),source=resources[0],id=crypto.randomUUID();return {...next,resources:[...next.resources,...resources.filter(r=>!next.resources.some(n=>n.id===r.id))].filter((r,i,a)=>a.findIndex(n=>n.id===r.id)===i),underlays:[...next.underlays,{id,name:source.name,resourceId:r.id,sourceId:source.id,page:options.page,x:0,y:0,angle:0,opacity:.55,visible:true,locked:false,scope:'site',layerId:'underlays',metersPerPixel:10/r.width,crop:{x:0,y:0,width:r.width,height:r.height}}]}}
export function imageToWorld(u,n){const a=u.angle*Math.PI/180,x=(n.x-u.crop.x)*u.metersPerPixel,y=(n.y-u.crop.y)*u.metersPerPixel;return{x:u.x+x*Math.cos(a)-y*Math.sin(a),y:u.y+x*Math.sin(a)+y*Math.cos(a)}}
export function worldToImage(u,n){const a=-u.angle*Math.PI/180,x=n.x-u.x,y=n.y-u.y;return{x:(x*Math.cos(a)-y*Math.sin(a))/u.metersPerPixel+u.crop.x,y:(x*Math.sin(a)+y*Math.cos(a))/u.metersPerPixel+u.crop.y}}
export const underlayCorners=u=>[{x:u.crop.x,y:u.crop.y},{x:u.crop.x+u.crop.width,y:u.crop.y},{x:u.crop.x+u.crop.width,y:u.crop.y+u.crop.height},{x:u.crop.x,y:u.crop.y+u.crop.height}].map(n=>imageToWorld(u,n));
export function cropUnderlay(p,id,crop){const u=p.underlays?.find(u=>u.id===id);if(!u)throw Error('Подложка не найдена');const anchor=imageToWorld(u,{x:crop.x,y:crop.y});return {...p,underlays:p.underlays.map(n=>n.id===id?{...n,x:anchor.x,y:anchor.y,crop}:n)}}
export function calibrateUnderlay(p,id,a,b,length){const u=p.underlays?.find(u=>u.id===id);if(!u)throw Error('Подложка не найдена');const d=Math.hypot(a.x-b.x,a.y-b.y);if(!Number.isFinite(length)||length<=0||!Number.isFinite(d)||d<1e-6)throw Error('Укажите две разные точки и положительную длину');const oldAnchor=imageToWorld(u,a),next={...u,metersPerPixel:length/d,calibration:{a,b,length}};const shifted=imageToWorld(next,a);next.x+=oldAnchor.x-shifted.x;next.y+=oldAnchor.y-shifted.y;return {...p,underlays:p.underlays.map(n=>n.id===id?next:n)}}
export function assertUnderlayEdits(before,after){if(before.id!==after.id)return;for(const u of before.underlays??[]){const n=after.underlays?.find(n=>n.id===u.id),locked=u.locked||before.layers.find(l=>l.id==='underlays')?.locked;if(!locked)continue;const shape=v=>v?JSON.stringify({...v,locked:undefined,visible:undefined}):null;if(shape(u)!==shape(n))throw Error('Подложка заблокирована: '+u.name)}if(after.layers.find(l=>l.id==='underlays')?.locked&&(after.underlays??[]).some(u=>!before.underlays?.some(n=>n.id===u.id)))throw Error('Слой подложек заблокирован')}
