import {wallCurve,wallLength,setWallCurve,splitCurvedWall} from './curved-walls.mjs';
import {curvePoint,curveParameter,onCurve,lineCurveIntersections,curveIntersections,splitCurve} from './curve-math.mjs';
const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
export function wallIntersections(p,ids,extend=false){
 const [a,b]=ids.map(id=>p.objects.find(o=>o.id===id&&o.type==='wall'));if(!a||!b||a.id===b.id)throw Error('Выберите две разные стены');
 if(a.curve&&b.curve)return curveIntersections({...wallCurve(p,a),...(extend?{kind:'circle',sweepAngle:Math.sign(a.curve.sweepAngle)*360}:{})},{...wallCurve(p,b),...(extend?{kind:'circle',sweepAngle:Math.sign(b.curve.sweepAngle)*360}:{})});
 if(a.curve||b.curve){const c=a.curve?a:b,l=a.curve?b:a;return lineCurveIntersections(p.nodes[l.vertexIds[0]],p.nodes[l.vertexIds[1]],{...wallCurve(p,c),...(extend?{kind:'circle',sweepAngle:Math.sign(c.curve.sweepAngle)*360}:{})},extend)}
 const aa=p.nodes[a.vertexIds[0]],ab=p.nodes[a.vertexIds[1]],ba=p.nodes[b.vertexIds[0]],bb=p.nodes[b.vertexIds[1]],dx=ab.x-aa.x,dy=ab.y-aa.y,ex=bb.x-ba.x,ey=bb.y-ba.y,d=dx*ey-dy*ex;if(Math.abs(d)<1e-10)throw Error('Прямые параллельны или совпадают');const t=((ba.x-aa.x)*ey-(ba.y-aa.y)*ex)/d,u=((ba.x-aa.x)*dy-(ba.y-aa.y)*dx)/d;if(!extend&&(t<0||t>1||u<0||u>1))return[];return[{x:aa.x+t*dx,y:aa.y+t*dy}];
}
export function trimWallToPoint(p,id,point,endpoint='end'){
 const w=p.objects.find(o=>o.id===id&&o.type==='wall');if(!w)throw Error('Стена не найдена');if(w.locks?.length||w.buildingId||p.openings.some(o=>o.wallId===id)||p.objects.some(o=>o.wallMount?.wallId===id))throw Error('Стена имеет ограничения или связи: операция не применена');
 const changedNode=w.vertexIds[endpoint==='end'?1:0];if(p.objects.some(o=>o.id!==id&&o.vertexIds.includes(changedNode)))throw Error('Конец связан с другой геометрией: сначала отсоедините его');
 if(w.curve){const c=wallCurve(p,w);if(c.kind==='circle')throw Error('Для замкнутой стены сначала выберите две точки разделения');if(Math.abs(distance(point,c.center)-c.radius)>1e-6)throw Error('Точка должна лежать на осевой окружности');const angle=Math.atan2(point.y-c.center.y,point.x-c.center.x)*180/Math.PI,sign=Math.sign(c.sweepAngle),mod=v=>((v%360)+360)%360;const start=endpoint==='end'?c.startAngle:angle,end=endpoint==='end'?angle:c.startAngle+c.sweepAngle,sweep=sign*mod(sign*(end-start));return setWallCurve(p,id,{...c,startAngle:start,sweepAngle:sweep})}
 const nodeId=w.vertexIds[endpoint==='end'?1:0];return{...p,nodes:{...p.nodes,[nodeId]:{id:nodeId,...point}}};
}
export function splitWallAtDistance(p,id,offset){const w=p.objects.find(o=>o.id===id&&o.type==='wall');if(!w||!w.curve)throw Error('Выберите дугу');return splitCurvedWall(p,id,offset/wallLength(p,w))}
export function joinCompatibleWalls(p,ids){
 const [a,b]=ids.map(id=>p.objects.find(o=>o.id===id&&o.type==='wall'));if(a?.curve&&b?.curve)return joinCompatibleArcs(p,a,b);if(!a||!b||a.id===b.id||a.curve||b.curve||a.buildingId||b.buildingId||a.locks?.length||b.locks?.length)throw Error('Соединение доступно для свободных прямых стен');
 const shared=a.vertexIds.filter(id=>b.vertexIds.includes(id));if(shared.length!==1)throw Error('Стены должны иметь один общий узел');const joint=shared[0];if(p.objects.some(o=>!ids.includes(o.id)&&o.vertexIds.includes(joint))||p.objects.some(o=>ids.includes(o.wallMount?.wallId))||p.openings.some(o=>ids.includes(o.wallId)))throw Error('Стык имеет дополнительные связи');
 const start=p.nodes[a.vertexIds.find(id=>id!==joint)],end=p.nodes[b.vertexIds.find(id=>id!==joint)],middle=p.nodes[joint];if(Math.abs((middle.x-start.x)*(end.y-middle.y)-(middle.y-start.y)*(end.x-middle.x))>1e-7||distance(start,end)<Math.max(distance(start,middle),distance(end,middle)))throw Error('Соединение требует последовательные коллинеарные сегменты');
 if(a.thickness!==b.thickness||a.height!==b.height||a.layerId!==b.layerId||a.wallKind!==b.wallKind)throw Error('Параметры стен различаются');
 return{...p,objects:p.objects.filter(o=>o.id!==b.id).map(o=>o.id===a.id?{...o,vertexIds:[start.id,end.id]}:o)};
}
export function jointAngle(p,ids){const [a,b]=ids.map(id=>p.objects.find(o=>o.id===id&&o.type==='wall'));if(!a||!b||a.curve||b.curve)throw Error('Угол стыка: выберите две прямые стены');const common=a.vertexIds.filter(id=>b.vertexIds.includes(id));if(common.length!==1)throw Error('Стены должны иметь общий стык');const node=p.nodes[common[0]],va=p.nodes[a.vertexIds.find(id=>id!==node.id)],vb=p.nodes[b.vertexIds.find(id=>id!==node.id)],dot=((va.x-node.x)*(vb.x-node.x)+(va.y-node.y)*(vb.y-node.y))/(distance(va,node)*distance(vb,node));return{nodeId:node.id,angle:Math.acos(Math.max(-1,Math.min(1,dot)))*180/Math.PI}}
export function editJointAngle(p,ids,degrees,changedId,side=1,lock=false){
 if(!Number.isFinite(degrees)||degrees<=0||degrees>=180)throw Error('Угол стыка должен быть между 0° и 180°');const joint=jointAngle(p,ids),changed=p.objects.find(o=>o.id===changedId&&ids.includes(o.id)),fixed=p.objects.find(o=>ids.includes(o.id)&&o.id!==changedId);if(!changed||!fixed)throw Error('Выберите изменяемую стену');
 const node=p.nodes[joint.nodeId],endId=changed.vertexIds.find(id=>id!==node.id),end=p.nodes[endId],reference=p.nodes[fixed.vertexIds.find(id=>id!==node.id)],a=Math.atan2(reference.y-node.y,reference.x-node.x)+side*degrees*Math.PI/180,length=distance(node,end);
 const key=[...ids].sort().join(':');const constraints=(p.jointConstraints??[]).filter(c=>[...c.wallIds].sort().join(':')!==key);if(lock)constraints.push({id:crypto.randomUUID(),wallIds:ids,nodeId:node.id,angle:degrees,changedWallId:changedId});
 return{...p,schemaVersion:Math.max(p.schemaVersion,3),jointConstraints:constraints,nodes:{...p.nodes,[endId]:{...end,x:node.x+Math.cos(a)*length,y:node.y+Math.sin(a)*length}}};
}
function joinCompatibleArcs(p,a,b){if(a.id===b.id||a.curve.kind!=='arc'||b.curve.kind!=='arc'||a.buildingId||b.buildingId||p.objects.some(o=>o.boundaryWallIds?.some(id=>[a.id,b.id].includes(id)))||p.openings.some(o=>[a.id,b.id].includes(o.wallId))||p.objects.some(o=>[a.id,b.id].includes(o.wallMount?.wallId)))throw Error('Соединение дуг со связанными проёмами/контурами требует переноса связей');const ca=wallCurve(p,a),cb=wallCurve(p,b);if(distance(ca.center,cb.center)>1e-6||Math.abs(ca.radius-cb.radius)>1e-6||a.thickness!==b.thickness||a.height!==b.height||a.layerId!==b.layerId||a.wallKind!==b.wallKind)throw Error('Дуги должны принадлежать одной окружности и иметь одинаковые параметры');const shared=a.vertexIds.slice(0,2).filter(id=>b.vertexIds.slice(0,2).includes(id));if(shared.length!==1&&shared.length!==2)throw Error('Дуги должны иметь общий конец');const joint=a.vertexIds[1];if(!shared.includes(joint))return joinCompatibleArcs(p,{...a,vertexIds:[a.vertexIds[1],a.vertexIds[0],a.curve.centerId],curve:{...a.curve,startAngle:a.curve.startAngle+a.curve.sweepAngle,sweepAngle:-a.curve.sweepAngle}},b);if(p.objects.some(o=>![a.id,b.id].includes(o.id)&&o.vertexIds.includes(joint)))throw Error('Стык имеет дополнительные связи');const c1=a.vertexIds[1]===joint?ca:{...ca,startAngle:ca.startAngle+ca.sweepAngle,sweepAngle:-ca.sweepAngle},c2=b.vertexIds[0]===joint?cb:{...cb,startAngle:cb.startAngle+cb.sweepAngle,sweepAngle:-cb.sweepAngle};if(Math.sign(c1.sweepAngle)!==Math.sign(c2.sweepAngle)||Math.abs(c1.sweepAngle+c2.sweepAngle)>360+1e-7)throw Error('Дуги должны быть последовательными');const full=Math.abs(Math.abs(c1.sweepAngle+c2.sweepAngle)-360)<1e-7;const start=a.vertexIds.slice(0,2).find(id=>id!==joint),end=b.vertexIds.slice(0,2).find(id=>id!==joint);return{...p,objects:p.objects.filter(o=>o.id!==b.id).map(o=>o.id===a.id?{...a,vertexIds:full?[a.curve.centerId]:[start,end,a.curve.centerId],curve:{...a.curve,kind:full?'circle':'arc',startAngle:c1.startAngle,sweepAngle:c1.sweepAngle+c2.sweepAngle}}:o)}}
