import {withSite} from './site.mjs';
import {withFloors} from './floors.mjs';
import {validateProject} from './core.mjs';
import {vertices} from './geometry.mjs';
import {openingGeometry} from './openings.mjs';
export const notesLayer=()=>({id:'notes',name:'Заметки',visible:true,locked:false});
const idOK=id=>typeof id==='string'&&/^[a-zA-Z0-9-]{1,80}$/.test(id);
const point=p=>p&&Number.isFinite(p.x)&&Number.isFinite(p.y)&&Math.abs(p.x)<=1e6&&Math.abs(p.y)<=1e6;
export function variantDocument(p){const {workspace,notes,viewPresets,...doc}=structuredClone(p);return {...doc,schemaVersion:p.schemaVersion>=10?10:8,...(p.schemaVersion>=10?{variantSnapshot:true}:{}),layers:doc.layers.filter(l=>l.id!=='notes')};}
export function withWorkspace(input){if(input.schemaVersion>=9&&!input.variantSnapshot)return input;if(input.variantSnapshot){const {variantSnapshot,...root}=input;const id=crypto.randomUUID();return {...root,notes:[],viewPresets:[],layers:[...root.layers,notesLayer()],workspace:{activeVariantId:id,variants:[{id,name:'Текущее состояние',createdAt:new Date().toISOString(),document:variantDocument(input),notes:[]}]}}}const p=withSite(input),id=crypto.randomUUID();return {...p,schemaVersion:9,layers:[...p.layers,notesLayer()],notes:[],viewPresets:[],workspace:{activeVariantId:id,variants:[{id,name:'Текущее состояние',createdAt:new Date().toISOString(),document:variantDocument(p),notes:[]}]}};}
export function synchronizeWorkspace(p){
 if(p.schemaVersion<9||p.variantSnapshot)return p;
 const resources=new Map((p.resources??[]).map(r=>[r.id,r]));for(const v of p.workspace.variants)for(const r of [...v.document.resources??[],...(v.document.floorModel?[v.document.floorModel.site,...v.document.floorModel.levels].flatMap(f=>f.document.resources??[]):[])]){if(resources.has(r.id)&&['id','sha256','mimeType','byteLength','width','height'].some(key=>resources.get(r.id)[key]!==r[key]))throw Error('Метаданные общего файла различаются между вариантами');if(!resources.has(r.id))resources.set(r.id,r)}
 const shared=[...resources.values()];if(shared.length>200)throw Error('Общая библиотека: не более 200 файлов');
 const reserved=new Set([...Object.keys(p.nodes),...p.objects.map(o=>o.id),...p.openings.map(o=>o.id),...p.notes.map(o=>o.id),...p.workspace.variants.map(o=>o.id),...p.viewPresets.map(o=>o.id),...(p.groups??[]).map(o=>o.id),...(p.rooms??[]).map(o=>o.id),...(p.library??[]).map(o=>o.id),...(p.underlays??[]).map(o=>o.id),...(p.jointConstraints??[]).map(o=>o.id),...(p.clearanceRules??[]).map(o=>o.id),...(p.fences??[]).flatMap(o=>[o.id,...o.segmentIds,...o.posts.map(x=>x.id),...o.sections.map(x=>x.id),...o.openings.map(x=>x.id)])]);
 if(shared.some(r=>reserved.has(r.id)))throw Error('ID общего файла совпадает с объектом проекта');
 p={...p,notes:p.notes.map(n=>{const position=notePoint(p,n);if(!point(position))throw Error('Заметка выходит за пределы координат проекта');return {...n,position}})};
 const result={...p,resources:shared,workspace:{...p.workspace,variants:p.workspace.variants.map(v=>v.id===p.workspace.activeVariantId?{...v,document:{...variantDocument(p),resources:shared},notes:structuredClone(p.notes)}:{...v,document:{...v.document,resources:shared}})}};
 if(new TextEncoder().encode(JSON.stringify(result)).length>5*1024*1024)throw Error('Проект с вариантами превышает 5 МБ; уменьшите их число');return result;
}
export function validateWorkspace(p){if(p.variantSnapshot){if(p.schemaVersion!==10||p.workspace!==undefined||p.notes!==undefined||p.viewPresets!==undefined)throw Error('Некорректный внутренний снимок варианта');return;}if(p.schemaVersion<9){if(p.workspace!==undefined||p.notes!==undefined||p.viewPresets!==undefined)throw Error('Варианты и заметки требуют формат v9');return;}const w=p.workspace;if(!w||!Array.isArray(w.variants)||!w.variants.length||w.variants.length>12||!idOK(w.activeVariantId)||!w.variants.some(v=>v.id===w.activeVariantId)||!Array.isArray(p.notes)||!Array.isArray(p.viewPresets)||p.viewPresets.length>50)throw Error('Некорректные варианты проекта');const normalized=[],ids=new Set([...Object.keys(p.nodes),...p.objects.map(o=>o.id),...p.openings.map(o=>o.id),...p.notes.map(o=>o.id),...(p.groups??[]).map(o=>o.id),...(p.rooms??[]).map(o=>o.id),...(p.fences??[]).map(o=>o.id),...(p.resources??[]).map(o=>o.id),...(p.library??[]).map(o=>o.id)]);for(const v of w.variants){if(!idOK(v.id)||ids.has(v.id)||typeof v.name!=='string'||!v.name.trim()||v.name.length>80||!Number.isFinite(Date.parse(v.createdAt))||!v.document||!(p.schemaVersion===9&&v.document.schemaVersion===8||p.schemaVersion>=10&&v.document.schemaVersion===10&&v.document.variantSnapshot===true)||v.document.workspace!==undefined||v.document.notes!==undefined||v.document.viewPresets!==undefined)throw Error('Некорректный вариант');ids.add(v.id);const document=validateProject(v.document);validateNotes(v.notes,document);normalized.push({...v,document});}
 validateNotes(p.notes,p);for(const preset of p.viewPresets){if(!idOK(preset.id)||ids.has(preset.id)||typeof preset.name!=='string'||!preset.name.trim()||preset.name.length>80||!preset.visibility||Array.isArray(preset.visibility)||Object.entries(preset.visibility).some(([key,v])=>!p.layers.some(l=>l.id===key)||typeof v!=='boolean'))throw Error('Некорректный набор видимости');ids.add(preset.id)}
 return {...p,workspace:{...w,variants:normalized}};
}
export function validateNotes(notes,p){if(!Array.isArray(notes)||notes.length>500)throw Error('Слишком много заметок');const ids=new Set([...Object.keys(p.nodes),...p.objects.map(o=>o.id),...p.openings.map(o=>o.id),...(p.fences??[]).flatMap(o=>[o.id,...o.segmentIds,...o.openings.map(x=>x.id),...o.posts.map(x=>x.id),...o.sections.map(x=>x.id)]),...(p.clearanceRules??[]).map(o=>o.id),...(p.jointConstraints??[]).map(o=>o.id),...(p.groups??[]).map(o=>o.id),...(p.rooms??[]).map(o=>o.id),...(p.resources??[]).map(o=>o.id),...(p.library??[]).map(o=>o.id)]);for(const n of notes){if(!idOK(n.id)||ids.has(n.id)||typeof n.text!=='string'||n.text.length>2000||!point(n.position)||!point(n.offset)||n.objectId!==undefined&&!idOK(n.objectId)||!Array.isArray(n.photoIds)||n.photoIds.length>10||new Set(n.photoIds).size!==n.photoIds.length||n.photoIds.some(id=>!p.resources?.some(r=>r.id===id&&r.mimeType.startsWith('image/')))||!Number.isFinite(Date.parse(n.createdAt)))throw Error('Некорректная заметка или её фотография');ids.add(n.id)}}
export function variantProject(p,id){p=synchronizeWorkspace(withWorkspace(p));const v=p.workspace.variants.find(v=>v.id===id);if(!v)throw Error('Вариант не найден');const {variantSnapshot,...document}=structuredClone(v.document);return {...document,schemaVersion:Math.max(9,v.document.schemaVersion),id:p.id,name:p.name,revision:p.revision,createdAt:p.createdAt,updatedAt:p.updatedAt,resources:structuredClone(p.resources),notes:structuredClone(v.notes),layers:[...v.document.layers,structuredClone(p.layers.find(l=>l.id==='notes')??notesLayer())],viewPresets:structuredClone(p.viewPresets),workspace:structuredClone({...p.workspace,activeVariantId:id})};}
export function copyVariant(p,name){p=synchronizeWorkspace(withWorkspace(p));if(p.workspace.variants.length>=12)throw Error('В проекте не более 12 вариантов');const id=crypto.randomUUID(),v={id,name:name.trim(),createdAt:new Date().toISOString(),document:variantDocument(p),notes:structuredClone(p.notes)};return validateProject({...p,workspace:{...p.workspace,activeVariantId:id,variants:[...p.workspace.variants,v]}});}
export function deleteVariant(p,id){if(p.workspace.variants.length===1)throw Error('Последний вариант нельзя удалить');if(!p.workspace.variants.some(v=>v.id===id))throw Error('Вариант не найден');const next=p.workspace.activeVariantId===id?variantProject(p,p.workspace.variants.find(v=>v.id!==id).id):synchronizeWorkspace(p);return {...next,workspace:{...next.workspace,variants:next.workspace.variants.filter(v=>v.id!==id)}};}
export function notePoint(p,n){const o=p.objects.find(o=>o.id===n.objectId),opening=p.openings.find(o=>o.id===n.objectId),fence=p.fences?.find(o=>o.id===n.objectId);let a;if(o){const vs=vertices(p,o);a={x:vs.reduce((s,v)=>s+v.x,0)/vs.length,y:vs.reduce((s,v)=>s+v.y,0)/vs.length}}else if(opening)a=openingGeometry(p,opening).center;else if(fence)a=fence.points[0];return a?{x:a.x+n.offset.x,y:a.y+n.offset.y}:n.position;}
export function addNote(p,text,position,objectId){p=withWorkspace(p);const note={id:crypto.randomUUID(),text,position:structuredClone(position),offset:{x:0,y:0},objectId,photoIds:[],createdAt:new Date().toISOString()};return {...p,notes:[...p.notes,note]};}
export function compareVariants(p,leftId,rightId){const a=variantProject(p,leftId),b=variantProject(p,rightId),entities=q=>new Map([...q.objects,...q.openings,...(q.fences??[]),...(q.notes??[])].map(o=>[o.id,{object:o,fingerprint:JSON.stringify([o,o.vertexIds?.map(id=>q.nodes[id]),o.wallId?q.objects.find(w=>w.id===o.wallId)?.vertexIds.map(id=>q.nodes[id]):null])}])),left=entities(a),right=entities(b);return {left:a,right:b,added:[...right.keys()].filter(id=>!left.has(id)),removed:[...left.keys()].filter(id=>!right.has(id)),changed:[...right.keys()].filter(id=>left.has(id)&&right.get(id).fingerprint!==left.get(id).fingerprint)};}
export const builtInPresets={layout:['buildings','walls','openings','furniture','rooms','dimensions','labels','notes'],plumbing:['walls','openings','plumbing','pipes','dimensions','labels','notes'],electrical:['walls','openings','electrical','wires','dimensions','labels','notes'],site:['plot','buildings','paths','fences','clearances','dimensions','labels','notes']};
export function applyVisibility(p,visibility){return {...p,layers:p.layers.map(l=>({...l,visible:visibility[l.id]??l.visible}))};}
export function restoreVersion(current,document){const now=new Date().toISOString();let p=withWorkspace(structuredClone(document));if(current.schemaVersion>=10&&p.schemaVersion<10)p=withFloors(p);return validateProject({...p,id:current.id,name:current.name,revision:current.revision,createdAt:current.createdAt,updatedAt:now});}
export function assertWorkspaceEdits(before,after){if(before.id!==after.id)return;if(before.workspace?.activeVariantId!==after.workspace?.activeVariantId)return;if(before.layers.find(l=>l.id==='notes')?.locked&&JSON.stringify(before.notes)!==JSON.stringify(after.notes))throw Error('Слой заметок заблокирован');}
